{
  "swagger": "2.0",
  "info": {
    "title": "WorkItemTracking",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "5.0-preview"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Behaviors"
    },
    {
      "name": "Fields"
    },
    {
      "name": "Processes"
    },
    {
      "name": "Rules"
    },
    {
      "name": "States"
    },
    {
      "name": "Work Item Types"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/work/processes": {
      "post": {
        "tags": [
          "Processes"
        ],
        "description": "Creates a process.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Processes"
        ],
        "description": "Returns a list of all processes.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/behaviors": {
      "post": {
        "tags": [
          "Behaviors"
        ],
        "description": "Creates a single behavior in the given process.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Behaviors"
        ],
        "description": "Returns a list of all behaviors in the process.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/behaviors/{behaviorRefName}": {
      "delete": {
        "tags": [
          "Behaviors"
        ],
        "description": "Removes a behavior in the process.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Behaviors"
        ],
        "description": "Returns a behavior of the process.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Behaviors"
        ],
        "description": "Replaces a behavior in the process.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/fields": {
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Returns a list of all fields in a process.",
        "operationId": "Get Fields",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workitemtypes": {
      "post": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Creates a work item type in the process.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Returns a list of all work item types in a process.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workitemtypes/{witRefName}": {
      "delete": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Removes a work itewm type in the process.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Returns a single work item type in a process.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Updates a work item type of the process.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workItemTypes/{witRefName}/fields": {
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Returns a list of all fields in a work item type.",
        "operationId": "Get Work Item Type Fields",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workItemTypes/{witRefName}/rules": {
      "post": {
        "tags": [
          "Rules"
        ],
        "description": "Adds a rule to work item type in the process.",
        "operationId": "Add",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Rules"
        ],
        "description": "Returns a list of all rules in the work item type of the process.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workItemTypes/{witRefName}/rules/{ruleId}": {
      "delete": {
        "tags": [
          "Rules"
        ],
        "description": "Removes a rule from the work item type in the process.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Rules"
        ],
        "description": "Returns a single rule in the work item type of the process.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Rules"
        ],
        "description": "Updates a rule in the work item type of the process.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workItemTypes/{witRefName}/states": {
      "post": {
        "tags": [
          "States"
        ],
        "description": "Creates a state definition in the work item type of the process.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "States"
        ],
        "description": "Returns a list of all state definitions in a work item type of the process.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processId}/workItemTypes/{witRefName}/states/{stateId}": {
      "delete": {
        "tags": [
          "States"
        ],
        "description": "Removes a state definition in the work item type of the process.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "States"
        ],
        "description": "Returns a single state definition in a work item type of the process.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "States"
        ],
        "description": "Hides a state definition in the work item type of the process.Only states with customizationType:System can be hidden.",
        "operationId": "Hide State Definition",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "States"
        ],
        "description": "Updates a given state definition in the work item type of the process.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/work/processes/{processTypeId}": {
      "delete": {
        "tags": [
          "Processes"
        ],
        "description": "Removes a process of a specific ID.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Processes"
        ],
        "description": "Returns a single process of a specified ID.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Processes"
        ],
        "description": "Updates a process of a specific ID.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
    },
    "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks.",
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}