{
  "swagger": "2.0",
  "info": {
    "title": "TaskAgent",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.0"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "agents"
    },
    {
      "name": "azurermsubscriptions"
    },
    {
      "name": "deploymentgroupaccesstoken"
    },
    {
      "name": "deploymentgroups"
    },
    {
      "name": "deploymentmachinejobrequests"
    },
    {
      "name": "deploymentmachinemessages"
    },
    {
      "name": "endpoint"
    },
    {
      "name": "hublicense"
    },
    {
      "name": "icon"
    },
    {
      "name": "inputvalidation"
    },
    {
      "name": "jobrequests"
    },
    {
      "name": "machinegroupaccesstoken"
    },
    {
      "name": "machinegroups"
    },
    {
      "name": "machines"
    },
    {
      "name": "maintenancedefinitions"
    },
    {
      "name": "maintenancejobs"
    },
    {
      "name": "messages"
    },
    {
      "name": "packages"
    },
    {
      "name": "poolroles"
    },
    {
      "name": "pools"
    },
    {
      "name": "queueroles"
    },
    {
      "name": "queues"
    },
    {
      "name": "revisions"
    },
    {
      "name": "securefiles"
    },
    {
      "name": "serviceendpointproxy"
    },
    {
      "name": "serviceendpoints"
    },
    {
      "name": "serviceendpointtypes"
    },
    {
      "name": "sessions"
    },
    {
      "name": "taskgroups"
    },
    {
      "name": "tasks"
    },
    {
      "name": "updates"
    },
    {
      "name": "usercapabilities"
    },
    {
      "name": "variablegroups"
    },
    {
      "name": "vstsaadoauth"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/distributedtask/endpoint": {
      "post": {
        "tags": [
          "endpoint"
        ],
        "summary": "QueryEndpoint",
        "description": "Proxy for a GET request defined by an 'endpoint'. The request is authorized using a service connection. The response is filtered using an XPath/Json based selector.",
        "operationId": "QueryEndpoint"
      }
    },
    "/_apis/distributedtask/hublicense/{hubName}": {
      "get": {
        "tags": [
          "hublicense"
        ],
        "summary": "GetTaskHubLicenseDetails",
        "description": "",
        "operationId": "GetTaskHubLicenseDetails"
      },
      "put": {
        "tags": [
          "hublicense"
        ],
        "summary": "UpdateTaskHubLicenseDetails",
        "description": "",
        "operationId": "UpdateTaskHubLicenseDetails"
      }
    },
    "/_apis/distributedtask/inputvalidation": {
      "post": {
        "tags": [
          "inputvalidation"
        ],
        "summary": "ValidateInputs",
        "description": "",
        "operationId": "ValidateInputs"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackages",
        "description": "",
        "operationId": "GetPackages"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}/{version}": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackage",
        "description": "",
        "operationId": "GetPackage"
      }
    },
    "/_apis/distributedtask/poolroles/{poolId}": {
      "get": {
        "tags": [
          "poolroles"
        ],
        "summary": "GetAgentPoolRoles",
        "description": "",
        "operationId": "GetAgentPoolRoles"
      }
    },
    "/_apis/distributedtask/pools": {
      "post": {
        "tags": [
          "pools"
        ],
        "summary": "AddAgentPool",
        "description": "",
        "operationId": "AddAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pools"
        ],
        "summary": "GetAgentPools",
        "description": "",
        "operationId": "GetAgentPools",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}": {
      "delete": {
        "tags": [
          "pools"
        ],
        "summary": "DeleteAgentPool",
        "description": "",
        "operationId": "DeleteAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pools"
        ],
        "summary": "GetAgentPool",
        "description": "",
        "operationId": "GetAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pools"
        ],
        "summary": "UpdateAgentPool",
        "description": "",
        "operationId": "UpdateAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents": {
      "post": {
        "tags": [
          "agents"
        ],
        "summary": "AddAgent",
        "description": "",
        "operationId": "AddAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "agents"
        ],
        "summary": "GetAgents",
        "description": "",
        "operationId": "GetAgents",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}": {
      "delete": {
        "tags": [
          "agents"
        ],
        "summary": "DeleteAgent",
        "description": "",
        "operationId": "DeleteAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "agents"
        ],
        "summary": "GetAgent",
        "description": "",
        "operationId": "GetAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "agents"
        ],
        "summary": "ReplaceAgent",
        "description": "",
        "operationId": "ReplaceAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "agents"
        ],
        "summary": "UpdateAgent",
        "description": "",
        "operationId": "UpdateAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/updates": {
      "put": {
        "tags": [
          "updates"
        ],
        "summary": "UpdateAgentUpdateState",
        "description": "",
        "operationId": "UpdateAgentUpdateState",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/usercapabilities": {
      "put": {
        "tags": [
          "usercapabilities"
        ],
        "summary": "UpdateAgentUserCapabilities",
        "description": "",
        "operationId": "UpdateAgentUserCapabilities",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests": {
      "get": {
        "tags": [
          "jobrequests"
        ],
        "summary": "GetAgentRequestsForAgent",
        "description": "",
        "operationId": "GetAgentRequestsForAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "jobrequests"
        ],
        "summary": "QueueAgentRequest",
        "description": "",
        "operationId": "QueueAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests/{requestId}": {
      "delete": {
        "tags": [
          "jobrequests"
        ],
        "summary": "DeleteAgentRequest",
        "description": "",
        "operationId": "DeleteAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "jobrequests"
        ],
        "summary": "GetAgentRequest",
        "description": "",
        "operationId": "GetAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "jobrequests"
        ],
        "summary": "UpdateAgentRequest",
        "description": "",
        "operationId": "UpdateAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions": {
      "post": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "CreateAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "CreateAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "GetAgentPoolMaintenanceDefinitions",
        "description": "",
        "operationId": "GetAgentPoolMaintenanceDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions/{definitionId}": {
      "delete": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "DeleteAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "DeleteAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "GetAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "GetAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "UpdateAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "UpdateAgentPoolMaintenanceDefinition"
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs": {
      "get": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "GetAgentPoolMaintenanceJobs",
        "description": "",
        "operationId": "GetAgentPoolMaintenanceJobs",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "QueueAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "QueueAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs/{jobId}": {
      "delete": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "DeleteAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "DeleteAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "GetAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "GetAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "UpdateAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "UpdateAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages": {
      "get": {
        "tags": [
          "messages"
        ],
        "summary": "GetMessage",
        "description": "",
        "operationId": "GetMessage",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "messages"
        ],
        "summary": "RefreshAgent",
        "description": "",
        "operationId": "RefreshAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages/{messageId}": {
      "delete": {
        "tags": [
          "messages"
        ],
        "summary": "DeleteMessage",
        "description": "",
        "operationId": "DeleteMessage",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions": {
      "post": {
        "tags": [
          "sessions"
        ],
        "summary": "CreateAgentSession",
        "description": "",
        "operationId": "CreateAgentSession",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions/{sessionId}": {
      "delete": {
        "tags": [
          "sessions"
        ],
        "summary": "DeleteAgentSession",
        "description": "",
        "operationId": "DeleteAgentSession",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/queueroles/{queueId}": {
      "get": {
        "tags": [
          "queueroles"
        ],
        "summary": "GetAgentQueueRoles",
        "description": "",
        "operationId": "GetAgentQueueRoles"
      }
    },
    "/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "queues"
        ],
        "summary": "AddAgentQueue",
        "description": "",
        "operationId": "AddAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "queues"
        ],
        "summary": "CreateTeamProject",
        "description": "",
        "operationId": "CreateTeamProject",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueues",
        "description": "",
        "operationId": "GetAgentQueues",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "queues"
        ],
        "summary": "DeleteAgentQueue",
        "description": "",
        "operationId": "DeleteAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueue",
        "description": "",
        "operationId": "GetAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/azurermsubscriptions": {
      "get": {
        "tags": [
          "azurermsubscriptions"
        ],
        "summary": "GetAzureSubscriptions",
        "description": "Returns list of azure subscriptions",
        "operationId": "GetAzureSubscriptions"
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/vstsaadoauth": {
      "post": {
        "tags": [
          "vstsaadoauth"
        ],
        "summary": "AcquireAccessToken",
        "description": "",
        "operationId": "AcquireAccessToken"
      },
      "get": {
        "tags": [
          "vstsaadoauth"
        ],
        "summary": "GetVstsAadTenantId",
        "description": "",
        "operationId": "GetVstsAadTenantId"
      }
    },
    "/_apis/distributedtask/serviceendpointtypes": {
      "get": {
        "tags": [
          "serviceendpointtypes"
        ],
        "summary": "GetServiceEndpointTypes",
        "description": "",
        "operationId": "GetServiceEndpointTypes",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}": {
      "delete": {
        "tags": [
          "tasks"
        ],
        "summary": "DeleteTaskDefinition",
        "description": "",
        "operationId": "DeleteTaskDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTaskDefinitions",
        "description": "",
        "operationId": "GetTaskDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTaskContentZip",
        "description": "",
        "operationId": "GetTaskContentZip",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}/icon": {
      "get": {
        "tags": [
          "icon"
        ],
        "summary": "GetTaskIcon",
        "description": "",
        "operationId": "GetTaskIcon",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroupaccesstoken/{deploymentGroupId}": {
      "post": {
        "tags": [
          "deploymentgroupaccesstoken"
        ],
        "summary": "GenerateDeploymentGroupAccessToken",
        "description": "",
        "operationId": "GenerateDeploymentGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups": {
      "post": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "AddDeploymentGroup",
        "description": "",
        "operationId": "AddDeploymentGroup"
      },
      "get": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "GetDeploymentGroups",
        "description": "",
        "operationId": "GetDeploymentGroups"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}": {
      "delete": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "DeleteDeploymentGroup",
        "description": "",
        "operationId": "DeleteDeploymentGroup"
      },
      "get": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "GetDeploymentGroup",
        "description": "",
        "operationId": "GetDeploymentGroup"
      },
      "patch": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "UpdateDeploymentGroup",
        "description": "",
        "operationId": "UpdateDeploymentGroup"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinejobrequests": {
      "get": {
        "tags": [
          "deploymentmachinejobrequests"
        ],
        "summary": "GetAgentRequestsForDeploymentMachine",
        "description": "",
        "operationId": "GetAgentRequestsForDeploymentMachine"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinemessages": {
      "post": {
        "tags": [
          "deploymentmachinemessages"
        ],
        "summary": "RefreshDeploymentMachines",
        "description": "",
        "operationId": "RefreshDeploymentMachines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines": {
      "post": {
        "tags": [
          "machines"
        ],
        "summary": "AddDeploymentMachine",
        "description": "",
        "operationId": "AddDeploymentMachine"
      },
      "get": {
        "tags": [
          "machines"
        ],
        "summary": "GetDeploymentMachines",
        "description": "",
        "operationId": "GetDeploymentMachines"
      },
      "patch": {
        "tags": [
          "machines"
        ],
        "summary": "UpdateDeploymentMachines",
        "description": "",
        "operationId": "UpdateDeploymentMachines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines/{machineId}": {
      "delete": {
        "tags": [
          "machines"
        ],
        "summary": "DeleteDeploymentMachine",
        "description": "",
        "operationId": "DeleteDeploymentMachine"
      },
      "get": {
        "tags": [
          "machines"
        ],
        "summary": "GetDeploymentMachine",
        "description": "",
        "operationId": "GetDeploymentMachine"
      },
      "put": {
        "tags": [
          "machines"
        ],
        "summary": "ReplaceDeploymentMachine",
        "description": "",
        "operationId": "ReplaceDeploymentMachine"
      },
      "patch": {
        "tags": [
          "machines"
        ],
        "summary": "UpdateDeploymentMachine",
        "description": "",
        "operationId": "UpdateDeploymentMachine"
      }
    },
    "/{project}/_apis/distributedtask/machinegroupaccesstoken/{machineGroupId}": {
      "post": {
        "tags": [
          "machinegroupaccesstoken"
        ],
        "summary": "GenerateDeploymentMachineGroupAccessToken",
        "description": "",
        "operationId": "GenerateDeploymentMachineGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups": {
      "post": {
        "tags": [
          "machinegroups"
        ],
        "summary": "AddDeploymentMachineGroup",
        "description": "",
        "operationId": "AddDeploymentMachineGroup"
      },
      "get": {
        "tags": [
          "machinegroups"
        ],
        "summary": "GetDeploymentMachineGroups",
        "description": "",
        "operationId": "GetDeploymentMachineGroups"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}": {
      "delete": {
        "tags": [
          "machinegroups"
        ],
        "summary": "DeleteDeploymentMachineGroup",
        "description": "",
        "operationId": "DeleteDeploymentMachineGroup"
      },
      "get": {
        "tags": [
          "machinegroups"
        ],
        "summary": "GetDeploymentMachineGroup",
        "description": "",
        "operationId": "GetDeploymentMachineGroup"
      },
      "patch": {
        "tags": [
          "machinegroups"
        ],
        "summary": "UpdateDeploymentMachineGroup",
        "description": "",
        "operationId": "UpdateDeploymentMachineGroup"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}/machines": {
      "get": {
        "tags": [
          "machines"
        ],
        "summary": "GetDeploymentMachineGroupMachines",
        "description": "",
        "operationId": "GetDeploymentMachineGroupMachines"
      },
      "patch": {
        "tags": [
          "machines"
        ],
        "summary": "UpdateDeploymentMachineGroupMachines",
        "description": "",
        "operationId": "UpdateDeploymentMachineGroupMachines"
      }
    },
    "/{project}/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "queues"
        ],
        "summary": "AddAgentQueue",
        "description": "",
        "operationId": "AddAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "queues"
        ],
        "summary": "CreateTeamProject",
        "description": "",
        "operationId": "CreateTeamProject",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueues",
        "description": "",
        "operationId": "GetAgentQueues",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "queues"
        ],
        "summary": "DeleteAgentQueue",
        "description": "",
        "operationId": "DeleteAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueue",
        "description": "",
        "operationId": "GetAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/securefiles": {
      "get": {
        "tags": [
          "securefiles"
        ],
        "summary": "GetSecureFiles",
        "description": "Get secure files",
        "operationId": "GetSecureFiles"
      },
      "post": {
        "tags": [
          "securefiles"
        ],
        "summary": "QuerySecureFilesByProperties",
        "description": "Query secure files using a name pattern and a condition on file properties.",
        "operationId": "QuerySecureFilesByProperties"
      },
      "patch": {
        "tags": [
          "securefiles"
        ],
        "summary": "UpdateSecureFiles",
        "description": "Update properties and/or names of a set of secure files. Files are identified by their IDs. Properties provided override the existing one entirely, i.e. do not merge.",
        "operationId": "UpdateSecureFiles"
      }
    },
    "/{project}/_apis/distributedtask/securefiles/{secureFileId}": {
      "delete": {
        "tags": [
          "securefiles"
        ],
        "summary": "DeleteSecureFile",
        "description": "Delete a secure file",
        "operationId": "DeleteSecureFile"
      },
      "get": {
        "tags": [
          "securefiles"
        ],
        "summary": "DownloadSecureFile",
        "description": "Download a secure file by Id",
        "operationId": "DownloadSecureFile"
      },
      "patch": {
        "tags": [
          "securefiles"
        ],
        "summary": "UpdateSecureFile",
        "description": "Update the name or properties of an existing secure file",
        "operationId": "UpdateSecureFile"
      }
    },
    "/{project}/_apis/distributedtask/serviceendpointproxy": {
      "post": {
        "tags": [
          "serviceendpointproxy"
        ],
        "summary": "ExecuteServiceEndpointRequest",
        "description": "",
        "operationId": "ExecuteServiceEndpointRequest",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_query"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints": {
      "post": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "CreateServiceEndpoint",
        "description": "",
        "operationId": "CreateServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "GetServiceEndpoints",
        "description": "",
        "operationId": "GetServiceEndpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "UpdateServiceEndpoints",
        "description": "",
        "operationId": "UpdateServiceEndpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}": {
      "delete": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "DeleteServiceEndpoint",
        "description": "",
        "operationId": "DeleteServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "GetServiceEndpointDetails",
        "description": "",
        "operationId": "GetServiceEndpointDetails",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "UpdateServiceEndpoint",
        "description": "",
        "operationId": "UpdateServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups": {
      "post": {
        "tags": [
          "taskgroups"
        ],
        "summary": "AddTaskGroup",
        "description": "",
        "operationId": "AddTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_add"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "taskgroups"
        ],
        "summary": "PublishTaskGroup",
        "description": "",
        "operationId": "PublishTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}": {
      "delete": {
        "tags": [
          "taskgroups"
        ],
        "summary": "DeleteTaskGroup",
        "description": "",
        "operationId": "DeleteTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "taskgroups"
        ],
        "summary": "GetTaskGroup",
        "description": "",
        "operationId": "GetTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "taskgroups"
        ],
        "summary": "PublishPreviewTaskGroup",
        "description": "",
        "operationId": "PublishPreviewTaskGroup"
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}/revisions": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetTaskGroupHistory",
        "description": "",
        "operationId": "GetTaskGroupHistory",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/variablegroups": {
      "post": {
        "tags": [
          "variablegroups"
        ],
        "summary": "AddVariableGroup",
        "description": "",
        "operationId": "AddVariableGroup"
      },
      "get": {
        "tags": [
          "variablegroups"
        ],
        "summary": "GetVariableGroups",
        "description": "",
        "operationId": "GetVariableGroups"
      }
    },
    "/{project}/_apis/distributedtask/variablegroups/{groupId}": {
      "delete": {
        "tags": [
          "variablegroups"
        ],
        "summary": "DeleteVariableGroup",
        "description": "",
        "operationId": "DeleteVariableGroup"
      },
      "get": {
        "tags": [
          "variablegroups"
        ],
        "summary": "GetVariableGroup",
        "description": "",
        "operationId": "GetVariableGroup"
      },
      "put": {
        "tags": [
          "variablegroups"
        ],
        "summary": "UpdateVariableGroup",
        "description": "",
        "operationId": "UpdateVariableGroup"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.agentpools": "Grants the ability to view tasks, pools, queues, agents, and currently running or recently completed jobs for agents",
        "vso.agentpools_manage": "Grants the ability to manage pools, queues, and agents",
        "vso.serviceendpoint_manage": "Grants the ability to read, query and manage service endpoints.",
        "vso.serviceendpoint": "Grants the ability to read service endpoints.",
        "vso.serviceendpoint_query": "Grants the ability to read and query service endpoints.",
        "vso.taskgroups": "Grants the ability to read task groups",
        "vso.taskgroups_manage": "Grants the ability to read, create and manage taskgroups.",
        "vso.taskgroups_add": "Grants the ability to read and create task groups"
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}