{
  "swagger": "2.0",
  "info": {
    "title": "Git",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "annotatedTags"
    },
    {
      "name": "Blobs"
    },
    {
      "name": "BranchStats"
    },
    {
      "name": "Changes"
    },
    {
      "name": "CherryPicks"
    },
    {
      "name": "CommitDiffs"
    },
    {
      "name": "Commits"
    },
    {
      "name": "CommitsBatch"
    },
    {
      "name": "DeletedRepositories"
    },
    {
      "name": "forks"
    },
    {
      "name": "forkSyncRequests"
    },
    {
      "name": "ImportRequests"
    },
    {
      "name": "Items"
    },
    {
      "name": "ItemsBatch"
    },
    {
      "name": "PullRequestAttachments"
    },
    {
      "name": "PullRequestCommentLikes"
    },
    {
      "name": "PullRequestCommits"
    },
    {
      "name": "PullRequestConflicts"
    },
    {
      "name": "PullRequestIterationChanges"
    },
    {
      "name": "PullRequestIterations"
    },
    {
      "name": "PullRequestIterationStatuses"
    },
    {
      "name": "PullRequestLabels"
    },
    {
      "name": "PullRequestQuery"
    },
    {
      "name": "PullRequestReviewers"
    },
    {
      "name": "PullRequests"
    },
    {
      "name": "PullRequestShare"
    },
    {
      "name": "PullRequestStatuses"
    },
    {
      "name": "PullRequestThreadComments"
    },
    {
      "name": "PullRequestThreads"
    },
    {
      "name": "PullRequestWorkItems"
    },
    {
      "name": "pushes"
    },
    {
      "name": "refs"
    },
    {
      "name": "refsFavorites"
    },
    {
      "name": "Repositories"
    },
    {
      "name": "Reverts"
    },
    {
      "name": "Statuses"
    },
    {
      "name": "Suggestions"
    },
    {
      "name": "Trees"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/git/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Get a pull request using its ID",
        "operationId": "PullRequests_GetPullRequestById"
      }
    },
    "/_apis/git/repositories": {
      "post": {
        "tags": [
          "Repositories"
        ],
        "description": "Create a git repository",
        "operationId": "Repositories_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Retrieve git repositories.",
        "operationId": "Repositories_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "Repositories"
        ],
        "description": "Delete a git repository",
        "operationId": "Repositories_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "",
        "operationId": "Repositories_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Repositories"
        ],
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "Repositories_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "Blobs"
        ],
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "Blobs_GetBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "Blobs"
        ],
        "description": "Gets a single blob.",
        "operationId": "Blobs_GetBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Retrieve git commits for a project",
        "operationId": "Commits_GetCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Retrieve a particular commit.",
        "operationId": "Commits_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "Changes"
        ],
        "description": "Retrieve changes for a particular commit.",
        "operationId": "Changes_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "Statuses"
        ],
        "description": "",
        "operationId": "Statuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Statuses"
        ],
        "description": "",
        "operationId": "Statuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "CommitsBatch"
        ],
        "description": "Retrieve git commits for a project",
        "operationId": "CommitsBatch_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "CommitDiffs"
        ],
        "description": "Get differences in committed items between two commits.",
        "operationId": "CommitDiffs_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "Items"
        ],
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "Items_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "Items"
        ],
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "Items_GetItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "ItemsBatch"
        ],
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "ItemsBatch_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "PullRequestQuery"
        ],
        "description": "Query for pull requests",
        "operationId": "PullRequestQuery_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "PullRequests"
        ],
        "description": "Create a git pull request",
        "operationId": "PullRequests_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Query for pull requests",
        "operationId": "PullRequests_GetPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Retrieve a pull request",
        "operationId": "PullRequests_GetPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequests"
        ],
        "description": "Updates a pull request",
        "operationId": "PullRequests_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "Create a new attachment",
        "operationId": "PullRequestAttachments_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_GetAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "PullRequestCommits"
        ],
        "description": "Retrieve pull request's commits",
        "operationId": "PullRequestCommits_GetPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "PullRequestConflicts_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "PullRequestConflicts_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Update merge conflict resolution",
        "operationId": "PullRequestConflicts_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "PullRequestIterations"
        ],
        "description": "",
        "operationId": "PullRequestIterations_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "PullRequestIterations"
        ],
        "description": "",
        "operationId": "PullRequestIterations_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "PullRequestIterationChanges"
        ],
        "description": "",
        "operationId": "PullRequestIterationChanges_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "PullRequestCommits"
        ],
        "description": "Get the commits for an iteration.",
        "operationId": "PullRequestCommits_GetPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Create a pull request status on the iteration. This method will have the same result as CreatePullRequestStatus with specified iterationId in the request body.",
        "operationId": "PullRequestIterationStatuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "PullRequestIterationStatuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Get the specific pull request iteration status by ID. The status ID is unique within the pull request across all iterations.",
        "operationId": "PullRequestIterationStatuses_Get",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/labels": {
      "post": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "Retrieve a pull request's Labels",
        "operationId": "PullRequestLabels_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/labels/{labelIdOrName}": {
      "delete": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Adds reviewers to a git pull request",
        "operationId": "PullRequestReviewers_CreatePullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Retrieve a pull request reviewers",
        "operationId": "PullRequestReviewers_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Resets multiple reviewer votes in a batch",
        "operationId": "PullRequestReviewers_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Adds a reviewer to a git pull request",
        "operationId": "PullRequestReviewers_CreatePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Removes a reviewer from a git pull request",
        "operationId": "PullRequestReviewers_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "PullRequestReviewers_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "PullRequestShare"
        ],
        "description": "",
        "operationId": "PullRequestShare_SharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Create a pull request status.",
        "operationId": "PullRequestStatuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "PullRequestStatuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Get the specific pull request status by ID. The status ID is unique within the pull request across all iterations.",
        "operationId": "PullRequestStatuses_Get",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Create a pull request review comment thread",
        "operationId": "PullRequestThreads_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Get all pull request comment threads.",
        "operationId": "PullRequestThreads_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "PullRequestThreads_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Update a pull request review comment thread",
        "operationId": "PullRequestThreads_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Create a pull request review comment",
        "operationId": "PullRequestThreadComments_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Get all pull request comments in a thread.",
        "operationId": "PullRequestThreadComments_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "PullRequestThreadComments_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "PullRequestThreadComments_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Update a pull request review comment thread",
        "operationId": "PullRequestThreadComments_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}/likes": {
      "post": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Add a like on a comment.",
        "operationId": "PullRequestCommentLikes_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Delete a like on a comment.",
        "operationId": "PullRequestCommentLikes_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Get likes for a comment.",
        "operationId": "PullRequestCommentLikes_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "PullRequestWorkItems"
        ],
        "description": "Retrieve a pull request work items",
        "operationId": "PullRequestWorkItems_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "Pushes"
        ],
        "description": "Push changes to the repository.",
        "operationId": "Pushes_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Pushes"
        ],
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "Pushes_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "Pushes"
        ],
        "description": "Retrieve a particular push.",
        "operationId": "Pushes_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "Refs"
        ],
        "description": "Creates or updates refs with the given information",
        "operationId": "Refs_UpdateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "Refs_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "Refs"
        ],
        "description": "",
        "operationId": "Refs_UpdateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "BranchStats"
        ],
        "description": "Retrieve statistics about a single branch.",
        "operationId": "BranchStats_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "BranchStats"
        ],
        "description": "Retrieve statistics for multiple commits",
        "operationId": "BranchStats_GetBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "Suggestions"
        ],
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "Suggestions_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "Trees"
        ],
        "description": "",
        "operationId": "Trees_GetTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryNameOrId}/forks/{collectionId}": {
      "get": {
        "tags": [
          "Forks"
        ],
        "description": "Query the child forks of a repository in a particular collection.",
        "operationId": "Forks_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryNameOrId}/forkSyncRequests": {
      "post": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Request that another repository's refs be fetched into this one.",
        "operationId": "ForkSyncRequests_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Query all requested fork sync operations on this repository.",
        "operationId": "ForkSyncRequests_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryNameOrId}/forkSyncRequests/{forkSyncOperationId}": {
      "get": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Get a specific fork sync operation's details.",
        "operationId": "ForkSyncRequests_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/deletedrepositories": {
      "get": {
        "tags": [
          "DeletedRepositories"
        ],
        "description": "Retrieve deleted git repositories.",
        "operationId": "DeletedRepositories_List"
      }
    },
    "/{project}/_apis/git/favorites/refs": {
      "post": {
        "tags": [
          "RefsFavorites"
        ],
        "description": "Creates a ref favorite",
        "operationId": "RefsFavorites_Create",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "RefsFavorites"
        ],
        "description": "Gets the refs favorites for a repo and an identity.",
        "operationId": "RefsFavorites_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/favorites/refs/{favoriteId}": {
      "delete": {
        "tags": [
          "RefsFavorites"
        ],
        "description": "",
        "operationId": "RefsFavorites_Delete"
      },
      "get": {
        "tags": [
          "RefsFavorites"
        ],
        "description": "",
        "operationId": "RefsFavorites_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/pullrequests": {
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Query pull requests by project",
        "operationId": "PullRequests_GetPullRequestsByProject",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories": {
      "post": {
        "tags": [
          "Repositories"
        ],
        "description": "Create a git repository",
        "operationId": "Repositories_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "Retrieve git repositories.",
        "operationId": "Repositories_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "Repositories"
        ],
        "description": "Delete a git repository",
        "operationId": "Repositories_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Repositories"
        ],
        "description": "",
        "operationId": "Repositories_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Repositories"
        ],
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "Repositories_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags": {
      "post": {
        "tags": [
          "AnnotatedTags"
        ],
        "description": "Create an annotated tag",
        "operationId": "AnnotatedTags_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags/{objectId}": {
      "get": {
        "tags": [
          "AnnotatedTags"
        ],
        "description": "Get an annotated tag",
        "operationId": "AnnotatedTags_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "Blobs"
        ],
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "Blobs_GetBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "Blobs"
        ],
        "description": "Gets a single blob.",
        "operationId": "Blobs_GetBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks": {
      "post": {
        "tags": [
          "CherryPicks"
        ],
        "description": "",
        "operationId": "CherryPicks_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "CherryPicks"
        ],
        "description": "",
        "operationId": "CherryPicks_GetCherryPickForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks/{cherryPickId}": {
      "get": {
        "tags": [
          "CherryPicks"
        ],
        "description": "",
        "operationId": "CherryPicks_GetCherryPick",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Retrieve git commits for a project",
        "operationId": "Commits_GetCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "Commits"
        ],
        "description": "Retrieve a particular commit.",
        "operationId": "Commits_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "Changes"
        ],
        "description": "Retrieve changes for a particular commit.",
        "operationId": "Changes_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "Statuses"
        ],
        "description": "",
        "operationId": "Statuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Statuses"
        ],
        "description": "",
        "operationId": "Statuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "CommitsBatch"
        ],
        "description": "Retrieve git commits for a project",
        "operationId": "CommitsBatch_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "CommitDiffs"
        ],
        "description": "Get differences in committed items between two commits.",
        "operationId": "CommitDiffs_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests": {
      "post": {
        "tags": [
          "ImportRequests"
        ],
        "description": "Create an import request",
        "operationId": "ImportRequests_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ImportRequests"
        ],
        "description": "Retrieve import requests for a repository",
        "operationId": "ImportRequests_Query",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests/{importRequestId}": {
      "get": {
        "tags": [
          "ImportRequests"
        ],
        "description": "Retrieve a particular import request",
        "operationId": "ImportRequests_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ImportRequests"
        ],
        "description": "Update an import request",
        "operationId": "ImportRequests_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "Items"
        ],
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "Items_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "Items"
        ],
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "Items_GetItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "ItemsBatch"
        ],
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "ItemsBatch_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "PullRequestQuery"
        ],
        "description": "Query for pull requests",
        "operationId": "PullRequestQuery_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "PullRequests"
        ],
        "description": "Create a git pull request",
        "operationId": "PullRequests_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Query for pull requests",
        "operationId": "PullRequests_GetPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "PullRequests"
        ],
        "description": "Retrieve a pull request",
        "operationId": "PullRequests_GetPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequests"
        ],
        "description": "Updates a pull request",
        "operationId": "PullRequests_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "Create a new attachment",
        "operationId": "PullRequestAttachments_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestAttachments"
        ],
        "description": "",
        "operationId": "PullRequestAttachments_GetAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "PullRequestCommits"
        ],
        "description": "Retrieve pull request's commits",
        "operationId": "PullRequestCommits_GetPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "PullRequestConflicts_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "PullRequestConflicts_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestConflicts"
        ],
        "description": "Update merge conflict resolution",
        "operationId": "PullRequestConflicts_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "PullRequestIterations"
        ],
        "description": "",
        "operationId": "PullRequestIterations_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "PullRequestIterations"
        ],
        "description": "",
        "operationId": "PullRequestIterations_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "PullRequestIterationChanges"
        ],
        "description": "",
        "operationId": "PullRequestIterationChanges_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "PullRequestCommits"
        ],
        "description": "Get the commits for an iteration.",
        "operationId": "PullRequestCommits_GetPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Create a pull request status on the iteration. This method will have the same result as CreatePullRequestStatus with specified iterationId in the request body.",
        "operationId": "PullRequestIterationStatuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "PullRequestIterationStatuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "PullRequestIterationStatuses"
        ],
        "description": "Get the specific pull request iteration status by ID. The status ID is unique within the pull request across all iterations.",
        "operationId": "PullRequestIterationStatuses_Get",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/labels": {
      "post": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "Retrieve a pull request's Labels",
        "operationId": "PullRequestLabels_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/labels/{labelIdOrName}": {
      "delete": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestLabels"
        ],
        "description": "",
        "operationId": "PullRequestLabels_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Adds reviewers to a git pull request",
        "operationId": "PullRequestReviewers_CreatePullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Retrieve a pull request reviewers",
        "operationId": "PullRequestReviewers_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Resets multiple reviewer votes in a batch",
        "operationId": "PullRequestReviewers_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Adds a reviewer to a git pull request",
        "operationId": "PullRequestReviewers_CreatePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Removes a reviewer from a git pull request",
        "operationId": "PullRequestReviewers_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestReviewers"
        ],
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "PullRequestReviewers_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "PullRequestShare"
        ],
        "description": "",
        "operationId": "PullRequestShare_SharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Create a pull request status.",
        "operationId": "PullRequestStatuses_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "PullRequestStatuses_List",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "PullRequestStatuses"
        ],
        "description": "Get the specific pull request status by ID. The status ID is unique within the pull request across all iterations.",
        "operationId": "PullRequestStatuses_Get",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Create a pull request review comment thread",
        "operationId": "PullRequestThreads_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Get all pull request comment threads.",
        "operationId": "PullRequestThreads_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "PullRequestThreads_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestThreads"
        ],
        "description": "Update a pull request review comment thread",
        "operationId": "PullRequestThreads_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Create a pull request review comment",
        "operationId": "PullRequestThreadComments_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Get all pull request comments in a thread.",
        "operationId": "PullRequestThreadComments_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "PullRequestThreadComments_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "PullRequestThreadComments_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "PullRequestThreadComments"
        ],
        "description": "Update a pull request review comment thread",
        "operationId": "PullRequestThreadComments_Update",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}/likes": {
      "post": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Add a like on a comment.",
        "operationId": "PullRequestCommentLikes_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Delete a like on a comment.",
        "operationId": "PullRequestCommentLikes_Delete",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "PullRequestCommentLikes"
        ],
        "description": "Get likes for a comment.",
        "operationId": "PullRequestCommentLikes_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "PullRequestWorkItems"
        ],
        "description": "Retrieve a pull request work items",
        "operationId": "PullRequestWorkItems_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "Pushes"
        ],
        "description": "Push changes to the repository.",
        "operationId": "Pushes_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Pushes"
        ],
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "Pushes_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "Pushes"
        ],
        "description": "Retrieve a particular push.",
        "operationId": "Pushes_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "Refs"
        ],
        "description": "Creates or updates refs with the given information",
        "operationId": "Refs_UpdateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "Refs"
        ],
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "Refs_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "Refs"
        ],
        "description": "",
        "operationId": "Refs_UpdateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts": {
      "post": {
        "tags": [
          "Reverts"
        ],
        "description": "",
        "operationId": "Reverts_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Reverts"
        ],
        "description": "",
        "operationId": "Reverts_GetRevertForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts/{revertId}": {
      "get": {
        "tags": [
          "Reverts"
        ],
        "description": "",
        "operationId": "Reverts_GetRevert",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "BranchStats"
        ],
        "description": "Retrieve statistics about a single branch.",
        "operationId": "BranchStats_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "BranchStats"
        ],
        "description": "Retrieve statistics for multiple commits",
        "operationId": "BranchStats_GetBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "Suggestions"
        ],
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "Suggestions_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "Trees"
        ],
        "description": "",
        "operationId": "Trees_GetTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryNameOrId}/forks/{collectionId}": {
      "get": {
        "tags": [
          "Forks"
        ],
        "description": "Query the child forks of a repository in a particular collection.",
        "operationId": "Forks_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryNameOrId}/forkSyncRequests": {
      "post": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Request that another repository's refs be fetched into this one.",
        "operationId": "ForkSyncRequests_Create",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Query all requested fork sync operations on this repository.",
        "operationId": "ForkSyncRequests_List",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryNameOrId}/forkSyncRequests/{forkSyncOperationId}": {
      "get": {
        "tags": [
          "ForkSyncRequests"
        ],
        "description": "Get a specific fork sync operation's details.",
        "operationId": "ForkSyncRequests_Get",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    }
  },
  "definitions": {
    "AssociatedWorkItem": {
      "description": "",
      "type": "object",
      "properties": {
        "assignedTo": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "state": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "description": "REST url",
          "type": "string"
        },
        "webUrl": {
          "type": "string"
        },
        "workItemType": {
          "type": "string"
        }
      }
    },
    "AsyncGitOperationNotification": {
      "description": "",
      "type": "object",
      "properties": {
        "operationId": {
          "readOnly": true,
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "AsyncRefOperationCommitLevelEventNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
        "commitId": {
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "AsyncRefOperationCompletedNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
        "newRefName": {
          "type": "string"
        }
      }
    },
    "AsyncRefOperationConflictNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncRefOperationCommitLevelEventNotification"
        }
      ],
      "properties": {
      }
    },
    "AsyncRefOperationGeneralFailureNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
      }
    },
    "AsyncRefOperationProgressNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncRefOperationCommitLevelEventNotification"
        }
      ],
      "properties": {
        "progress": {
          "readOnly": true,
          "type": "number",
          "format": "double"
        }
      }
    },
    "AsyncRefOperationTimeoutNotification": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
      }
    },
    "Attachment": {
      "description": "Meta data for a file attached to an artifact",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "description": "The person that uploaded this attachment",
          "$ref": "#/definitions/IdentityRef"
        },
        "contentHash": {
          "description": "Content hash of on-disk representation of file content. Its calculated by the server by using SHA1 hash function.",
          "type": "string"
        },
        "createdDate": {
          "description": "The time the attachment was uploaded",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "The description of the attachment, can be null.",
          "type": "string"
        },
        "displayName": {
          "description": "The display name of the attachment, can't be null or empty.",
          "type": "string"
        },
        "id": {
          "description": "Id of the code review attachment",
          "type": "integer",
          "format": "int32"
        },
        "properties": {
          "$ref": "#/definitions/PropertiesCollection"
        },
        "url": {
          "description": "The url to download the content of the attachment",
          "type": "string"
        }
      }
    },
    "Change": {
      "description": "",
      "type": "object",
      "properties": {
        "changeType": {
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "item": {
          "type": "string",
          "format": "T"
        },
        "newContent": {
          "$ref": "#/definitions/ItemContent"
        },
        "sourceServerItem": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "ChangeCountDictionary": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        }
      ],
      "properties": {
      }
    },
    "ChangeList": {
      "description": "",
      "type": "object",
      "properties": {
        "allChangesIncluded": {
          "type": "boolean"
        },
        "changeCounts": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "changes": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "Change"
          }
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "creationDate": {
          "type": "string",
          "format": "date-time"
        },
        "notes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "owner": {
          "type": "string"
        },
        "ownerDisplayName": {
          "type": "string"
        },
        "ownerId": {
          "type": "string",
          "format": "uuid"
        },
        "sortDate": {
          "type": "string",
          "format": "date-time"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ChangeListSearchCriteria": {
      "description": "Criteria used in a search for change lists",
      "type": "object",
      "properties": {
        "compareVersion": {
          "description": "If provided, a version descriptor to compare against base",
          "type": "string"
        },
        "excludeDeletes": {
          "description": "If true, don't include delete history entries",
          "type": "boolean"
        },
        "followRenames": {
          "description": "Whether or not to follow renames for the given item being queried",
          "type": "boolean"
        },
        "fromDate": {
          "description": "If provided, only include history entries created after this date (string)",
          "type": "string"
        },
        "fromVersion": {
          "description": "If provided, a version descriptor for the earliest change list to include",
          "type": "string"
        },
        "itemPath": {
          "description": "Path of item to search under. If the itemPaths memebr is used then it will take precedence over this.",
          "type": "string"
        },
        "itemPaths": {
          "description": "List of item paths to search under. If this member is used then itemPath will be ignored.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "itemVersion": {
          "description": "Version of the items to search",
          "type": "string"
        },
        "skip": {
          "description": "Number of results to skip (used when clicking more...)",
          "type": "integer",
          "format": "int32"
        },
        "toDate": {
          "description": "If provided, only include history entries created before this date (string)",
          "type": "string"
        },
        "top": {
          "description": "If provided, the maximum number of history entries to return",
          "type": "integer",
          "format": "int32"
        },
        "toVersion": {
          "description": "If provided, a version descriptor for the latest change list to include",
          "type": "string"
        },
        "user": {
          "description": "Alias or display name of user who made the changes",
          "type": "string"
        }
      }
    },
    "CheckinNote": {
      "description": "",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "Comment": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "description": "The author of the pull request comment.",
          "$ref": "#/definitions/IdentityRef"
        },
        "commentType": {
          "description": "Determines what kind of comment when it was created.",
          "enum": [
            "unknown",
            "text",
            "codeChange",
            "system"
          ]
        },
        "content": {
          "description": "The comment's content.",
          "type": "string"
        },
        "id": {
          "description": "The pull request comment id. It always starts from 1.",
          "type": "integer",
          "format": "int16"
        },
        "isDeleted": {
          "description": "Marks if this comment was soft-deleted.",
          "type": "boolean"
        },
        "lastContentUpdatedDate": {
          "description": "The date a comment content was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "lastUpdatedDate": {
          "description": "The date a comment was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "parentCommentId": {
          "description": "The pull request comment id of the parent comment. This is used for replies",
          "type": "integer",
          "format": "int16"
        },
        "publishedDate": {
          "description": "The date a comment was first published.",
          "type": "string",
          "format": "date-time"
        },
        "usersLiked": {
          "description": "A list of the users who've liked this comment.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRef"
          }
        }
      }
    },
    "CommentIterationContext": {
      "description": "Iteration context is used to specify comparing iteration Ids when a comment thread is added while comparing 2 iterations.",
      "type": "object",
      "properties": {
        "firstComparingIteration": {
          "description": "First comparing iteration Id. Minimum value is 1.",
          "type": "integer",
          "format": "int16"
        },
        "secondComparingIteration": {
          "description": "Second comparing iteration Id. Minimum value is 1.",
          "type": "integer",
          "format": "int16"
        }
      }
    },
    "CommentPosition": {
      "description": "",
      "type": "object",
      "properties": {
        "line": {
          "description": "Position line starting with one.",
          "type": "integer",
          "format": "int32"
        },
        "offset": {
          "description": "Position offset starting with zero.",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "CommentThread": {
      "description": "Represents a given comment thread",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "comments": {
          "description": "A list of the comments.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Comment"
          }
        },
        "id": {
          "description": "The comment thread id.",
          "type": "integer",
          "format": "int32"
        },
        "isDeleted": {
          "description": "Specify if the thread is deleted which happens when all comments are deleted",
          "type": "boolean"
        },
        "lastUpdatedDate": {
          "description": "The time this thread was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "properties": {
          "description": "A list of (optional) thread properties.",
          "$ref": "#/definitions/PropertiesCollection"
        },
        "publishedDate": {
          "description": "The time this thread was published.",
          "type": "string",
          "format": "date-time"
        },
        "status": {
          "description": "The status of the comment thread.",
          "enum": [
            "unknown",
            "active",
            "fixed",
            "wontFix",
            "closed",
            "byDesign",
            "pending"
          ]
        },
        "threadContext": {
          "description": "Specify thread context such as position in left/right file.",
          "$ref": "#/definitions/CommentThreadContext"
        }
      }
    },
    "CommentThreadContext": {
      "description": "",
      "type": "object",
      "properties": {
        "filePath": {
          "description": "File path relative to the root of the repository. It's up to the client to use any path format.",
          "type": "string"
        },
        "leftFileEnd": {
          "description": "Position of last character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "leftFileStart": {
          "description": "Position of first character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "rightFileEnd": {
          "description": "Position of last character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "rightFileStart": {
          "description": "Position of first character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        }
      }
    },
    "CommentTrackingCriteria": {
      "description": "Criteria to decide if and how a thread should be tracked",
      "type": "object",
      "properties": {
        "firstComparingIteration": {
          "description": "The first comparing iteration being viewed. Threads will be tracked if this is greater than 0.",
          "type": "integer",
          "format": "int32"
        },
        "origLeftFileEnd": {
          "description": "Original position of last character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "origLeftFileStart": {
          "description": "Original position of first character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "origRightFileEnd": {
          "description": "Original position of last character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "origRightFileStart": {
          "description": "Original position of first character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "secondComparingIteration": {
          "description": "The second comparing iteration being viewed. Threads will be tracked if this is greater than 0.",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "FileContentMetadata": {
      "description": "",
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string"
        },
        "encoding": {
          "type": "integer",
          "format": "int32"
        },
        "extension": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "isBinary": {
          "type": "boolean"
        },
        "isImage": {
          "type": "boolean"
        },
        "vsLink": {
          "type": "string"
        }
      }
    },
    "GitAnnotatedTag": {
      "description": "",
      "type": "object",
      "properties": {
        "message": {
          "description": "Tagging Message",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "objectId": {
          "type": "string"
        },
        "taggedBy": {
          "description": "User name, Email and date of tagging",
          "$ref": "#/definitions/GitUserDate"
        },
        "taggedObject": {
          "description": "Tagged git object",
          "$ref": "#/definitions/GitObject"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitAsyncRefOperation": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "detailedStatus": {
          "$ref": "#/definitions/GitAsyncRefOperationDetail"
        },
        "status": {
          "enum": [
            "queued",
            "inProgress",
            "completed",
            "failed",
            "abandoned"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitAsyncRefOperationDetail": {
      "description": "",
      "type": "object",
      "properties": {
        "conflict": {
          "type": "boolean"
        },
        "currentCommitId": {
          "type": "string"
        },
        "failureMessage": {
          "type": "string"
        },
        "progress": {
          "type": "number",
          "format": "double"
        },
        "status": {
          "enum": [
            "none",
            "invalidRefName",
            "refNameConflict",
            "createBranchPermissionRequired",
            "writePermissionRequired",
            "targetBranchDeleted",
            "gitObjectTooLarge",
            "operationIndentityNotFound",
            "asyncOperationNotFound",
            "other"
          ]
        },
        "timedout": {
          "type": "boolean"
        }
      }
    },
    "GitAsyncRefOperationParameters": {
      "description": "",
      "type": "object",
      "properties": {
        "generatedRefName": {
          "type": "string"
        },
        "ontoRefName": {
          "type": "string"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "source": {
          "$ref": "#/definitions/GitAsyncRefOperationSource"
        }
      }
    },
    "GitAsyncRefOperationSource": {
      "description": "",
      "type": "object",
      "properties": {
        "commitList": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitBaseVersionDescriptor": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitVersionDescriptor"
        }
      ],
      "properties": {
        "baseVersion": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "baseVersionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "baseVersionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitBlobRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "size": {
          "description": "Size of blob content (in bytes)",
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitBranchStats": {
      "description": "",
      "type": "object",
      "properties": {
        "aheadCount": {
          "type": "integer",
          "format": "int32"
        },
        "behindCount": {
          "type": "integer",
          "format": "int32"
        },
        "commit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "isBaseVersion": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitChange": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "Change"
        }
      ],
      "properties": {
        "changeId": {
          "description": "Id of the change within the group.  For example, within the iteration",
          "type": "integer",
          "format": "int32"
        },
        "newContentTemplate": {
          "description": "New Content template to be used",
          "$ref": "#/definitions/GitTemplate"
        },
        "originalPath": {
          "description": "Original path of item if different from current path",
          "type": "string"
        }
      }
    },
    "GitCherryPick": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitAsyncRefOperation"
        }
      ],
      "properties": {
        "cherryPickId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitCommit": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitCommitRef"
        }
      ],
      "properties": {
        "push": {
          "$ref": "#/definitions/GitPushRef"
        },
        "treeId": {
          "type": "string"
        }
      }
    },
    "GitCommitChanges": {
      "description": "",
      "type": "object",
      "properties": {
        "changeCounts": {
          "$ref": "#/definitions/ChangeCountDictionary"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        }
      }
    },
    "GitCommitDiffs": {
      "description": "",
      "type": "object",
      "properties": {
        "aheadCount": {
          "type": "integer",
          "format": "int32"
        },
        "allChangesIncluded": {
          "type": "boolean"
        },
        "baseCommit": {
          "type": "string"
        },
        "behindCount": {
          "type": "integer",
          "format": "int32"
        },
        "changeCounts": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        },
        "commonCommit": {
          "type": "string"
        },
        "targetCommit": {
          "type": "string"
        }
      }
    },
    "GitCommitRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/GitUserDate"
        },
        "changeCounts": {
          "$ref": "#/definitions/ChangeCountDictionary"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "commitId": {
          "type": "string"
        },
        "committer": {
          "$ref": "#/definitions/GitUserDate"
        },
        "parents": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "remoteUrl": {
          "type": "string"
        },
        "statuses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitStatus"
          }
        },
        "url": {
          "type": "string"
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRef"
          }
        }
      }
    },
    "GitCommitToCreate": {
      "description": "",
      "type": "object",
      "properties": {
        "baseRef": {
          "$ref": "#/definitions/GitRef"
        },
        "comment": {
          "type": "string"
        },
        "pathActions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPathAction"
          }
        }
      }
    },
    "GitConflict": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "conflictId": {
          "type": "integer",
          "format": "int32"
        },
        "conflictPath": {
          "type": "string"
        },
        "conflictType": {
          "enum": [
            "none",
            "addAdd",
            "addRename",
            "deleteEdit",
            "deleteRename",
            "directoryFile",
            "directoryChild",
            "editDelete",
            "editEdit",
            "fileDirectory",
            "rename1to2",
            "rename2to1",
            "renameAdd",
            "renameDelete",
            "renameRename"
          ]
        },
        "mergeBaseCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeOrigin": {
          "$ref": "#/definitions/GitMergeOriginRef"
        },
        "mergeSourceCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeTargetCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "resolutionError": {
          "enum": [
            "none",
            "mergeContentNotFound",
            "pathInUse",
            "invalidPath",
            "unknownAction",
            "unknownMergeType",
            "otherError"
          ]
        },
        "resolutionStatus": {
          "enum": [
            "unresolved",
            "partiallyResolved",
            "resolved"
          ]
        },
        "resolvedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "resolvedDate": {
          "type": "string",
          "format": "date-time"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitConflictAddAdd": {
      "description": "Data object for AddAdd conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictAddRename": {
      "description": "Data object for RenameAdd conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalPath": {
          "type": "string"
        }
      }
    },
    "GitConflictDeleteEdit": {
      "description": "Data object for EditDelete conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictDeleteRename": {
      "description": "Data object for RenameDelete conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictDirectoryFile": {
      "description": "Data object for FileDirectory conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceTree": {
          "$ref": "#/definitions/GitTreeRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictEditDelete": {
      "description": "Data object for DeleteEdit conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictEditEdit": {
      "description": "Data object for EditEdit conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictFileDirectory": {
      "description": "Data object for DirectoryFile conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetTree": {
          "$ref": "#/definitions/GitTreeRef"
        }
      }
    },
    "GitConflictRename1to2": {
      "description": "Data object for Rename1to2 conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionRename1to2"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceNewPath": {
          "type": "string"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRename2to1": {
      "description": "Data object for Rename2to1 conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceNewBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalPath": {
          "type": "string"
        },
        "targetNewBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRenameAdd": {
      "description": "Data object for AddRename conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalPath": {
          "type": "string"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictRenameDelete": {
      "description": "Data object for DeleteRename conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRenameRename": {
      "description": "Data object for RenameRename conflict",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "originalPath": {
          "type": "string"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitDeletedRepository": {
      "description": "",
      "type": "object",
      "properties": {
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "deletedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "deletedDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        }
      }
    },
    "GitFilePathsCollection": {
      "description": "",
      "type": "object",
      "properties": {
        "commitId": {
          "type": "string"
        },
        "paths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "readOnly": true,
          "type": "string"
        }
      }
    },
    "GitForkOperationStatusDetail": {
      "description": "Status information about a requested fork operation.",
      "type": "object",
      "properties": {
        "allSteps": {
          "description": "All valid steps for the forking process",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "currentStep": {
          "description": "Index into AllSteps for the current step",
          "type": "integer",
          "format": "int32"
        },
        "errorMessage": {
          "description": "Error message if the operation failed.",
          "type": "string"
        }
      }
    },
    "GitForkRef": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitRef"
        }
      ],
      "properties": {
        "repository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitForkRelationship": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "collection": {
          "description": "Team Project Collection where this Fork resides",
          "$ref": "#/definitions/TeamProjectCollectionReference"
        },
        "project": {
          "description": "Team Project where this Fork resides",
          "$ref": "#/definitions/TeamProjectReference"
        },
        "relationship": {
          "description": "Relationship of this fork to the current repository context",
          "enum": [
            "parent",
            "child"
          ]
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "repositoryName": {
          "type": "string"
        }
      }
    },
    "GitForkSyncRequest": {
      "description": "Request to sync data between two forks.",
      "type": "object",
      "properties": {
        "_links": {
          "description": "Collection of related links",
          "$ref": "#/definitions/ReferenceLinks"
        },
        "detailedStatus": {
          "$ref": "#/definitions/GitForkOperationStatusDetail"
        },
        "operationId": {
          "description": "Unique identifier for the operation.",
          "type": "integer",
          "format": "int32"
        },
        "status": {
          "enum": [
            "queued",
            "inProgress",
            "completed",
            "failed",
            "abandoned"
          ]
        }
      }
    },
    "GitForkSyncRequestParameters": {
      "description": "Parameters for creating a fork request",
      "type": "object",
      "properties": {
        "source": {
          "description": "Fully-qualified identifier for the source repository.",
          "$ref": "#/definitions/GlobalGitRepositoryKey"
        },
        "sourceToTargetRefs": {
          "description": "If supplied, the set of ref mappings to use when performing a \"sync\" or create. If missing, all refs will be synchronized.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/SourceToTargetRef"
          }
        }
      }
    },
    "GitImportFailedEvent": {
      "description": "",
      "type": "object",
      "properties": {
        "sourceRepositoryName": {
          "type": "string"
        },
        "targetRepository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitImportGitSource": {
      "description": "Parameter for creating a git import request when source is Git version control",
      "type": "object",
      "properties": {
        "overwrite": {
          "description": "Tells if this is a sync request or not",
          "type": "boolean"
        },
        "url": {
          "description": "Url for the source repo",
          "type": "string"
        }
      }
    },
    "GitImportRequest": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "detailedStatus": {
          "$ref": "#/definitions/GitImportStatusDetail"
        },
        "importRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "status": {
          "enum": [
            "queued",
            "inProgress",
            "completed",
            "failed",
            "abandoned"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitImportRequestParameters": {
      "description": "Parameters for creating an import request",
      "type": "object",
      "properties": {
        "deleteServiceEndpointAfterImportIsDone": {
          "description": "Option to delete service endpoint when import is done",
          "type": "boolean"
        },
        "gitSource": {
          "description": "Source for importing git repository",
          "$ref": "#/definitions/GitImportGitSource"
        },
        "serviceEndpointId": {
          "description": "Service Endpoint for connection to external endpoint",
          "type": "string",
          "format": "uuid"
        },
        "tfvcSource": {
          "description": "Source for importing tfvc repository",
          "$ref": "#/definitions/GitImportTfvcSource"
        }
      }
    },
    "GitImportStatusDetail": {
      "description": "",
      "type": "object",
      "properties": {
        "allSteps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "currentStep": {
          "type": "integer",
          "format": "int32"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    },
    "GitImportSucceededEvent": {
      "description": "",
      "type": "object",
      "properties": {
        "sourceRepositoryName": {
          "type": "string"
        },
        "targetRepository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitImportTfvcSource": {
      "description": "Parameter for creating a git import request when source is tfvc version control",
      "type": "object",
      "properties": {
        "importHistory": {
          "description": "Set true to import History, false otherwise",
          "type": "boolean"
        },
        "importHistoryDurationInDays": {
          "description": "Get history for last n days (max allowed value is 180 days)",
          "type": "integer",
          "format": "int32"
        },
        "path": {
          "description": "Path which we want to import (this can be copied from Path Control in Explorer)",
          "type": "string"
        }
      }
    },
    "GitItem": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ItemModel"
        }
      ],
      "properties": {
        "commitId": {
          "description": "SHA1 of commit item was fetched at",
          "type": "string"
        },
        "gitObjectType": {
          "description": "Type of object (Commit, Tree, Blob, Tag, ...)",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "latestProcessedChange": {
          "description": "Shallow ref to commit that last changed this item Only populated if latestProcessedChange is requested May not be accurate if latest change is not yet cached",
          "$ref": "#/definitions/GitCommitRef"
        },
        "objectId": {
          "description": "Git object id",
          "type": "string"
        },
        "originalObjectId": {
          "description": "Git object id",
          "type": "string"
        }
      }
    },
    "GitItemDescriptor": {
      "description": "",
      "type": "object",
      "properties": {
        "path": {
          "description": "Path to item",
          "readOnly": true,
          "type": "string"
        },
        "recursionLevel": {
          "description": "Specifies whether to include children (OneLevel), all descendants (Full), or None",
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        },
        "version": {
          "description": "Version string (interpretation based on VersionType defined in subclass",
          "readOnly": true,
          "type": "string"
        },
        "versionOptions": {
          "description": "Version modifiers (e.g. previous)",
          "readOnly": true,
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "versionType": {
          "description": "How to interpret version (branch,tag,commit)",
          "readOnly": true,
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitItemRequestData": {
      "description": "",
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "Whether to include metadata for all items",
          "readOnly": true,
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemDescriptors": {
          "description": "Collection of items to fetch, including path, version, and recursion level",
          "readOnly": true,
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitItemDescriptor"
          }
        },
        "latestProcessedChange": {
          "description": "Whether to include shallow ref to commit that last changed each item",
          "readOnly": true,
          "type": "boolean"
        }
      }
    },
    "GitLastChangeItem": {
      "description": "",
      "type": "object",
      "properties": {
        "commitId": {
          "description": "Gets or sets the commit Id this item was modified most recently for the provided version.",
          "type": "string"
        },
        "path": {
          "description": "Gets or sets the path of the item.",
          "type": "string"
        }
      }
    },
    "GitLastChangeTreeItems": {
      "description": "",
      "type": "object",
      "properties": {
        "commits": {
          "description": "The list of commits referenced by Items, if they were requested.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "items": {
          "description": "The last change of items.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitLastChangeItem"
          }
        },
        "lastExploredTime": {
          "description": "The last explored time, in case the result is not comprehensive. Null otherwise.",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitMergeOriginRef": {
      "description": "",
      "type": "object",
      "properties": {
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitObject": {
      "description": "",
      "type": "object",
      "properties": {
        "objectId": {
          "description": "Git object id",
          "type": "string"
        },
        "objectType": {
          "description": "Type of object (Commit, Tree, Blob, Tag)",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        }
      }
    },
    "GitPathAction": {
      "description": "",
      "type": "object",
      "properties": {
        "action": {
          "enum": [
            "none",
            "edit",
            "delete",
            "add",
            "rename"
          ]
        },
        "base64Content": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "rawTextContent": {
          "type": "string"
        },
        "targetPath": {
          "type": "string"
        }
      }
    },
    "GitPathToItemsCollection": {
      "description": "",
      "type": "object",
      "properties": {
        "items": {
          "type": "object",
          "additionalProperties": {
            "type": "array"
          }
        }
      }
    },
    "GitPullRequest": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "artifactId": {
          "type": "string"
        },
        "autoCompleteSetBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "closedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "closedDate": {
          "type": "string",
          "format": "date-time"
        },
        "codeReviewId": {
          "type": "integer",
          "format": "int32"
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "completionOptions": {
          "$ref": "#/definitions/GitPullRequestCompletionOptions"
        },
        "completionQueueTime": {
          "type": "string",
          "format": "date-time"
        },
        "createdBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "creationDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "forkSource": {
          "$ref": "#/definitions/GitForkRef"
        },
        "labels": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/WebApiTagDefinition"
          }
        },
        "lastMergeCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "lastMergeSourceCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "lastMergeTargetCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeFailureMessage": {
          "type": "string"
        },
        "mergeFailureType": {
          "enum": [
            "none",
            "unknown",
            "caseSensitive",
            "objectTooLarge"
          ]
        },
        "mergeId": {
          "type": "string",
          "format": "uuid"
        },
        "mergeOptions": {
          "$ref": "#/definitions/GitPullRequestMergeOptions"
        },
        "mergeStatus": {
          "enum": [
            "notSet",
            "queued",
            "conflicts",
            "succeeded",
            "rejectedByPolicy",
            "failure"
          ]
        },
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "remoteUrl": {
          "type": "string"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "reviewers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRefWithVote"
          }
        },
        "sourceRefName": {
          "type": "string"
        },
        "status": {
          "enum": [
            "notSet",
            "active",
            "abandoned",
            "completed",
            "all"
          ]
        },
        "supportsIterations": {
          "type": "boolean"
        },
        "targetRefName": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "workItemRefs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRef"
          }
        }
      }
    },
    "GitPullRequestChange": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitChange"
        }
      ],
      "properties": {
        "changeTrackingId": {
          "description": "Id used to track files through multiple changes",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPullRequestCommentThread": {
      "description": "Represents a given user or system Pull Request comment thread",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommentThread"
        }
      ],
      "properties": {
        "pullRequestThreadContext": {
          "description": "Extended context information unique to pull requests",
          "$ref": "#/definitions/GitPullRequestCommentThreadContext"
        }
      }
    },
    "GitPullRequestCommentThreadContext": {
      "description": "",
      "type": "object",
      "properties": {
        "changeTrackingId": {
          "description": "Used to track a comment across iterations. This value can be found by looking at the iteration's changes list. Must be set for pull requests with iteration support. Otherwise, it's not required for 'legacy' pull requests.",
          "type": "integer",
          "format": "int32"
        },
        "iterationContext": {
          "description": "Specify comparing iteration Ids when a comment thread is added while comparing 2 iterations.",
          "$ref": "#/definitions/CommentIterationContext"
        },
        "trackingCriteria": {
          "description": "The criteria used to track this thread. If this property is filled out when the thread is returned, then the thread has been tracked from its original location using the given criteria.",
          "$ref": "#/definitions/CommentTrackingCriteria"
        }
      }
    },
    "GitPullRequestCompletionOptions": {
      "description": "",
      "type": "object",
      "properties": {
        "bypassPolicy": {
          "type": "boolean"
        },
        "bypassReason": {
          "type": "string"
        },
        "deleteSourceBranch": {
          "type": "boolean"
        },
        "mergeCommitMessage": {
          "type": "string"
        },
        "squashMerge": {
          "type": "boolean"
        },
        "transitionWorkItems": {
          "type": "boolean"
        }
      }
    },
    "GitPullRequestIteration": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/IdentityRef"
        },
        "changeList": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestChange"
          }
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "commonRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "hasMoreCommits": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "push": {
          "$ref": "#/definitions/GitPushRef"
        },
        "reason": {
          "enum": [
            "push",
            "forcePush",
            "create",
            "rebase",
            "unknown"
          ]
        },
        "sourceRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "targetRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "updatedDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitPullRequestIterationChanges": {
      "description": "",
      "type": "object",
      "properties": {
        "changeEntries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestChange"
          }
        },
        "nextSkip": {
          "type": "integer",
          "format": "int32"
        },
        "nextTop": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPullRequestMergeOptions": {
      "description": "",
      "type": "object",
      "properties": {
        "disableRenames": {
          "type": "boolean"
        }
      }
    },
    "GitPullRequestQuery": {
      "description": "A pull request query",
      "type": "object",
      "properties": {
        "queries": {
          "description": "The query to perform",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestQueryInput"
          }
        },
        "results": {
          "description": "The results of the query",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "GitPullRequestQueryInput": {
      "description": "The input required for a pull request query. Currently there is only one query: LastMergeCommit, which returns all pull requests whose LastMergeCommit is in the list of CommitIds.",
      "type": "object",
      "properties": {
        "items": {
          "description": "The list commit ids to search for.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "type": {
          "description": "The type of query to perform",
          "enum": [
            "notSet",
            "lastMergeCommit",
            "commit"
          ]
        }
      }
    },
    "GitPullRequestReviewFileContentInfo": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "path": {
          "description": "The file change path.",
          "type": "string"
        },
        "sHA1Hash": {
          "description": "Content hash of on-disk representation of file content. Its calculated by the client by using SHA1 hash function. Ensure that uploaded file has same encoding as in source control.",
          "type": "string"
        }
      }
    },
    "GitPullRequestSearchCriteria": {
      "description": "",
      "type": "object",
      "properties": {
        "creatorId": {
          "type": "string",
          "format": "uuid"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "reviewerId": {
          "type": "string",
          "format": "uuid"
        },
        "sourceRefName": {
          "type": "string"
        },
        "sourceRepositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "status": {
          "enum": [
            "notSet",
            "active",
            "abandoned",
            "completed",
            "all"
          ]
        },
        "targetRefName": {
          "type": "string"
        }
      }
    },
    "GitPullRequestStatus": {
      "description": "This class contains the metadata of a service/extension posting pull request status. Status can be associated with a pull request or an iteration.",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitStatus"
        }
      ],
      "properties": {
        "iterationId": {
          "description": "ID of the iteration to associate status with. Minimum value is 1.",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPush": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitPushRef"
        }
      ],
      "properties": {
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "refUpdates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitRefUpdate"
          }
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitPushEventData": {
      "description": "",
      "type": "object",
      "properties": {
        "afterId": {
          "type": "string"
        },
        "beforeId": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommit"
          }
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitPushRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "pushCorrelationId": {
          "type": "string",
          "format": "uuid"
        },
        "pushedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "pushId": {
          "type": "integer",
          "format": "int32"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitPushSearchCriteria": {
      "description": "",
      "type": "object",
      "properties": {
        "fromDate": {
          "type": "string",
          "format": "date-time"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "includeRefUpdates": {
          "type": "boolean"
        },
        "pusherId": {
          "type": "string",
          "format": "uuid"
        },
        "refName": {
          "type": "string"
        },
        "toDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitQueryBranchStatsCriteria": {
      "description": "",
      "type": "object",
      "properties": {
        "baseCommit": {
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "targetCommits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitVersionDescriptor"
          }
        }
      }
    },
    "GitQueryCommitsCriteria": {
      "description": "",
      "type": "object",
      "properties": {
        "$skip": {
          "description": "Number of entries to skip",
          "type": "integer",
          "format": "int32"
        },
        "$top": {
          "description": "Maximum number of entries to retrieve",
          "type": "integer",
          "format": "int32"
        },
        "author": {
          "description": "Alias or display name of the author",
          "type": "string"
        },
        "compareVersion": {
          "description": "If provided, the earliest commit in the graph to search",
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "excludeDeletes": {
          "description": "If true, don't include delete history entries",
          "type": "boolean"
        },
        "fromCommitId": {
          "description": "If provided, a lower bound for filtering commits alphabetically",
          "type": "string"
        },
        "fromDate": {
          "description": "If provided, only include history entries created after this date (string)",
          "type": "string"
        },
        "historyMode": {
          "description": "What Git history mode should be used. This only applies to the search criteria when Ids = null.",
          "enum": [
            "simplifiedHistory",
            "firstParent",
            "fullHistory",
            "fullHistorySimplifyMerges"
          ]
        },
        "ids": {
          "description": "If provided, specifies the exact commit ids of the commits to fetch. May not be combined with other parameters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "includeWorkItems": {
          "description": "Whether to include linked work items",
          "type": "boolean"
        },
        "itemPath": {
          "description": "Path of item to search under",
          "type": "string"
        },
        "itemVersion": {
          "description": "If provided, identifies the commit or branch to search",
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "toCommitId": {
          "description": "If provided, an upper bound for filtering commits alphabetically",
          "type": "string"
        },
        "toDate": {
          "description": "If provided, only include history entries created before this date (string)",
          "type": "string"
        },
        "user": {
          "description": "Alias or display name of the committer",
          "type": "string"
        }
      }
    },
    "GitQueryRefsCriteria": {
      "description": "",
      "type": "object",
      "properties": {
        "commitIds": {
          "description": "List of commit Ids to be searched",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "refNames": {
          "description": "List of complete or partial names for refs to be searched",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "searchType": {
          "description": "Type of search on refNames, if provided",
          "enum": [
            "exact",
            "startsWith",
            "contains"
          ]
        }
      }
    },
    "GitRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "isLocked": {
          "type": "boolean"
        },
        "isLockedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "name": {
          "type": "string"
        },
        "objectId": {
          "type": "string"
        },
        "peeledObjectId": {
          "type": "string"
        },
        "statuses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitStatus"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitRefFavorite": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "identityId": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "enum": [
            "invalid",
            "folder",
            "ref"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitRefUpdate": {
      "description": "",
      "type": "object",
      "properties": {
        "isLocked": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "newObjectId": {
          "type": "string"
        },
        "oldObjectId": {
          "type": "string"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "GitRefUpdateResult": {
      "description": "",
      "type": "object",
      "properties": {
        "customMessage": {
          "description": "Custom message for the result object For instance, Reason for failing.",
          "type": "string"
        },
        "isLocked": {
          "description": "Whether the ref is locked or not",
          "type": "boolean"
        },
        "name": {
          "description": "Ref name",
          "type": "string"
        },
        "newObjectId": {
          "description": "New object ID",
          "type": "string"
        },
        "oldObjectId": {
          "description": "Old object ID",
          "type": "string"
        },
        "rejectedBy": {
          "description": "Name of the plugin that rejected the updated.",
          "type": "string"
        },
        "repositoryId": {
          "description": "Repository ID",
          "type": "string",
          "format": "uuid"
        },
        "success": {
          "description": "True if the ref update succeeded, false otherwise",
          "type": "boolean"
        },
        "updateStatus": {
          "description": "Status of the update from the TFS server.",
          "enum": [
            "succeeded",
            "forcePushRequired",
            "staleOldObjectId",
            "invalidRefName",
            "unprocessed",
            "unresolvableToCommit",
            "writePermissionRequired",
            "manageNotePermissionRequired",
            "createBranchPermissionRequired",
            "createTagPermissionRequired",
            "rejectedByPlugin",
            "locked",
            "refNameConflict",
            "rejectedByPolicy",
            "succeededNonExistentRef",
            "succeededCorruptRef"
          ]
        }
      }
    },
    "GitRepository": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "createdByForking": {
          "description": "True if the repository was created as a fork",
          "type": "boolean"
        },
        "defaultBranch": {
          "type": "string"
        },
        "forkOptions": {
          "description": "If set, options for creating this repo as a fork of another one. If unset, this repo is unrelated to any existing forks.",
          "$ref": "#/definitions/GitForkSyncRequestParameters"
        },
        "forkParent": {
          "description": "Only set when querying repositories. If set, the \"parent\" fork of this repository.",
          "$ref": "#/definitions/GlobalGitRepositoryKey"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "parentRepository": {
          "$ref": "#/definitions/GitRepositoryRef"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        },
        "remoteUrl": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "validRemoteUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "GitRepositoryCreateOptions": {
      "description": "",
      "type": "object",
      "properties": {
        "forkOptions": {
          "description": "If set, options for creating this repo as a fork of another one. If unset, this repo is unrelated to any existing forks.",
          "$ref": "#/definitions/GitForkSyncRequestParameters"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        }
      }
    },
    "GitRepositoryRef": {
      "description": "",
      "type": "object",
      "properties": {
        "collection": {
          "description": "Team Project Collection where this Fork resides",
          "$ref": "#/definitions/TeamProjectCollectionReference"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitRepositoryStats": {
      "description": "",
      "type": "object",
      "properties": {
        "activePullRequestsCount": {
          "type": "integer",
          "format": "int32"
        },
        "branchesCount": {
          "type": "integer",
          "format": "int32"
        },
        "commitsCount": {
          "type": "integer",
          "format": "int32"
        },
        "repositoryId": {
          "type": "string"
        }
      }
    },
    "GitResolution": {
      "description": "",
      "type": "object",
      "properties": {
      }
    },
    "GitResolutionMergeContent": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "mergeType": {
          "enum": [
            "undecided",
            "takeSourceContent",
            "takeTargetContent",
            "autoMerged",
            "userMerged"
          ]
        },
        "userMergedBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "userMergedContent": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "byte"
          }
        }
      }
    },
    "GitResolutionPathConflict": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "keepSourceRenameTarget",
            "keepSourceDeleteTarget",
            "keepTargetRenameSource",
            "keepTargetDeleteSource"
          ]
        },
        "renamePath": {
          "type": "string"
        }
      }
    },
    "GitResolutionPickOneAction": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "pickSourceAction",
            "pickTargetAction"
          ]
        }
      }
    },
    "GitResolutionRename1to2": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolutionMergeContent"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "keepSourcePath",
            "keepTargetPath",
            "keepBothFiles"
          ]
        }
      }
    },
    "GitRevert": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitAsyncRefOperation"
        }
      ],
      "properties": {
        "revertId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitStatus": {
      "description": "This class contains the metadata of a service/extension posting a status.",
      "type": "object",
      "properties": {
        "_links": {
          "description": "Reference links.",
          "$ref": "#/definitions/ReferenceLinks"
        },
        "context": {
          "description": "Context of the status.",
          "$ref": "#/definitions/GitStatusContext"
        },
        "createdBy": {
          "description": "Identity that created the status.",
          "$ref": "#/definitions/IdentityRef"
        },
        "creationDate": {
          "description": "Creation date and time of the status.",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "Status description. Typically describes current state of the status.",
          "type": "string"
        },
        "id": {
          "description": "Status identifier.",
          "type": "integer",
          "format": "int32"
        },
        "state": {
          "description": "State of the status.",
          "enum": [
            "notSet",
            "pending",
            "succeeded",
            "failed",
            "error"
          ]
        },
        "targetUrl": {
          "description": "URL with status details.",
          "type": "string"
        },
        "updatedDate": {
          "description": "Last update date and time of the status.",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitStatusContext": {
      "description": "Status context that uniquely identifies the status.",
      "type": "object",
      "properties": {
        "genre": {
          "description": "Genre of the status. Typically name of the service/tool generating the status, can be empty.",
          "type": "string"
        },
        "name": {
          "description": "Name identifier of the status, cannot be null or empty.",
          "type": "string"
        }
      }
    },
    "GitSuggestion": {
      "description": "",
      "type": "object",
      "properties": {
        "properties": {
          "type": "object",
          "additionalProperties": {
            "type": "object"
          }
        },
        "type": {
          "type": "string"
        }
      }
    },
    "GitTargetVersionDescriptor": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitVersionDescriptor"
        }
      ],
      "properties": {
        "targetVersion": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "targetVersionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "targetVersionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitTemplate": {
      "description": "",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the Template",
          "type": "string"
        },
        "type": {
          "description": "Type of the Template",
          "type": "string"
        }
      }
    },
    "GitTreeDiff": {
      "description": "",
      "type": "object",
      "properties": {
        "baseTreeId": {
          "description": "ObjectId of the base tree of this diff.",
          "type": "string"
        },
        "diffEntries": {
          "description": "List of tree entries that differ between the base and target tree.  Renames and object type changes are returned as a delete for the old object and add for the new object.  If a continuation token is returned in the response header, some tree entries are yet to be processed and may yeild more diff entries. If the continuation token is not returned all the diff entries have been included in this response.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitTreeDiffEntry"
          }
        },
        "targetTreeId": {
          "description": "ObjectId of the target tree of this diff.",
          "type": "string"
        },
        "url": {
          "description": "REST Url to this resource.",
          "type": "string"
        }
      }
    },
    "GitTreeDiffEntry": {
      "description": "",
      "type": "object",
      "properties": {
        "baseObjectId": {
          "description": "SHA1 hash of the object in the base tree, if it exists. Will be null in case of adds.",
          "type": "string"
        },
        "changeType": {
          "description": "Type of change that affected this entry.",
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "objectType": {
          "description": "Object type of the tree entry. Blob, Tree or Commit(\"submodule\")",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "path": {
          "description": "Relative path in base and target trees.",
          "type": "string"
        },
        "targetObjectId": {
          "description": "SHA1 hash of the object in the target tree, if it exists. Will be null in case of deletes.",
          "type": "string"
        }
      }
    },
    "GitTreeDiffResponse": {
      "description": "",
      "type": "object",
      "properties": {
        "continuationToken": {
          "description": "The HTTP client methods find the continuation token header in the response and populate this field.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "treeDiff": {
          "$ref": "#/definitions/GitTreeDiff"
        }
      }
    },
    "GitTreeEntryRef": {
      "description": "",
      "type": "object",
      "properties": {
        "gitObjectType": {
          "description": "Blob or tree",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "mode": {
          "description": "Mode represented as octal string",
          "type": "string"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "relativePath": {
          "description": "Path relative to parent tree object",
          "type": "string"
        },
        "size": {
          "description": "Size of content",
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "description": "url to retrieve tree or blob",
          "type": "string"
        }
      }
    },
    "GitTreeRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "size": {
          "description": "Sum of sizes of all children",
          "type": "integer",
          "format": "int64"
        },
        "treeEntries": {
          "description": "Blobs and trees under this tree",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitTreeEntryRef"
          }
        },
        "url": {
          "description": "Url to tree",
          "type": "string"
        }
      }
    },
    "GitUserDate": {
      "description": "",
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitVersionDescriptor": {
      "description": "",
      "type": "object",
      "properties": {
        "version": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "versionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "versionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GlobalGitRepositoryKey": {
      "description": "Globally unique key for a repository.",
      "type": "object",
      "properties": {
        "collectionId": {
          "type": "string",
          "format": "uuid"
        },
        "projectId": {
          "type": "string",
          "format": "uuid"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "HistoryEntry": {
      "description": "",
      "type": "object",
      "properties": {
        "changeList": {
          "description": "The Change list (changeset/commit/shelveset) for this point in history",
          "type": "string",
          "format": "ChangeList"
        },
        "itemChangeType": {
          "description": "The change made to the item from this change list (only relevant for File history, not folders)",
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "serverItem": {
          "description": "The path of the item at this point in history (only relevant for File history, not folders)",
          "type": "string"
        }
      }
    },
    "IdentityRef": {
      "description": "",
      "type": "object",
      "properties": {
        "directoryAlias": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "inactive": {
          "type": "boolean"
        },
        "isAadIdentity": {
          "type": "boolean"
        },
        "isContainer": {
          "type": "boolean"
        },
        "profileUrl": {
          "type": "string"
        },
        "uniqueName": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "IdentityRefWithVote": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/IdentityRef"
        }
      ],
      "properties": {
        "isRequired": {
          "type": "boolean"
        },
        "reviewerUrl": {
          "type": "string"
        },
        "vote": {
          "type": "integer",
          "format": "int16"
        },
        "votedFor": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRefWithVote"
          }
        }
      }
    },
    "ImportRepositoryValidation": {
      "description": "",
      "type": "object",
      "properties": {
        "gitSource": {
          "$ref": "#/definitions/GitImportGitSource"
        },
        "password": {
          "type": "string"
        },
        "tfvcSource": {
          "$ref": "#/definitions/GitImportTfvcSource"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "IncludedGitCommit": {
      "description": "",
      "type": "object",
      "properties": {
        "commitId": {
          "type": "string"
        },
        "commitTime": {
          "type": "string",
          "format": "date-time"
        },
        "parentCommitIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "ItemContent": {
      "description": "",
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "contentType": {
          "enum": [
            "rawText",
            "base64Encoded"
          ]
        }
      }
    },
    "ItemDetailsOptions": {
      "description": "Optional details to include when returning an item model",
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "If true, include metadata about the file type",
          "type": "boolean"
        },
        "recursionLevel": {
          "description": "Specifies whether to include children (OneLevel), all descendants (Full) or None for folder items",
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        }
      }
    },
    "ItemModel": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "contentMetadata": {
          "$ref": "#/definitions/FileContentMetadata"
        },
        "isFolder": {
          "type": "boolean"
        },
        "isSymLink": {
          "type": "boolean"
        },
        "path": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "PropertiesCollection": {
      "description": "",
      "type": "object",
      "properties": {
        "count": {
          "description": "The count of properties in the collection.",
          "readOnly": true,
          "type": "integer",
          "format": "int32"
        },
        "item": {
          "type": "object"
        },
        "keys": {
          "description": "The set of keys in the collection.",
          "readOnly": true,
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "values": {
          "description": "The set of values in the collection.",
          "readOnly": true,
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PullRequestTabExtensionConfig": {
      "description": "Initial config contract sent to extensions creating tabs on the pull request page",
      "type": "object",
      "properties": {
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "repositoryId": {
          "type": "string"
        }
      }
    },
    "ReferenceLinks": {
      "description": "The class to represent a collection of REST reference links.  Example: { self: { href: \"http://localhost:8080/tfs/DefaultCollection/_apis/wit/workItems/1\" } }",
      "type": "object",
      "properties": {
      }
    },
    "ResourceRef": {
      "description": "",
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "ShareNotificationContext": {
      "description": "Context used while sharing a pull request.",
      "type": "object",
      "properties": {
        "message": {
          "description": "Optional user note or message.",
          "type": "string"
        },
        "receivers": {
          "description": "Identities of users who will receive a share notification.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRef"
          }
        }
      }
    },
    "SourceToTargetRef": {
      "description": "",
      "type": "object",
      "properties": {
        "sourceRef": {
          "description": "The source ref to copy. For example, refs/heads/master.",
          "type": "string"
        },
        "targetRef": {
          "description": "The target ref to update. For example, refs/heads/master",
          "type": "string"
        }
      }
    },
    "SupportedIde": {
      "description": "Represents a Supported IDE entity.",
      "type": "object",
      "properties": {
        "downloadUrl": {
          "description": "The download URL for the IDE.",
          "type": "string"
        },
        "ideType": {
          "description": "The type of the IDE.",
          "enum": [
            "unknown",
            "androidStudio",
            "appCode",
            "cLion",
            "dataGrip",
            "eclipse",
            "intelliJ",
            "mPS",
            "phpStorm",
            "pyCharm",
            "rubyMine",
            "tower",
            "visualStudio",
            "webStorm"
          ]
        },
        "name": {
          "description": "The name of the IDE.",
          "type": "string"
        },
        "protocolHandlerUrl": {
          "description": "The URL to open the protocol handler for the IDE.",
          "type": "string"
        },
        "supportedPlatforms": {
          "description": "A list of SupportedPlatforms.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "TeamProjectCollectionReference": {
      "description": "Reference object for a TeamProjectCollection.",
      "type": "object",
      "properties": {
        "id": {
          "description": "Collection Id.",
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "description": "Collection Name.",
          "type": "string"
        },
        "url": {
          "description": "Collection REST Url.",
          "type": "string"
        }
      }
    },
    "TeamProjectReference": {
      "description": "Represents a shallow reference to a TeamProject.",
      "type": "object",
      "properties": {
        "abbreviation": {
          "description": "Project abbreviation.",
          "type": "string"
        },
        "description": {
          "description": "The project's description (if any).",
          "type": "string"
        },
        "id": {
          "description": "Project identifier.",
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "description": "Project name.",
          "type": "string"
        },
        "revision": {
          "description": "Project revision.",
          "type": "integer",
          "format": "int64"
        },
        "state": {
          "description": "Project state.",
          "enum": [
            "deleting",
            "new",
            "wellFormed",
            "createPending",
            "all",
            "unchanged",
            "deleted"
          ]
        },
        "url": {
          "description": "Url to the full version of the object.",
          "type": "string"
        },
        "visibility": {
          "description": "Project visibility.",
          "enum": [
            "unchanged",
            "private",
            "organization",
            "public"
          ]
        }
      }
    },
    "TfvcBranch": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcBranchRef"
        }
      ],
      "properties": {
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcBranch"
          }
        },
        "mappings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcBranchMapping"
          }
        },
        "parent": {
          "$ref": "#/definitions/TfvcShallowBranchRef"
        },
        "relatedBranches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcShallowBranchRef"
          }
        }
      }
    },
    "TfvcBranchMapping": {
      "description": "",
      "type": "object",
      "properties": {
        "depth": {
          "type": "string"
        },
        "serverItem": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "TfvcBranchRef": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcShallowBranchRef"
        }
      ],
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "isDeleted": {
          "type": "boolean"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcChange": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "Change"
        }
      ],
      "properties": {
        "mergeSources": {
          "description": "List of merge sources in case of rename or branch creation.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcMergeSource"
          }
        },
        "pendingVersion": {
          "description": "Version at which a (shelved) change was pended against",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcChangeset": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcChangesetRef"
        }
      ],
      "properties": {
        "accountId": {
          "type": "string",
          "format": "uuid"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcChange"
          }
        },
        "checkinNotes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "collectionId": {
          "type": "string",
          "format": "uuid"
        },
        "hasMoreChanges": {
          "type": "boolean"
        },
        "policyOverride": {
          "$ref": "#/definitions/TfvcPolicyOverrideInfo"
        },
        "teamProjectIds": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AssociatedWorkItem"
          }
        }
      }
    },
    "TfvcChangesetRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/IdentityRef"
        },
        "changesetId": {
          "type": "integer",
          "format": "int32"
        },
        "checkedInBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcChangesetSearchCriteria": {
      "description": "Criteria used in a search for change lists",
      "type": "object",
      "properties": {
        "author": {
          "description": "Alias or display name of user who made the changes",
          "type": "string"
        },
        "followRenames": {
          "description": "Whether or not to follow renames for the given item being queried",
          "type": "boolean"
        },
        "fromDate": {
          "description": "If provided, only include changesets created after this date (string) Think of a better name for this.",
          "type": "string"
        },
        "fromId": {
          "description": "If provided, only include changesets after this changesetID",
          "type": "integer",
          "format": "int32"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemPath": {
          "description": "Path of item to search under",
          "type": "string"
        },
        "toDate": {
          "description": "If provided, only include changesets created before this date (string) Think of a better name for this.",
          "type": "string"
        },
        "toId": {
          "description": "If provided, a version descriptor for the latest change list to include",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcChangesetsRequestData": {
      "description": "",
      "type": "object",
      "properties": {
        "changesetIds": {
          "readOnly": true,
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "commentLength": {
          "readOnly": true,
          "type": "integer",
          "format": "int32"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        }
      }
    },
    "TfvcCheckinEventData": {
      "description": "",
      "type": "object",
      "properties": {
        "changeset": {
          "$ref": "#/definitions/TfvcChangeset"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        }
      }
    },
    "TfvcHistoryEntry": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "HistoryEntry"
        }
      ],
      "properties": {
        "encoding": {
          "description": "The encoding of the item at this point in history (only relevant for File history, not folders)",
          "type": "integer",
          "format": "int32"
        },
        "fileId": {
          "description": "The file id of the item at this point in history (only relevant for File history, not folders)",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcItem": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ItemModel"
        }
      ],
      "properties": {
        "changeDate": {
          "type": "string",
          "format": "date-time"
        },
        "deletionId": {
          "type": "integer",
          "format": "int32"
        },
        "hashValue": {
          "description": "MD5 hash as a base 64 string, applies to files only.",
          "type": "string"
        },
        "isBranch": {
          "type": "boolean"
        },
        "isPendingChange": {
          "type": "boolean"
        },
        "size": {
          "description": "The size of the file, if applicable.",
          "type": "integer",
          "format": "int64"
        },
        "version": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcItemDescriptor": {
      "description": "Item path and Version descriptor properties",
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "recursionLevel": {
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        },
        "version": {
          "type": "string"
        },
        "versionOption": {
          "enum": [
            "none",
            "previous",
            "useRename"
          ]
        },
        "versionType": {
          "enum": [
            "none",
            "changeset",
            "shelveset",
            "change",
            "date",
            "latest",
            "tip",
            "mergeSource"
          ]
        }
      }
    },
    "TfvcItemRequestData": {
      "description": "",
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "If true, include metadata about the file type",
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemDescriptors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcItemDescriptor"
          }
        }
      }
    },
    "TfvcLabel": {
      "description": "",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcLabelRef"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcItem"
          }
        }
      }
    },
    "TfvcLabelRef": {
      "description": "",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "labelScope": {
          "type": "string"
        },
        "modifiedDate": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcLabelRequestData": {
      "description": "",
      "type": "object",
      "properties": {
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemLabelFilter": {
          "type": "string"
        },
        "labelScope": {
          "type": "string"
        },
        "maxItemCount": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        }
      }
    },
    "TfvcMergeSource": {
      "description": "",
      "type": "object",
      "properties": {
        "isRename": {
          "description": "Indicates if this a rename source. If false, it is a merge source.",
          "type": "boolean"
        },
        "serverItem": {
          "description": "The server item of the merge source",
          "type": "string"
        },
        "versionFrom": {
          "description": "Start of the version range",
          "type": "integer",
          "format": "int32"
        },
        "versionTo": {
          "description": "End of the version range",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcPolicyFailureInfo": {
      "description": "",
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "policyName": {
          "type": "string"
        }
      }
    },
    "TfvcPolicyOverrideInfo": {
      "description": "",
      "type": "object",
      "properties": {
        "comment": {
          "type": "string"
        },
        "policyFailures": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcPolicyFailureInfo"
          }
        }
      }
    },
    "TfvcShallowBranchRef": {
      "description": "",
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      }
    },
    "TfvcShelveset": {
      "description": "This is the deep shelveset class",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcShelvesetRef"
        }
      ],
      "properties": {
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcChange"
          }
        },
        "notes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "policyOverride": {
          "$ref": "#/definitions/TfvcPolicyOverrideInfo"
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AssociatedWorkItem"
          }
        }
      }
    },
    "TfvcShelvesetRef": {
      "description": "This is the shallow shelveset class",
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcShelvesetRequestData": {
      "description": "",
      "type": "object",
      "properties": {
        "includeDetails": {
          "description": "Whether to include policyOverride and notes Only applies when requesting a single deep shelveset",
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references. Does not apply when requesting a single deep shelveset object. Links will always be included in the deep shelveset.",
          "type": "boolean"
        },
        "includeWorkItems": {
          "description": "Whether to include workItems",
          "type": "boolean"
        },
        "maxChangeCount": {
          "description": "Max number of changes to include",
          "type": "integer",
          "format": "int32"
        },
        "maxCommentLength": {
          "description": "Max length of comment",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "description": "Shelveset's name",
          "type": "string"
        },
        "owner": {
          "description": "Owner's ID. Could be a name or a guid.",
          "type": "string"
        }
      }
    },
    "TfvcVersionDescriptor": {
      "description": "",
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "versionOption": {
          "enum": [
            "none",
            "previous",
            "useRename"
          ]
        },
        "versionType": {
          "enum": [
            "none",
            "changeset",
            "shelveset",
            "change",
            "date",
            "latest",
            "tip",
            "mergeSource"
          ]
        }
      }
    },
    "UpdateRefsRequest": {
      "description": "",
      "type": "object",
      "properties": {
        "refUpdateRequests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitRefUpdate"
          }
        },
        "updateMode": {
          "enum": [
            "bestEffort",
            "allOrNone"
          ]
        }
      }
    },
    "VersionControlProjectInfo": {
      "description": "",
      "type": "object",
      "properties": {
        "defaultSourceControlType": {
          "enum": [
            "tfvc",
            "git"
          ]
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        },
        "supportsGit": {
          "type": "boolean"
        },
        "supportsTFVC": {
          "type": "boolean"
        }
      }
    },
    "VssJsonCollectionWrapper": {
      "description": "This class is used to serialized collections as a single JSON object on the wire, to avoid serializing JSON arrays directly to the client, which can be a security hole",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/VssJsonCollectionWrapperBase"
        }
      ],
      "properties": {
        "value": {
          "readOnly": true,
          "type": "string",
          "format": "T"
        }
      }
    },
    "VssJsonCollectionWrapperBase": {
      "description": "",
      "type": "object",
      "properties": {
        "count": {
          "readOnly": true,
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "WebApiCreateTagRequestData": {
      "description": "The representation of data needed to create a tag definition which is sent across the wire.",
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      }
    },
    "WebApiTagDefinition": {
      "description": "The representation of a tag definition which is sent across the wire.",
      "type": "object",
      "properties": {
        "active": {
          "type": "boolean"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.code": "Grants the ability to read source code and metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to get notified about version control events via service hooks.",
        "vso.code_manage": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage code repositories, create and manage pull requests and code reviews, and to receive notifications about version control events via service hooks.",
        "vso.code_write": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage pull requests and code reviews and to receive notifications about version control events via service hooks.",
        "vso.code_status": "Grants the ability to read and write commit and pull request status."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}