{
  "swagger": "2.0",
  "info": {
    "title": "Core",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.0"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "connectedServices"
    },
    {
      "name": "identityMru"
    },
    {
      "name": "members"
    },
    {
      "name": "processes"
    },
    {
      "name": "projectCollections"
    },
    {
      "name": "projectHistory"
    },
    {
      "name": "projects"
    },
    {
      "name": "proxies"
    },
    {
      "name": "teams"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/core/identitymru/{mruName}": {
      "post": {
        "tags": [
          "IdentityMru"
        ],
        "description": "",
        "operationId": "IdentityMru_Create"
      },
      "get": {
        "tags": [
          "IdentityMru"
        ],
        "description": "",
        "operationId": "IdentityMru_Get"
      },
      "patch": {
        "tags": [
          "IdentityMru"
        ],
        "description": "",
        "operationId": "IdentityMru_Update"
      }
    },
    "/_apis/process/processes": {
      "get": {
        "tags": [
          "Processes"
        ],
        "description": "Retrieve all processes",
        "operationId": "Processes_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/process/processes/{processId}": {
      "get": {
        "tags": [
          "Processes"
        ],
        "description": "Retrieve process by id",
        "operationId": "Processes_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/projectcollections": {
      "get": {
        "tags": [
          "ProjectCollections"
        ],
        "description": "Get project collection references for this application.",
        "operationId": "ProjectCollections_List",
        "security": [
          {
            "oauth2": [
              "vso.profile"
            ]
          }
        ]
      }
    },
    "/_apis/projectcollections/{collectionId}": {
      "get": {
        "tags": [
          "ProjectCollections"
        ],
        "description": "Get project collection with the specified id or name.",
        "operationId": "ProjectCollections_Get",
        "security": [
          {
            "oauth2": [
              "vso.profile"
            ]
          }
        ]
      }
    },
    "/_apis/projecthistory": {
      "get": {
        "tags": [
          "ProjectHistory"
        ],
        "description": "",
        "operationId": "ProjectHistory_List"
      }
    },
    "/_apis/projects": {
      "get": {
        "tags": [
          "Projects"
        ],
        "description": "Get project references with the specified state",
        "operationId": "Projects_GetProjects",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Projects"
        ],
        "description": "Queue a project creation.",
        "operationId": "Projects_QueueCreateProject",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}": {
      "get": {
        "tags": [
          "Projects"
        ],
        "description": "Get project with the specified id or name, optionally including capabilities.",
        "operationId": "Projects_GetProject",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Projects"
        ],
        "description": "Queue a project deletion.",
        "operationId": "Projects_QueueDeleteProject",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Projects"
        ],
        "description": "Update an existing project's name, abbreviation, or description.",
        "operationId": "Projects_Update",
        "security": [
          {
            "oauth2": [
              "vso.project_write"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/connectedservices": {
      "post": {
        "tags": [
          "ConnectedServices"
        ],
        "description": "",
        "operationId": "ConnectedServices_Create",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ConnectedServices"
        ],
        "description": "",
        "operationId": "ConnectedServices_List",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/connectedservices/{name}": {
      "get": {
        "tags": [
          "ConnectedServices"
        ],
        "description": "",
        "operationId": "ConnectedServices_Get",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/properties": {
      "get": {
        "tags": [
          "Projects"
        ],
        "description": "Get a collection of team project properties.",
        "operationId": "Projects_List",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Projects"
        ],
        "description": "Create, update, and delete team project properties.",
        "operationId": "Projects_SetProjectProperties",
        "security": [
          {
            "oauth2": [
              "vso.project_write"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams": {
      "post": {
        "tags": [
          "Teams"
        ],
        "description": "Creates a team",
        "operationId": "Teams_Create",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Teams"
        ],
        "description": "",
        "operationId": "Teams_GetTeams",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams/{teamId}": {
      "delete": {
        "tags": [
          "Teams"
        ],
        "description": "Deletes a team",
        "operationId": "Teams_Delete",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Teams"
        ],
        "description": "Gets a team",
        "operationId": "Teams_GetTeam",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teams"
        ],
        "description": "Updates a team's name and/or description",
        "operationId": "Teams_Update",
        "security": [
          {
            "oauth2": [
              "vso.project_write"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams/{teamId}/members": {
      "get": {
        "tags": [
          "Members"
        ],
        "description": "",
        "operationId": "Members_Get",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/proxies": {
      "put": {
        "tags": [
          "Proxies"
        ],
        "description": "",
        "operationId": "Proxies_Create"
      },
      "delete": {
        "tags": [
          "Proxies"
        ],
        "description": "",
        "operationId": "Proxies_Delete"
      },
      "get": {
        "tags": [
          "Proxies"
        ],
        "description": "",
        "operationId": "Proxies_List"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.profile": "Grants the ability to read your profile, accounts, collections, projects, teams, and other top-level organizational artifacts.",
        "vso.project": "Grants the ability to read projects and teams.",
        "vso.project_manage": "Grants the ability to create, read, update, and delete projects and teams.",
        "vso.project_write": "Grants the ability to read and update projects and teams.",
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}