{
  "swagger": "2.0",
  "info": {
    "title": "TaskAgent",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Agents"
    },
    {
      "name": "Azurermsubscriptions"
    },
    {
      "name": "Deploymentgroupaccesstoken"
    },
    {
      "name": "Deploymentgroups"
    },
    {
      "name": "Deploymentgroupsmetrics"
    },
    {
      "name": "Deploymentmachinejobrequests"
    },
    {
      "name": "Deploymentmachinemessages"
    },
    {
      "name": "Deploymentpoolaccesstoken"
    },
    {
      "name": "Endpoint"
    },
    {
      "name": "Executionhistory"
    },
    {
      "name": "Icon"
    },
    {
      "name": "Inputvalidation"
    },
    {
      "name": "Machinegroupaccesstoken"
    },
    {
      "name": "Machinegroups"
    },
    {
      "name": "Machines"
    },
    {
      "name": "Maintenancedefinitions"
    },
    {
      "name": "Maintenancejobs"
    },
    {
      "name": "Messages"
    },
    {
      "name": "Packages",
      "description": "At resource version 2, the Packages endpoint returns Package objects and does not support streaming package contents."
    },
    {
      "name": "Queues"
    },
    {
      "name": "Revisions"
    },
    {
      "name": "Securefiles"
    },
    {
      "name": "Serviceendpointproxy"
    },
    {
      "name": "Serviceendpoints"
    },
    {
      "name": "Serviceendpointtypes"
    },
    {
      "name": "Targets"
    },
    {
      "name": "Taskgroups"
    },
    {
      "name": "Tasks"
    },
    {
      "name": "Updates"
    },
    {
      "name": "Usercapabilities"
    },
    {
      "name": "Variablegroups"
    },
    {
      "name": "Vstsaadoauth"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/distributedtask/deploymentpoolaccesstoken/{poolId}": {
      "post": {
        "tags": [
          "Deploymentpoolaccesstoken"
        ],
        "description": "",
        "operationId": "Generate Deployment Pool Access Token"
      }
    },
    "/_apis/distributedtask/endpoint": {
      "post": {
        "tags": [
          "Endpoint"
        ],
        "description": "Proxy for a GET request defined by an 'endpoint'. The request is authorized using a service connection. The response is filtered using an XPath/Json based selector.",
        "operationId": "Query"
      }
    },
    "/_apis/distributedtask/inputvalidation": {
      "post": {
        "tags": [
          "Inputvalidation"
        ],
        "description": "",
        "operationId": "Validate Inputs"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "List"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}/{version}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "Get"
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents": {
      "post": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Add",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}": {
      "delete": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Replace Agent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/updates": {
      "put": {
        "tags": [
          "Updates"
        ],
        "description": "",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/usercapabilities": {
      "put": {
        "tags": [
          "Usercapabilities"
        ],
        "description": "",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions": {
      "post": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions/{definitionId}": {
      "delete": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Update"
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs": {
      "get": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Queue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs/{jobId}": {
      "delete": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages": {
      "get": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Refresh Agent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages/{messageId}": {
      "delete": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/azurermsubscriptions": {
      "get": {
        "tags": [
          "Azurermsubscriptions"
        ],
        "description": "Returns list of azure subscriptions",
        "operationId": "Get"
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/vstsaadoauth": {
      "post": {
        "tags": [
          "Vstsaadoauth"
        ],
        "description": "",
        "operationId": "Acquire Access Token"
      },
      "get": {
        "tags": [
          "Vstsaadoauth"
        ],
        "description": "",
        "operationId": "Get"
      }
    },
    "/_apis/distributedtask/serviceendpointtypes": {
      "get": {
        "tags": [
          "Serviceendpointtypes"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}": {
      "delete": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}/icon": {
      "get": {
        "tags": [
          "Icon"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroupaccesstoken/{deploymentGroupId}": {
      "post": {
        "tags": [
          "Deploymentgroupaccesstoken"
        ],
        "description": "",
        "operationId": "Generate Deployment Group Access Token"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups": {
      "post": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Add"
      },
      "get": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "List"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}": {
      "delete": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Get"
      },
      "patch": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Update"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinejobrequests": {
      "get": {
        "tags": [
          "Deploymentmachinejobrequests"
        ],
        "description": "",
        "operationId": "Get Agent Requests For Deployment Machine"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinemessages": {
      "post": {
        "tags": [
          "Deploymentmachinemessages"
        ],
        "description": "",
        "operationId": "Refresh Deployment Machines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines": {
      "post": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Add"
      },
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Get Deployment Machines"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Update Deployment Machines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines/{machineId}": {
      "delete": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Get"
      },
      "put": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Replace Deployment Machine"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Update Deployment Machine"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/targets": {
      "post": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Add"
      },
      "get": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "List"
      },
      "patch": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Update Deployment Targets"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/targets/{targetId}": {
      "delete": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Get"
      },
      "put": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Replace Deployment Target"
      },
      "patch": {
        "tags": [
          "Targets"
        ],
        "description": "",
        "operationId": "Update Deployment Target"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/deploymentgroupsmetrics": {
      "get": {
        "tags": [
          "Deploymentgroupsmetrics"
        ],
        "description": "",
        "operationId": "List"
      }
    },
    "/{project}/_apis/distributedtask/machinegroupaccesstoken/{machineGroupId}": {
      "post": {
        "tags": [
          "Machinegroupaccesstoken"
        ],
        "description": "",
        "operationId": "Generate Deployment Machine Group Access Token"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups": {
      "post": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Add"
      },
      "get": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "List"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}": {
      "delete": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Get"
      },
      "patch": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Update"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}/machines": {
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Get Deployment Machine Group Machines"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Update Deployment Machine Group Machines"
      }
    },
    "/{project}/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Add",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Get Agent Queues",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/securefiles": {
      "get": {
        "tags": [
          "Securefiles"
        ],
        "description": "Get secure files",
        "operationId": "Get Secure Files"
      },
      "post": {
        "tags": [
          "Securefiles"
        ],
        "description": "Query secure files using a name pattern and a condition on file properties.",
        "operationId": "Query"
      },
      "patch": {
        "tags": [
          "Securefiles"
        ],
        "description": "Update properties and/or names of a set of secure files. Files are identified by their IDs. Properties provided override the existing one entirely, i.e. do not merge.",
        "operationId": "Update Secure Files"
      }
    },
    "/{project}/_apis/distributedtask/securefiles/{secureFileId}": {
      "delete": {
        "tags": [
          "Securefiles"
        ],
        "description": "Delete a secure file",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Securefiles"
        ],
        "description": "Download a secure file by Id",
        "operationId": "Download Secure File"
      },
      "patch": {
        "tags": [
          "Securefiles"
        ],
        "description": "Update the name or properties of an existing secure file",
        "operationId": "Update Secure File"
      }
    },
    "/{project}/_apis/distributedtask/serviceendpointproxy": {
      "post": {
        "tags": [
          "Serviceendpointproxy"
        ],
        "description": "",
        "operationId": "Execute Service Endpoint Request",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_query"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints": {
      "post": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Get Service Endpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Update Service Endpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}": {
      "delete": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Update Service Endpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}/executionhistory": {
      "get": {
        "tags": [
          "Executionhistory"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/executionhistory": {
      "post": {
        "tags": [
          "Executionhistory"
        ],
        "description": "",
        "operationId": "Add",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups": {
      "post": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Create a task group.",
        "operationId": "Add",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}": {
      "delete": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Delete a task group.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Taskgroups"
        ],
        "deprecated": true,
        "description": "This REST API is deprecated and will be removed in a future release. Use GetTasGroupAsync(project, searchText = null, expand = null, artifactType = null, artifactSourceId = null, top = null, continuationToken = null, queryOrder = null, path = null, isExactNameMatch = null, tagFilter = null, propertyFilters = null, definitionIdFilter = null, userState = null, cancellationToken = default(CancellationToken)) instead.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Update a task group.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}/revisions": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_read"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/variablegroups": {
      "post": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Add"
      },
      "get": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Get Variable Groups"
      }
    },
    "/{project}/_apis/distributedtask/variablegroups/{groupId}": {
      "delete": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Get"
      },
      "put": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Update"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.agentpools": "Grants the ability to view tasks, pools, queues, agents, and currently running or recently completed jobs for agents",
        "vso.agentpools_manage": "Grants the ability to manage pools, queues, and agents",
        "vso.serviceendpoint": "Grants the ability to read service endpoints.",
        "vso.serviceendpoint_manage": "Grants the ability to read, query and manage service endpoints.",
        "vso.serviceendpoint_query": "Grants the ability to read and query service endpoints.",
        "vso.taskgroups_manage": "Grants the ability to read, create and manage taskgroups.",
        "vso.taskgroups_read": "Grants the ability to read task groups",
        "vso.taskgroups_write": "Grants the ability to read and create task groups"
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}