{
  "swagger": "2.0",
  "info": {
    "title": "WorkItemTracking",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1-preview"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Artifact Link Types"
    },
    {
      "name": "Artifact Uri Query"
    },
    {
      "name": "Attachments",
      "description": "Create and get attachments associated with work items."
    },
    {
      "name": "Classification Nodes"
    },
    {
      "name": "Comments",
      "description": "Work item comments controller"
    },
    {
      "name": "Fields"
    },
    {
      "name": "Queries",
      "description": "The queries in a team project are organized in folders.\n\nA sample structure of queries and folders might appear as shown here.\n\n* **My Queries**\n* **Shared Queries**\n  * Feedback (Query)\n    * **Current Sprint**\n      * Blocked Tasks (Query)\n      * Open Impediments (Query)\n      * Test Cases (Query)\n      * Unfinished Work (Query)\n      * Work in Progress (Query)"
    },
    {
      "name": "Recyclebin",
      "description": "The controller that services request for Recycle bin"
    },
    {
      "name": "Revisions",
      "description": "The controller that services requests for Work Item Revisions"
    },
    {
      "name": "Templates"
    },
    {
      "name": "Updates",
      "description": "The controller that services the requests for Work Item Updates"
    },
    {
      "name": "Wiql",
      "description": "The WIQL API is used to run a query given the WIQL text or a saved query ID."
    },
    {
      "name": "Work Item Icons",
      "description": "Discover the list of work item icons and view individual icons."
    },
    {
      "name": "Work Item Links",
      "description": "This API provides access to all work item links in your project or collection and allows you to build a warehouse.\n\nThe response of the API contains a batch of work item links (\"values\"), a URL to the next batch of work item links (\"nextLink\") and a boolean that tells you whether you have read all currently available work item links (\"isLastBatch\").\n\nThe workflow for building your warehouse is as follows:\n  1. Make a request to the API without providing a waterma[...]"
    },
    {
      "name": "Work Item Relation Types"
    },
    {
      "name": "Work Item Revisions",
      "description": "This API provides access to all work item revisions in your project or collection and allows you to build a warehouse.\n\nThe response of the API contains a batch of work item revisions(\"values\"), a URL to the next batch of work item revisions(\"nextLink\") and a boolean that tells you whether you have read all currently available work item revisions(\"isLastBatch\").\n\nThe workflow for building your warehouse is as follows:\n1. Make a request to the API without providin[...]"
    },
    {
      "name": "Work Items",
      "description": "The controller that services CRUD request for Work Items"
    },
    {
      "name": "Work Item Transitions",
      "description": "Currently only for the single GetWorkItemNextStatesOnCheckinAction that returns the next state if the work item is checked in."
    },
    {
      "name": "Work Item Type Categories",
      "description": "The controller that services the requests for Work Item Type Categories."
    },
    {
      "name": "Work Item Types",
      "description": "The controller that services the requests for Work Item Types"
    },
    {
      "name": "Work Item Types Field",
      "description": "The controller that services the requests for Work Item Type Fields"
    },
    {
      "name": "Work Item Type States",
      "description": "The controller that services the requests for states of Work Item Types."
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/wit/artifactlinktypes": {
      "get": {
        "tags": [
          "Artifact Link Types"
        ],
        "description": "Get the list of work item tracking outbound artifact link types.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/artifacturiquery": {
      "post": {
        "tags": [
          "Artifact Uri Query"
        ],
        "description": "Queries work items linked to a given list of artifact URI.",
        "operationId": "Query",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments": {
      "post": {
        "tags": [
          "Attachments"
        ],
        "description": "Uploads an attachment.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments/{id}": {
      "get": {
        "tags": [
          "Attachments"
        ],
        "description": "Downloads an attachment.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemicons": {
      "get": {
        "tags": [
          "Work Item Icons"
        ],
        "description": "Get a list of all work item icons.",
        "operationId": "List"
      }
    },
    "/_apis/wit/workitemicons/{icon}": {
      "get": {
        "tags": [
          "Work Item Icons"
        ],
        "description": "Get a work item icon given the friendly name and icon color.",
        "operationId": "Get"
      }
    },
    "/_apis/wit/workitemrelationtypes": {
      "get": {
        "tags": [
          "Work Item Relation Types"
        ],
        "description": "Gets the work item relation types.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemrelationtypes/{relation}": {
      "get": {
        "tags": [
          "Work Item Relation Types"
        ],
        "description": "Gets the work item relation type definition.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems": {
      "get": {
        "tags": [
          "Work Items"
        ],
        "description": "Returns a list of work items.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems/{id}": {
      "delete": {
        "tags": [
          "Work Items"
        ],
        "description": "Deletes the specified work item and sends it to the Recycle Bin, so that it can be restored back, if required. Optionally, if the destroy parameter has been set to true, it destroys the work item permanently.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Work Items"
        ],
        "description": "Returns a single work item.",
        "operationId": "Get Work Item",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Work Items"
        ],
        "description": "Updates a single work item.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments": {
      "get": {
        "tags": [
          "Comments"
        ],
        "description": "Gets the specified number of comments for a work item from the specified revision.",
        "operationId": "Get Comments",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments/{revision}": {
      "get": {
        "tags": [
          "Comments"
        ],
        "description": "Gets a comment for a work item at the specified revision.",
        "operationId": "Get Comment",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "Returns the list of fully hydrated work item revisions, paged.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions/{revisionNumber}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "Returns a fully hydrated work item for the requested revision",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates": {
      "get": {
        "tags": [
          "Updates"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates/{updateNumber}": {
      "get": {
        "tags": [
          "Updates"
        ],
        "description": "Returns a single update for a work item",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemtransitions": {
      "get": {
        "tags": [
          "Work Item Transitions"
        ],
        "description": "Returns the next state on the given work item IDs.",
        "operationId": "List"
      }
    },
    "/{project}/_apis/wit/classificationnodes": {
      "get": {
        "tags": [
          "Classification Nodes"
        ],
        "description": "Gets root classification nodes under the project.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/classificationnodes/{structureGroup}/{*path}": {
      "post": {
        "tags": [
          "Classification Nodes"
        ],
        "description": "Create new or update an existing classification node.",
        "operationId": "Create Or Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Classification Nodes"
        ],
        "description": "Delete an existing classification node.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Classification Nodes"
        ],
        "description": "Gets the classification node for a given node path.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Classification Nodes"
        ],
        "description": "Update an existing classification node.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields": {
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Returns information for all fields.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields/{fieldNameOrRefName}": {
      "delete": {
        "tags": [
          "Fields"
        ],
        "description": "Deletes the field.",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Gets information on a specific field.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Fields"
        ],
        "description": "Updates the field.",
        "operationId": "Update"
      }
    },
    "/{project}/_apis/wit/queries": {
      "get": {
        "tags": [
          "Queries"
        ],
        "description": "Gets the root queries and their children",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/queries/{query}": {
      "post": {
        "tags": [
          "Queries"
        ],
        "description": "Creates a query, or moves a query.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Queries"
        ],
        "description": "Delete a query or a folder",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queries"
        ],
        "description": "Retrieves an individual query and its children",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Queries"
        ],
        "description": "Update a query or a folder. This allows you to update, rename and move queries and folders.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin": {
      "get": {
        "tags": [
          "Recyclebin"
        ],
        "description": "Gets a list of the IDs and the URLs of the deleted the work items in the Recycle Bin.",
        "operationId": "Get Deleted Work Item References",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin/{id}": {
      "delete": {
        "tags": [
          "Recyclebin"
        ],
        "description": "Destroys the specified work item permanently from the Recycle Bin. This action can not be undone.",
        "operationId": "Destroy Work Item",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Recyclebin"
        ],
        "description": "Gets a deleted work item from Recycle Bin.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Recyclebin"
        ],
        "description": "Restores the deleted work item from Recycle Bin.",
        "operationId": "Restore Work Item",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemlinks": {
      "get": {
        "tags": [
          "Work Item Links"
        ],
        "description": "Get a batch of work item links",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemrevisions": {
      "get": {
        "tags": [
          "Work Item Revisions"
        ],
        "description": "Get a batch of work item revisions with the option of including deleted items",
        "operationId": "Read Reporting Revisions Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Work Item Revisions"
        ],
        "description": "Get a batch of work item revisions. This request may be used if your list of fields is large enough that it may run the URL over the length limit.",
        "operationId": "Read Reporting Revisions Post",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitems/${type}": {
      "post": {
        "tags": [
          "Work Items"
        ],
        "description": "Creates a single work item.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Work Items"
        ],
        "description": "Returns a single work item from a template.",
        "operationId": "Get Work Item Template",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories": {
      "get": {
        "tags": [
          "Work Item Type Categories"
        ],
        "description": "Returns a the deltas between work item revisions.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories/{category}": {
      "get": {
        "tags": [
          "Work Item Type Categories"
        ],
        "description": "Returns a the deltas between work item revisions.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes": {
      "get": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Returns the list of work item types",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}": {
      "get": {
        "tags": [
          "Work Item Types"
        ],
        "description": "Returns a work item type definition.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/fields/{field}": {
      "get": {
        "tags": [
          "Work Item Types Field"
        ],
        "description": "Returns the dependent fields for the corresponding workitem type and fieldname.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/states": {
      "get": {
        "tags": [
          "Work Item Type States"
        ],
        "description": "Returns the state names and colors for a work item type.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates": {
      "post": {
        "tags": [
          "Templates"
        ],
        "description": "Creates a template",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets template",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates/{templateId}": {
      "delete": {
        "tags": [
          "Templates"
        ],
        "description": "Deletes the template with given id",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets the template with specified id",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Templates"
        ],
        "description": "Replace template contents",
        "operationId": "Replace Template",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql": {
      "post": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given its WIQL.",
        "operationId": "Query By Wiql",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql/{id}": {
      "head": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given the query ID.",
        "operationId": "Get"
      },
      "get": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given the query ID.",
        "operationId": "Query By Id",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks.",
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}