{
  "swagger": "2.0",
  "info": {
    "title": "Work",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1-preview"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Backlogconfiguration"
    },
    {
      "name": "Boardcolumns"
    },
    {
      "name": "Boardparents"
    },
    {
      "name": "Boardrows"
    },
    {
      "name": "Boards"
    },
    {
      "name": "Boardusersettings"
    },
    {
      "name": "Capacities"
    },
    {
      "name": "Cardrulesettings"
    },
    {
      "name": "Cardsettings"
    },
    {
      "name": "Charts"
    },
    {
      "name": "Columns"
    },
    {
      "name": "Deliverytimeline"
    },
    {
      "name": "Iterations"
    },
    {
      "name": "Plans",
      "description": "Controller for the Scaled Agile plans REST API"
    },
    {
      "name": "Processconfiguration"
    },
    {
      "name": "Rows"
    },
    {
      "name": "Teamdaysoff"
    },
    {
      "name": "Teamfieldvalues"
    },
    {
      "name": "Teamsettings"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/{project}/_apis/work/boardcolumns": {
      "get": {
        "tags": [
          "Boardcolumns"
        ],
        "description": "Get available board columns in a project",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boardrows": {
      "get": {
        "tags": [
          "Boardrows"
        ],
        "description": "Get available board rows in a project",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/plans": {
      "post": {
        "tags": [
          "Plans"
        ],
        "description": "Add a new plan for the team",
        "operationId": "Create"
      },
      "get": {
        "tags": [
          "Plans"
        ],
        "description": "Get the information for all the plans configured for the given team",
        "operationId": "List"
      }
    },
    "/{project}/_apis/work/plans/{id}": {
      "delete": {
        "tags": [
          "Plans"
        ],
        "description": "Delete the specified plan",
        "operationId": "Delete"
      },
      "get": {
        "tags": [
          "Plans"
        ],
        "description": "Get the information for the specified plan",
        "operationId": "Get"
      },
      "put": {
        "tags": [
          "Plans"
        ],
        "description": "Update the information for the specified plan",
        "operationId": "Update"
      }
    },
    "/{project}/_apis/work/plans/{id}/deliverytimeline": {
      "get": {
        "tags": [
          "Deliverytimeline"
        ],
        "description": "Get Delivery View Data",
        "operationId": "Get"
      }
    },
    "/{project}/_apis/work/processconfiguration": {
      "get": {
        "tags": [
          "Processconfiguration"
        ],
        "description": "Get process configuration",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/backlogconfiguration": {
      "get": {
        "tags": [
          "Backlogconfiguration"
        ],
        "description": "Gets backlog configuration for a team",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards": {
      "get": {
        "tags": [
          "Boards"
        ],
        "description": "Get boards",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/boardusersettings": {
      "get": {
        "tags": [
          "Boardusersettings"
        ],
        "description": "Get board user settings for a board id",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Boardusersettings"
        ],
        "description": "Update board user settings for the board id\n\nWe don't want stakeholders to update board settings (currently just autorefresh). The BacklogManagement feature check validates this.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardrulesettings": {
      "get": {
        "tags": [
          "Cardrulesettings"
        ],
        "description": "Get board card Rule settings for the board id or board by name",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Cardrulesettings"
        ],
        "description": "Update board card Rule settings for the board id or board by name",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardsettings": {
      "get": {
        "tags": [
          "Cardsettings"
        ],
        "description": "Get board card settings for the board id or board by name",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Cardsettings"
        ],
        "description": "Update board card settings for the board id or board by name",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts": {
      "get": {
        "tags": [
          "Charts"
        ],
        "description": "Get board charts",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts/{name}": {
      "get": {
        "tags": [
          "Charts"
        ],
        "description": "Get a board chart",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Charts"
        ],
        "description": "Update a board chart",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/columns": {
      "get": {
        "tags": [
          "Columns"
        ],
        "description": "Get columns on a board",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Columns"
        ],
        "description": "Update columns on a board",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/rows": {
      "get": {
        "tags": [
          "Rows"
        ],
        "description": "Get rows on a board",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Rows"
        ],
        "description": "Update rows on a board",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{id}": {
      "get": {
        "tags": [
          "Boards"
        ],
        "description": "Get board",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Boards"
        ],
        "description": "Update board options",
        "operationId": "Set Board Options",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/boardparents": {
      "get": {
        "tags": [
          "Boardparents"
        ],
        "description": "Returns the list of parent field filter model for the given list of workitem ids",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings": {
      "get": {
        "tags": [
          "Teamsettings"
        ],
        "description": "Get a team's settings",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamsettings"
        ],
        "description": "Update a team's settings",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations": {
      "get": {
        "tags": [
          "Iterations"
        ],
        "description": "Get a team's iterations using timeframe filter",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Iterations"
        ],
        "description": "Add an iteration to the team",
        "operationId": "Post Team Iteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{id}": {
      "delete": {
        "tags": [
          "Iterations"
        ],
        "description": "Delete a team's iteration by iterationId",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Iterations"
        ],
        "description": "Get team's iteration by iterationId",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities": {
      "get": {
        "tags": [
          "Capacities"
        ],
        "description": "Get a team's capacity",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Capacities"
        ],
        "description": "Replace a team's capacity",
        "operationId": "Replace Capacities",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities/{teamMemberId}": {
      "get": {
        "tags": [
          "Capacities"
        ],
        "description": "Get a team member's capacity",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Capacities"
        ],
        "description": "Update a team member's capacity",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/teamdaysoff": {
      "get": {
        "tags": [
          "Teamdaysoff"
        ],
        "description": "Get team's days off for an iteration",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamdaysoff"
        ],
        "description": "Set a team's days off for an iteration",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/teamfieldvalues": {
      "get": {
        "tags": [
          "Teamfieldvalues"
        ],
        "description": "Get a collection of team field values",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamfieldvalues"
        ],
        "description": "Update team field values",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks.",
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}