{
  "swagger": "2.0",
  "info": {
    "title": "WorkItemTracking",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "artifactLinkTypes"
    },
    {
      "name": "artifactUriQuery"
    },
    {
      "name": "attachments"
    },
    {
      "name": "classificationNodes"
    },
    {
      "name": "comments"
    },
    {
      "name": "fields"
    },
    {
      "name": "queries"
    },
    {
      "name": "recyclebin"
    },
    {
      "name": "revisions"
    },
    {
      "name": "templates"
    },
    {
      "name": "updates"
    },
    {
      "name": "wiql"
    },
    {
      "name": "workItemIcons"
    },
    {
      "name": "workItemLinks"
    },
    {
      "name": "workItemRelationTypes"
    },
    {
      "name": "workItemRevisions"
    },
    {
      "name": "workItems"
    },
    {
      "name": "workItemTypeCategories"
    },
    {
      "name": "workItemTypes"
    },
    {
      "name": "workItemTypesField"
    },
    {
      "name": "workItemTypeStates"
    },
    {
      "name": "workItemTypeTemplate"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/wit/artifactlinktypes": {
      "get": {
        "tags": [
          "ArtifactLinkTypes"
        ],
        "description": "Get the workItemTracking toolTypes outboundLinks of type WorkItem",
        "operationId": "ArtifactLinkTypes_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/artifacturiquery": {
      "post": {
        "tags": [
          "ArtifactUriQuery"
        ],
        "description": "Gets the results of the work item ids linked to the artifact uri",
        "operationId": "ArtifactUriQuery_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments": {
      "post": {
        "tags": [
          "Attachments"
        ],
        "description": "Creates an attachment.",
        "operationId": "Attachments_Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments/{id}": {
      "get": {
        "tags": [
          "Attachments"
        ],
        "description": "Returns an attachment",
        "operationId": "Attachments_GetAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemicons": {
      "get": {
        "tags": [
          "WorkItemIcons"
        ],
        "description": "Get a list of all work item icons.",
        "operationId": "WorkItemIcons_List"
      }
    },
    "/_apis/wit/workitemicons/{icon}": {
      "get": {
        "tags": [
          "WorkItemIcons"
        ],
        "description": "Get a work item icon given the friendly name and icon color.",
        "operationId": "WorkItemIcons_GetWorkItemIconJson"
      }
    },
    "/_apis/wit/workitemrelationtypes": {
      "get": {
        "tags": [
          "WorkItemRelationTypes"
        ],
        "description": "Gets the work item relation types.",
        "operationId": "WorkItemRelationTypes_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemrelationtypes/{relation}": {
      "get": {
        "tags": [
          "WorkItemRelationTypes"
        ],
        "description": "Gets the work item relation types.",
        "operationId": "WorkItemRelationTypes_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems": {
      "get": {
        "tags": [
          "WorkItems"
        ],
        "description": "Returns a list of work items",
        "operationId": "WorkItems_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems/{id}": {
      "delete": {
        "tags": [
          "WorkItems"
        ],
        "description": "",
        "operationId": "WorkItems_Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "WorkItems"
        ],
        "description": "Returns a single work item",
        "operationId": "WorkItems_GetWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "WorkItems"
        ],
        "description": "Updates a single work item",
        "operationId": "WorkItems_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments": {
      "get": {
        "tags": [
          "Comments"
        ],
        "description": "Returns specified number of comments for a work item from the specified revision",
        "operationId": "Comments_GetComments",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments/{revision}": {
      "get": {
        "tags": [
          "Comments"
        ],
        "description": "Returns comment for a work item at the specified revision",
        "operationId": "Comments_GetComment",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "Returns the list of fully hydrated work item revisions, paged.",
        "operationId": "Revisions_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions/{revisionNumber}": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "Returns a fully hydrated work item for the requested revision",
        "operationId": "Revisions_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates": {
      "get": {
        "tags": [
          "Updates"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "Updates_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates/{updateNumber}": {
      "get": {
        "tags": [
          "Updates"
        ],
        "description": "Returns a single update for a work item",
        "operationId": "Updates_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/classificationnodes": {
      "get": {
        "tags": [
          "ClassificationNodes"
        ],
        "description": "",
        "operationId": "ClassificationNodes_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/classificationnodes/{structureGroup}/{*path}": {
      "post": {
        "tags": [
          "ClassificationNodes"
        ],
        "description": "",
        "operationId": "ClassificationNodes_Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ClassificationNodes"
        ],
        "description": "",
        "operationId": "ClassificationNodes_Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ClassificationNodes"
        ],
        "description": "",
        "operationId": "ClassificationNodes_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ClassificationNodes"
        ],
        "description": "",
        "operationId": "ClassificationNodes_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields": {
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Returns information for all fields.",
        "operationId": "Fields_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields/{fieldNameOrRefName}": {
      "delete": {
        "tags": [
          "Fields"
        ],
        "description": "",
        "operationId": "Fields_Delete"
      },
      "get": {
        "tags": [
          "Fields"
        ],
        "description": "Gets information on a specific field.",
        "operationId": "Fields_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Fields"
        ],
        "description": "",
        "operationId": "Fields_Update"
      }
    },
    "/{project}/_apis/wit/queries": {
      "get": {
        "tags": [
          "Queries"
        ],
        "description": "Gets the root queries and their children",
        "operationId": "Queries_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/queries/{query}": {
      "post": {
        "tags": [
          "Queries"
        ],
        "description": "Creates a query, or moves a query.",
        "operationId": "Queries_Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Queries"
        ],
        "description": "Delete a query or a folder",
        "operationId": "Queries_Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queries"
        ],
        "description": "Retrieves an individual query and its children",
        "operationId": "Queries_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Queries"
        ],
        "description": "Update a query or a folder. This allows you to update, rename and move queries and folders.",
        "operationId": "Queries_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin": {
      "get": {
        "tags": [
          "Recyclebin"
        ],
        "description": "",
        "operationId": "Recyclebin_GetDeletedWorkItemReferences",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin/{id}": {
      "delete": {
        "tags": [
          "Recyclebin"
        ],
        "description": "",
        "operationId": "Recyclebin_DestroyWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Recyclebin"
        ],
        "description": "",
        "operationId": "Recyclebin_Get",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Recyclebin"
        ],
        "description": "",
        "operationId": "Recyclebin_RestoreWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemlinks": {
      "get": {
        "tags": [
          "WorkItemLinks"
        ],
        "description": "Get a batch of work item links",
        "operationId": "WorkItemLinks_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemrevisions": {
      "get": {
        "tags": [
          "WorkItemRevisions"
        ],
        "description": "Get a batch of work item revisions with the option of including deleted items",
        "operationId": "WorkItemRevisions_ReadReportingRevisionsGet",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "WorkItemRevisions"
        ],
        "description": "Get a batch of work item revisions. This request may be used if your list of fields is large enough that it may run the URL over the length limit.",
        "operationId": "WorkItemRevisions_ReadReportingRevisionsPost",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitems/${type}": {
      "post": {
        "tags": [
          "WorkItems"
        ],
        "description": "Creates a single work item",
        "operationId": "WorkItems_Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "WorkItems"
        ],
        "description": "Returns a single work item from a template",
        "operationId": "WorkItems_GetWorkItemTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories": {
      "get": {
        "tags": [
          "WorkItemTypeCategories"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "WorkItemTypeCategories_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories/{category}": {
      "get": {
        "tags": [
          "WorkItemTypeCategories"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "WorkItemTypeCategories_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes": {
      "get": {
        "tags": [
          "WorkItemTypes"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "WorkItemTypes_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}": {
      "get": {
        "tags": [
          "WorkItemTypes"
        ],
        "description": "Returns a the deltas between work item revisions",
        "operationId": "WorkItemTypes_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/fields/{field}": {
      "get": {
        "tags": [
          "WorkItemTypesField"
        ],
        "description": "Returns the dependent fields for the corresponding workitem type and fieldname",
        "operationId": "WorkItemTypesField_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/states": {
      "get": {
        "tags": [
          "WorkItemTypeStates"
        ],
        "description": "Returns the state names and colors for a work item type",
        "operationId": "WorkItemTypeStates_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypetemplate": {
      "post": {
        "tags": [
          "WorkItemTypeTemplate"
        ],
        "description": "Add/updates a work item type",
        "operationId": "WorkItemTypeTemplate_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypetemplate/{type}": {
      "get": {
        "tags": [
          "WorkItemTypeTemplate"
        ],
        "description": "Export work item type",
        "operationId": "WorkItemTypeTemplate_ExportWorkItemTypeDefinition",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates": {
      "post": {
        "tags": [
          "Templates"
        ],
        "description": "Creates a template",
        "operationId": "Templates_Create",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets template",
        "operationId": "Templates_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates/{templateId}": {
      "delete": {
        "tags": [
          "Templates"
        ],
        "description": "Deletes the template with given id",
        "operationId": "Templates_Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets the template with specified id",
        "operationId": "Templates_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Templates"
        ],
        "description": "Replace template contents",
        "operationId": "Templates_ReplaceTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql": {
      "post": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given its WIQL.",
        "operationId": "Wiql_QueryByWiql",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql/{id}": {
      "head": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given the query ID.",
        "operationId": "Wiql_Get"
      },
      "get": {
        "tags": [
          "Wiql"
        ],
        "description": "Gets the results of the query given the query ID.",
        "operationId": "Wiql_QueryById",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks.",
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}