{
  "swagger": "2.0",
  "info": {
    "title": "CodeReview",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "attachments"
    },
    {
      "name": "changes"
    },
    {
      "name": "comments"
    },
    {
      "name": "contents"
    },
    {
      "name": "contentsBatch"
    },
    {
      "name": "iterations"
    },
    {
      "name": "likes"
    },
    {
      "name": "properties"
    },
    {
      "name": "reviewers"
    },
    {
      "name": "reviews"
    },
    {
      "name": "reviewsBatch"
    },
    {
      "name": "settings"
    },
    {
      "name": "share"
    },
    {
      "name": "statuses"
    },
    {
      "name": "threads"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/codereview/reviews": {
      "get": {
        "tags": [
          "reviews"
        ],
        "summary": "GetReviews",
        "description": "Query reviews based on search criteria. When making subsequent requests that include continuation tokens, be sure to pass the same search criteria. Otherwise the subsequent requests may return unexpected results.",
        "operationId": "getReviews",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews": {
      "get": {
        "tags": [
          "reviews"
        ],
        "summary": "GetReviews",
        "description": "Query reviews based on search criteria. When making subsequent requests that include continuation tokens, be sure to pass the same search criteria. Otherwise the subsequent requests may return unexpected results.",
        "operationId": "getReviews",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "reviews"
        ],
        "summary": "CreateReview",
        "description": "",
        "operationId": "createReview",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}": {
      "delete": {
        "tags": [
          "reviews"
        ],
        "summary": "DeleteReview",
        "description": "",
        "operationId": "deleteReview",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "reviews"
        ],
        "summary": "GetReview",
        "description": "",
        "operationId": "getReview",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "reviews"
        ],
        "summary": "ReplaceReview",
        "description": "",
        "operationId": "replaceReview",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "reviews"
        ],
        "summary": "UpdateReview",
        "description": "",
        "operationId": "updateReview",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/attachments": {
      "post": {
        "tags": [
          "attachments"
        ],
        "summary": "AddAttachment",
        "description": "",
        "operationId": "addAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetAttachments",
        "description": "",
        "operationId": "getAttachments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/attachments/{attachmentId}": {
      "delete": {
        "tags": [
          "attachments"
        ],
        "summary": "DeleteAttachment",
        "description": "",
        "operationId": "deleteAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetAttachment",
        "description": "",
        "operationId": "getAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/contents": {
      "get": {
        "tags": [
          "contents"
        ],
        "summary": "DownloadContent",
        "description": "",
        "operationId": "downloadContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "contents"
        ],
        "summary": "UploadContent",
        "description": "",
        "operationId": "uploadContent",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/contentsbatch": {
      "post": {
        "tags": [
          "contentsBatch"
        ],
        "summary": "DownloadContentsBatchZip",
        "description": "Fetch file contents based on criteria. Criteria can be a set of iteration ids or content hashes. POST /_apis/codereview/reviews/{id}/contentsBatch",
        "operationId": "downloadContentsBatchZip",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations": {
      "post": {
        "tags": [
          "iterations"
        ],
        "summary": "CreateIteration",
        "description": "",
        "operationId": "createIteration",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetIterations",
        "description": "",
        "operationId": "getIterations",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetIteration",
        "description": "",
        "operationId": "getIteration",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "iterations"
        ],
        "summary": "UpdateIteration",
        "description": "",
        "operationId": "updateIteration",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetChanges",
        "description": "",
        "operationId": "getChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/changes/{changeId}/{fileTarget}": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetContent",
        "description": "",
        "operationId": "getContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/properties": {
      "patch": {
        "tags": [
          "properties"
        ],
        "summary": "CreateOrUpdateIterationProperties",
        "description": "Create or update review properties collection. PATCH /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/properties The patch operation can be add, replace or remove. For add operation, the path can be empty. If the path is empty, the value must be a list of key value pairs. For replace operation, the path cannot be empty. If the path does not exist, the property will be added to the collection. For remove operation, the path cannot be empty. If the path does no[...]",
        "operationId": "createOrUpdateIterationProperties",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "properties"
        ],
        "summary": "GetIterationProperties",
        "description": "Get iteration properties collection. GET /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/properties",
        "operationId": "getIterationProperties",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateIterationStatus",
        "description": "Create an iteration status. POST /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses/{statusId}",
        "operationId": "createIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetIterationStatuses",
        "description": "Get all the statuses associated with an iteration. GET /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses",
        "operationId": "getIterationStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetIterationStatus",
        "description": "Get the specific iteration status. GET /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses/{statusId}",
        "operationId": "getIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "statuses"
        ],
        "summary": "UpdateIterationStatus",
        "description": "Update an iteration status. PATCH /_apis/codereview/reviews/{reviewId}/iterations/{iterationId}/statuses/{statusId}",
        "operationId": "updateIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/properties": {
      "patch": {
        "tags": [
          "properties"
        ],
        "summary": "CreateOrUpdateReviewProperties",
        "description": "Create or update review properties collection. PATCH /_apis/codereview/reviews/{reviewId}/properties The patch operation can be add, replace or remove. For add operation, the path can be empty. If the path is empty, the value must be a list of key value pairs. For replace operation, the path cannot be empty. If the path does not exist, the property will be added to the collection. For remove operation, the path cannot be empty. If the path does not exist, no action will b[...]",
        "operationId": "createOrUpdateReviewProperties",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "properties"
        ],
        "summary": "GetReviewProperties",
        "description": "Get review properties collection. GET /_apis/codereview/reviews/{reviewId}/properties",
        "operationId": "getReviewProperties",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/reviewers": {
      "post": {
        "tags": [
          "reviewers"
        ],
        "summary": "AddReviewers",
        "description": "",
        "operationId": "addReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "reviewers"
        ],
        "summary": "GetReviewers",
        "description": "",
        "operationId": "getReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/reviewers/{reviewerId}": {
      "delete": {
        "tags": [
          "reviewers"
        ],
        "summary": "DeleteReviewer",
        "description": "",
        "operationId": "deleteReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "reviewers"
        ],
        "summary": "ReplaceReviewer",
        "description": "",
        "operationId": "replaceReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/share": {
      "post": {
        "tags": [
          "share"
        ],
        "summary": "ShareReview",
        "description": "",
        "operationId": "shareReview",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateReviewStatus",
        "description": "Create a review status. POST /_apis/codereview/reviews/{reviewId}/statuses",
        "operationId": "createReviewStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetReviewStatuses",
        "description": "Get all the statuses associated with a review. GET /_apis/codereview/reviews/{reviewId}/statuses",
        "operationId": "getReviewStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetReviewStatus",
        "description": "Get the specific review status. GET /_apis/codereview/reviews/{reviewId}/statuses/{statusId}",
        "operationId": "getReviewStatus",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "statuses"
        ],
        "summary": "UpdateReviewStatus",
        "description": "Update a review status. PATCH /_apis/codereview/reviews/{reviewId}/statuses/{statusId}",
        "operationId": "updateReviewStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads": {
      "post": {
        "tags": [
          "threads"
        ],
        "summary": "CreateThread",
        "description": "Create a review comment thread. POST /_apis/CodeReview/reviews/{id}/Threads",
        "operationId": "createThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "threads"
        ],
        "summary": "GetThreads",
        "description": "Get all review comment threads of a review. GET /_apis/CodeReview/reviews/{id}/Threads/ When modifiedSince parameter is passed, fetch threads of a review that were modified after modifiedSince timestamp.",
        "operationId": "getThreads",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads/{threadId}": {
      "get": {
        "tags": [
          "threads"
        ],
        "summary": "GetThread",
        "description": "Get a review comment thread by id for a review. Return 304 if comment thread hasn't modified based on ifModifiedSince header. GET /_apis/CodeReview/reviews/{id}/Threads/{threadId}",
        "operationId": "getThread",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "threads"
        ],
        "summary": "UpdateThread",
        "description": "",
        "operationId": "updateThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "comments"
        ],
        "summary": "CreateComment",
        "description": "Create a discussion comment. POST /_apis/CodeReview/reviews/{id}/Threads/{threadId}/comments",
        "operationId": "createComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "comments"
        ],
        "summary": "GetComments",
        "description": "Read all comments for a review comment thread by id for a review. GET /_apis/CodeReview/reviews/{id}/Threads/{threadId}/comments",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "comments"
        ],
        "summary": "DeleteComment",
        "description": "Soft delete a comment. Deleted(Withdrawn) comments are always returned. Use IsDeleted flag in each comment to detect if its a deleted comment, Delete /_apis/CodeReview/reviews/{id}/Threads/{threadId}/comments/{commentId}",
        "operationId": "deleteComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "comments"
        ],
        "summary": "GetComment",
        "description": "Get a comment for a review comment thread by id of a review based on commentId. GET /_apis/CodeReview/reviews/{id}/Threads/{threadId}/comments/{commentId}",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "comments"
        ],
        "summary": "UpdateComment",
        "description": "Update a comment. Patch /_apis/CodeReview/reviews/{id}/Threads/{threadId}/comments/{commentId}",
        "operationId": "updateComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads/{threadId}/comments/{commentId}/likes": {
      "post": {
        "tags": [
          "likes"
        ],
        "summary": "CreateLike",
        "description": "Like a comment in a thread for a review. POST /_apis/CodeReview/reviews/{id}/threads/{id}/comments/{commentId}/likes",
        "operationId": "createLike",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "likes"
        ],
        "summary": "GetLikes",
        "description": "Get all likes of a comment in a thread for a review. GET /_apis/CodeReview/reviews/{id}/threads/{id}/comments/{commentId}/likes",
        "operationId": "getLikes",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviews/{reviewId}/threads/{threadId}/comments/{commentId}/likes/{userId}": {
      "delete": {
        "tags": [
          "likes"
        ],
        "summary": "DeleteLike",
        "description": "Withdraw like of a comment in a thread for a review. DELETE /_apis/CodeReview/reviews/{id}/threads/{id}/comments/{commentId}/likes/{userId}",
        "operationId": "deleteLike",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/reviewsbatch": {
      "post": {
        "tags": [
          "reviewsBatch"
        ],
        "summary": "GetReviewsBatch",
        "description": "Query reviews by sourceArtifactIds. POST /_apis/codereview/reviewsBatch",
        "operationId": "getReviewsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/codereview/settings": {
      "post": {
        "tags": [
          "settings"
        ],
        "summary": "CreateReviewSettings",
        "description": "",
        "operationId": "createReviewSettings",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "settings"
        ],
        "summary": "GetReviewSettings",
        "description": "",
        "operationId": "getReviewSettings",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "settings"
        ],
        "summary": "UpdateReviewSettings",
        "description": "",
        "operationId": "updateReviewSettings",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.code": "Grants the ability to read source code and metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to get notified about version control events via service hooks.",
        "vso.code_write": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage pull requests and code reviews and to receive notifications about version control events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}