{
  "swagger": "2.0",
  "info": {
    "title": "Core",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "connectedServices"
    },
    {
      "name": "identityMru"
    },
    {
      "name": "members"
    },
    {
      "name": "processes"
    },
    {
      "name": "projectCollections"
    },
    {
      "name": "projectHistory"
    },
    {
      "name": "projects"
    },
    {
      "name": "proxies"
    },
    {
      "name": "teams"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/core/identitymru/{mruName}": {
      "post": {
        "tags": [
          "identityMru"
        ],
        "summary": "CreateIdentityMru",
        "description": "",
        "operationId": "createIdentityMru"
      },
      "delete": {
        "tags": [
          "identityMru"
        ],
        "summary": "DeleteIdentityMru",
        "description": "",
        "operationId": "deleteIdentityMru"
      },
      "get": {
        "tags": [
          "identityMru"
        ],
        "summary": "GetIdentityMru",
        "description": "",
        "operationId": "getIdentityMru"
      },
      "patch": {
        "tags": [
          "identityMru"
        ],
        "summary": "UpdateIdentityMru",
        "description": "",
        "operationId": "updateIdentityMru"
      }
    },
    "/_apis/process/processes": {
      "get": {
        "tags": [
          "processes"
        ],
        "summary": "GetProcesses",
        "description": "",
        "operationId": "getProcesses",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/process/processes/{processId}": {
      "get": {
        "tags": [
          "processes"
        ],
        "summary": "GetProcessById",
        "description": "Retrieve process by id",
        "operationId": "getProcessById",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/projectcollections": {
      "get": {
        "tags": [
          "projectCollections"
        ],
        "summary": "GetProjectCollections",
        "description": "Get project collection references for this application.",
        "operationId": "getProjectCollections",
        "security": [
          {
            "oauth2": [
              "vso.profile"
            ]
          }
        ]
      }
    },
    "/_apis/projectcollections/{collectionId}": {
      "get": {
        "tags": [
          "projectCollections"
        ],
        "summary": "GetProjectCollection",
        "description": "Get project collection with the specified id or name.",
        "operationId": "getProjectCollection",
        "security": [
          {
            "oauth2": [
              "vso.profile"
            ]
          }
        ]
      }
    },
    "/_apis/projecthistory": {
      "get": {
        "tags": [
          "projectHistory"
        ],
        "summary": "GetProjectHistory",
        "description": "",
        "operationId": "getProjectHistory"
      }
    },
    "/_apis/projects": {
      "get": {
        "tags": [
          "projects"
        ],
        "summary": "GetProjects",
        "description": "Get project references with the specified state",
        "operationId": "getProjects",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "projects"
        ],
        "summary": "QueueCreateProject",
        "description": "Queue a project creation.",
        "operationId": "queueCreateProject",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}": {
      "get": {
        "tags": [
          "projects"
        ],
        "summary": "GetProject",
        "description": "Get project with the specified id or name, optionally including capabilities.",
        "operationId": "getProject",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "projects"
        ],
        "summary": "QueueDeleteProject",
        "description": "Queue a project deletion.",
        "operationId": "queueDeleteProject",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "projects"
        ],
        "summary": "UpdateProject",
        "description": "Update an existing project's name, abbreviation, or description.",
        "operationId": "updateProject",
        "security": [
          {
            "oauth2": [
              "vso.project_write"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/connectedservices": {
      "post": {
        "tags": [
          "connectedServices"
        ],
        "summary": "CreateConnectedService",
        "description": "",
        "operationId": "createConnectedService",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "connectedServices"
        ],
        "summary": "GetConnectedServices",
        "description": "",
        "operationId": "getConnectedServices",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/connectedservices/{name}": {
      "get": {
        "tags": [
          "connectedServices"
        ],
        "summary": "GetConnectedServiceDetails",
        "description": "",
        "operationId": "getConnectedServiceDetails",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams": {
      "post": {
        "tags": [
          "teams"
        ],
        "summary": "CreateTeam",
        "description": "Creates a team",
        "operationId": "createTeam",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "teams"
        ],
        "summary": "GetTeams",
        "description": "",
        "operationId": "getTeams",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams/{teamId}": {
      "delete": {
        "tags": [
          "teams"
        ],
        "summary": "DeleteTeam",
        "description": "Deletes a team",
        "operationId": "deleteTeam",
        "security": [
          {
            "oauth2": [
              "vso.project_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "teams"
        ],
        "summary": "GetTeam",
        "description": "Gets a team",
        "operationId": "getTeam",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teams"
        ],
        "summary": "UpdateTeam",
        "description": "Updates a team's name and/or description",
        "operationId": "updateTeam",
        "security": [
          {
            "oauth2": [
              "vso.project_write"
            ]
          }
        ]
      }
    },
    "/_apis/projects/{projectId}/teams/{teamId}/members": {
      "get": {
        "tags": [
          "members"
        ],
        "summary": "GetTeamMembers",
        "description": "",
        "operationId": "getTeamMembers",
        "security": [
          {
            "oauth2": [
              "vso.profile",
              "vso.project"
            ]
          }
        ]
      }
    },
    "/_apis/proxies": {
      "put": {
        "tags": [
          "proxies"
        ],
        "summary": "CreateOrUpdateProxy",
        "description": "",
        "operationId": "createOrUpdateProxy"
      },
      "delete": {
        "tags": [
          "proxies"
        ],
        "summary": "DeleteProxy",
        "description": "",
        "operationId": "deleteProxy"
      },
      "get": {
        "tags": [
          "proxies"
        ],
        "summary": "GetProxies",
        "description": "",
        "operationId": "getProxies"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.profile": "Grants the ability to read your profile, accounts, collections, projects, teams, and other top-level organizational artifacts.",
        "vso.project": "Grants the ability to read projects and teams.",
        "vso.project_manage": "Grants the ability to create, read, update, and delete projects and teams.",
        "vso.project_write": "Grants the ability to read and update projects and teams.",
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}