{
  "swagger": "2.0",
  "info": {
    "title": "Dashboard",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "dashboards"
    },
    {
      "name": "widgets"
    },
    {
      "name": "widgetTypes"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/dashboard/widgettypes": {
      "get": {
        "tags": [
          "widgetTypes"
        ],
        "summary": "GetWidgetTypes",
        "description": "Returns available widgets in alphabetical order.",
        "operationId": "getWidgetTypes"
      }
    },
    "/_apis/dashboard/widgettypes/{contributionId}": {
      "get": {
        "tags": [
          "widgetTypes"
        ],
        "summary": "GetWidgetMetadata",
        "description": "",
        "operationId": "getWidgetMetadata"
      }
    },
    "/{project}/_apis/dashboard/dashboards": {
      "post": {
        "tags": [
          "dashboards"
        ],
        "summary": "CreateDashboard",
        "description": "",
        "operationId": "createDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "dashboards"
        ],
        "summary": "GetDashboards",
        "description": "",
        "operationId": "getDashboards",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "dashboards"
        ],
        "summary": "ReplaceDashboards",
        "description": "",
        "operationId": "replaceDashboards"
      }
    },
    "/{project}/_apis/dashboard/dashboards/{dashboardId}": {
      "delete": {
        "tags": [
          "dashboards"
        ],
        "summary": "DeleteDashboard",
        "description": "",
        "operationId": "deleteDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "dashboards"
        ],
        "summary": "GetDashboard",
        "description": "",
        "operationId": "getDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "dashboards"
        ],
        "summary": "ReplaceDashboard",
        "description": "",
        "operationId": "replaceDashboard"
      }
    },
    "/{project}/_apis/dashboard/dashboards/{dashboardId}/widgets": {
      "post": {
        "tags": [
          "widgets"
        ],
        "summary": "CreateWidget",
        "description": "",
        "operationId": "createWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "widgets"
        ],
        "summary": "GetWidgets",
        "description": "",
        "operationId": "getWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "widgets"
        ],
        "summary": "ReplaceWidgets",
        "description": "",
        "operationId": "replaceWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "widgets"
        ],
        "summary": "UpdateWidgets",
        "description": "",
        "operationId": "updateWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/dashboard/dashboards/{dashboardId}/widgets/{widgetId}": {
      "delete": {
        "tags": [
          "widgets"
        ],
        "summary": "DeleteWidget",
        "description": "",
        "operationId": "deleteWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "widgets"
        ],
        "summary": "GetWidget",
        "description": "",
        "operationId": "getWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "widgets"
        ],
        "summary": "ReplaceWidget",
        "description": "",
        "operationId": "replaceWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "widgets"
        ],
        "summary": "UpdateWidget",
        "description": "",
        "operationId": "updateWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards": {
      "post": {
        "tags": [
          "dashboards"
        ],
        "summary": "CreateDashboard",
        "description": "",
        "operationId": "createDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "dashboards"
        ],
        "summary": "GetDashboards",
        "description": "",
        "operationId": "getDashboards",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "dashboards"
        ],
        "summary": "ReplaceDashboards",
        "description": "",
        "operationId": "replaceDashboards"
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}": {
      "delete": {
        "tags": [
          "dashboards"
        ],
        "summary": "DeleteDashboard",
        "description": "",
        "operationId": "deleteDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "dashboards"
        ],
        "summary": "GetDashboard",
        "description": "",
        "operationId": "getDashboard",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "dashboards"
        ],
        "summary": "ReplaceDashboard",
        "description": "",
        "operationId": "replaceDashboard"
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}/widgets": {
      "post": {
        "tags": [
          "widgets"
        ],
        "summary": "CreateWidget",
        "description": "",
        "operationId": "createWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "widgets"
        ],
        "summary": "GetWidgets",
        "description": "",
        "operationId": "getWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "widgets"
        ],
        "summary": "ReplaceWidgets",
        "description": "",
        "operationId": "replaceWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "widgets"
        ],
        "summary": "UpdateWidgets",
        "description": "",
        "operationId": "updateWidgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}/widgets/{widgetId}": {
      "delete": {
        "tags": [
          "widgets"
        ],
        "summary": "DeleteWidget",
        "description": "",
        "operationId": "deleteWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "widgets"
        ],
        "summary": "GetWidget",
        "description": "",
        "operationId": "getWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "widgets"
        ],
        "summary": "ReplaceWidget",
        "description": "",
        "operationId": "replaceWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "widgets"
        ],
        "summary": "UpdateWidget",
        "description": "",
        "operationId": "updateWidget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.dashboards": "Grants the ability to read team dashboard information",
        "vso.dashboards_manage": "Grants the ability to manage team dashboard information"
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}