{
  "swagger": "2.0",
  "info": {
    "title": "ExtensionManagement",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "acquisitionOptions"
    },
    {
      "name": "acquisitionRequests"
    },
    {
      "name": "authorizations"
    },
    {
      "name": "data"
    },
    {
      "name": "extensionDataCollectionQuery"
    },
    {
      "name": "extensionStates"
    },
    {
      "name": "installedExtensionQuery"
    },
    {
      "name": "installedExtensions"
    },
    {
      "name": "installedExtensionsByName"
    },
    {
      "name": "policies"
    },
    {
      "name": "requestedExtensions"
    },
    {
      "name": "token"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/extensionmanagement/acquisitionoptions": {
      "get": {
        "tags": [
          "acquisitionOptions"
        ],
        "summary": "GetAcquisitionOptions",
        "description": "",
        "operationId": "getAcquisitionOptions",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/acquisitionrequests": {
      "post": {
        "tags": [
          "acquisitionRequests"
        ],
        "summary": "RequestAcquisition",
        "description": "",
        "operationId": "requestAcquisition",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/extensionstates": {
      "get": {
        "tags": [
          "extensionStates"
        ],
        "summary": "GetStates",
        "description": "",
        "operationId": "getStates"
      }
    },
    "/_apis/extensionmanagement/installedextensionquery": {
      "post": {
        "tags": [
          "installedExtensionQuery"
        ],
        "summary": "QueryExtensions",
        "description": "",
        "operationId": "queryExtensions"
      }
    },
    "/_apis/extensionmanagement/installedextensions": {
      "get": {
        "tags": [
          "installedExtensions"
        ],
        "summary": "GetInstalledExtensions",
        "description": "",
        "operationId": "getInstalledExtensions",
        "security": [
          {
            "oauth2": [
              "vso.extension"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "installedExtensions"
        ],
        "summary": "UpdateInstalledExtension",
        "description": "",
        "operationId": "updateInstalledExtension",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/InstalledExtensions/{publisherName}/{extensionName}/authorizations/{registrationId}": {
      "put": {
        "tags": [
          "authorizations"
        ],
        "summary": "RegisterAuthorization",
        "description": "",
        "operationId": "registerAuthorization",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/InstalledExtensions/{publisherName}/{extensionName}/data/Scopes/{scopeType}/{scopeValue}/Collections/{collectionName}/Documents": {
      "post": {
        "tags": [
          "data"
        ],
        "summary": "CreateDocumentByName",
        "description": "",
        "operationId": "createDocumentByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage",
              "vso.extension.data_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "data"
        ],
        "summary": "GetDocumentsByName",
        "description": "",
        "operationId": "getDocumentsByName",
        "security": [
          {
            "oauth2": [
              "vso.extension",
              "vso.extension.data"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "data"
        ],
        "summary": "SetDocumentByName",
        "description": "",
        "operationId": "setDocumentByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage",
              "vso.extension.data_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "data"
        ],
        "summary": "UpdateDocumentByName",
        "description": "",
        "operationId": "updateDocumentByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage",
              "vso.extension.data_write"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/InstalledExtensions/{publisherName}/{extensionName}/data/Scopes/{scopeType}/{scopeValue}/Collections/{collectionName}/Documents/{documentId}": {
      "delete": {
        "tags": [
          "data"
        ],
        "summary": "DeleteDocumentByName",
        "description": "",
        "operationId": "deleteDocumentByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage",
              "vso.extension.data_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "data"
        ],
        "summary": "GetDocumentByName",
        "description": "",
        "operationId": "getDocumentByName",
        "security": [
          {
            "oauth2": [
              "vso.extension",
              "vso.extension.data"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/InstalledExtensions/{publisherName}/{extensionName}/extensiondatacollectionquery": {
      "post": {
        "tags": [
          "extensionDataCollectionQuery"
        ],
        "summary": "QueryCollectionsByName",
        "description": "",
        "operationId": "queryCollectionsByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage",
              "vso.extension.data"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/installedextensionsbyname/{publisherName}/{extensionName}": {
      "get": {
        "tags": [
          "installedExtensionsByName"
        ],
        "summary": "GetInstalledExtensionByName",
        "description": "",
        "operationId": "getInstalledExtensionByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "installedExtensionsByName"
        ],
        "summary": "UninstallExtensionByName",
        "description": "",
        "operationId": "uninstallExtensionByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/installedextensionsbyname/{publisherName}/{extensionName}/{version}": {
      "post": {
        "tags": [
          "installedExtensionsByName"
        ],
        "summary": "InstallExtensionByName",
        "description": "",
        "operationId": "installExtensionByName",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/policies/{userId}": {
      "get": {
        "tags": [
          "policies"
        ],
        "summary": "GetPolicies",
        "description": "",
        "operationId": "getPolicies"
      }
    },
    "/_apis/extensionmanagement/requestedextensions": {
      "get": {
        "tags": [
          "requestedExtensions"
        ],
        "summary": "GetRequests",
        "description": "",
        "operationId": "getRequests",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/requestedextensions/{publisherName}/{extensionName}": {
      "patch": {
        "tags": [
          "requestedExtensions"
        ],
        "summary": "ResolveAllRequests",
        "description": "",
        "operationId": "resolveAllRequests",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/requestedextensions/{publisherName}/{extensionName}/requests/{requesterId}": {
      "patch": {
        "tags": [
          "requestedExtensions"
        ],
        "summary": "ResolveRequest",
        "description": "",
        "operationId": "resolveRequest",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/requestedextensions/{publisherName}/{extensionName}/requests/me": {
      "delete": {
        "tags": [
          "requestedExtensions"
        ],
        "summary": "DeleteRequest",
        "description": "",
        "operationId": "deleteRequest",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "requestedExtensions"
        ],
        "summary": "RequestExtension",
        "description": "",
        "operationId": "requestExtension",
        "security": [
          {
            "oauth2": [
              "vso.extension_manage"
            ]
          }
        ]
      }
    },
    "/_apis/extensionmanagement/token": {
      "get": {
        "tags": [
          "token"
        ],
        "summary": "GetToken",
        "description": "",
        "operationId": "getToken"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.extension": "Grants the ability to read installed extensions.",
        "vso.extension_manage": "Grants the ability to install, uninstall, and perform other administrative actions on installed extensions.",
        "vso.extension.data": "Grants the ability to read data (settings and documents) stored by installed extensions.",
        "vso.extension.data_write": "Grants the ability to read and write data (settings and documents) stored by installed extensions."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}