{
  "swagger": "2.0",
  "info": {
    "title": "Feed",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.0"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "feedChanges"
    },
    {
      "name": "feeds"
    },
    {
      "name": "globalPermissions"
    },
    {
      "name": "packageChanges"
    },
    {
      "name": "packages"
    },
    {
      "name": "permissions"
    },
    {
      "name": "versions"
    },
    {
      "name": "views"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/packaging/feedchanges": {
      "get": {
        "tags": [
          "feedChanges"
        ],
        "summary": "GetFeedChanges",
        "description": "",
        "operationId": "getFeedChanges",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feedchanges/{feedId}": {
      "get": {
        "tags": [
          "feedChanges"
        ],
        "summary": "GetFeedChange",
        "description": "",
        "operationId": "getFeedChange",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds": {
      "post": {
        "tags": [
          "feeds"
        ],
        "summary": "CreateFeed",
        "description": "",
        "operationId": "createFeed",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "feeds"
        ],
        "summary": "GetFeeds",
        "description": "",
        "operationId": "getFeeds",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}": {
      "delete": {
        "tags": [
          "feeds"
        ],
        "summary": "DeleteFeed",
        "description": "",
        "operationId": "deleteFeed",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "feeds"
        ],
        "summary": "GetFeed",
        "description": "",
        "operationId": "getFeed",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "feeds"
        ],
        "summary": "UpdateFeed",
        "description": "",
        "operationId": "updateFeed",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packagechanges": {
      "get": {
        "tags": [
          "packageChanges"
        ],
        "summary": "GetPackageChanges",
        "description": "",
        "operationId": "getPackageChanges",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackages",
        "description": "",
        "operationId": "getPackages",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages/{packageId}": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackage",
        "description": "",
        "operationId": "getPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions": {
      "get": {
        "tags": [
          "versions"
        ],
        "summary": "GetPackageVersions",
        "description": "",
        "operationId": "getPackageVersions",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions/{packageVersionId}": {
      "get": {
        "tags": [
          "versions"
        ],
        "summary": "GetPackageVersion",
        "description": "",
        "operationId": "getPackageVersion",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/permissions": {
      "get": {
        "tags": [
          "permissions"
        ],
        "summary": "GetFeedPermissions",
        "description": "",
        "operationId": "getFeedPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "permissions"
        ],
        "summary": "SetFeedPermissions",
        "description": "",
        "operationId": "setFeedPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views": {
      "post": {
        "tags": [
          "views"
        ],
        "summary": "CreateFeedView",
        "description": "",
        "operationId": "createFeedView",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "views"
        ],
        "summary": "GetFeedViews",
        "description": "",
        "operationId": "getFeedViews",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views/{viewId}": {
      "delete": {
        "tags": [
          "views"
        ],
        "summary": "DeleteFeedView",
        "description": "",
        "operationId": "deleteFeedView",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "views"
        ],
        "summary": "GetFeedView",
        "description": "",
        "operationId": "getFeedView",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "views"
        ],
        "summary": "UpdateFeedView",
        "description": "",
        "operationId": "updateFeedView",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/globalpermissions": {
      "get": {
        "tags": [
          "globalPermissions"
        ],
        "summary": "GetGlobalPermissions",
        "description": "",
        "operationId": "getGlobalPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "globalPermissions"
        ],
        "summary": "SetGlobalPermissions",
        "description": "",
        "operationId": "setGlobalPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.packaging_write": "Grants the ability to create and read feeds and packages.",
        "vso.packaging": "Grants the ability to read feeds and packages.",
        "vso.packaging_manage": "Grants the ability to create, read, update, and delete feeds and packages."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}