{
  "swagger": "2.0",
  "info": {
    "title": "Git",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "annotatedTags"
    },
    {
      "name": "blobs"
    },
    {
      "name": "branchStats"
    },
    {
      "name": "changes"
    },
    {
      "name": "cherryPicks"
    },
    {
      "name": "commitDiffs"
    },
    {
      "name": "commits"
    },
    {
      "name": "commitsBatch"
    },
    {
      "name": "deletedRepositories"
    },
    {
      "name": "importRequests"
    },
    {
      "name": "items"
    },
    {
      "name": "itemsBatch"
    },
    {
      "name": "pullRequestAttachments"
    },
    {
      "name": "pullRequestCommits"
    },
    {
      "name": "pullRequestConflicts"
    },
    {
      "name": "pullRequestIterationChanges"
    },
    {
      "name": "pullRequestIterations"
    },
    {
      "name": "pullRequestQuery"
    },
    {
      "name": "pullRequestReviewers"
    },
    {
      "name": "pullRequests"
    },
    {
      "name": "pullRequestShare"
    },
    {
      "name": "pullRequestStatuses"
    },
    {
      "name": "pullRequestThreadComments"
    },
    {
      "name": "pullRequestThreads"
    },
    {
      "name": "pullRequestWorkItems"
    },
    {
      "name": "pushes"
    },
    {
      "name": "refs"
    },
    {
      "name": "refsFavorites"
    },
    {
      "name": "repositories"
    },
    {
      "name": "reverts"
    },
    {
      "name": "statuses"
    },
    {
      "name": "suggestions"
    },
    {
      "name": "treeDiffs"
    },
    {
      "name": "trees"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/git/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequestById",
        "description": "Get a pull request using its ID",
        "operationId": "getPullRequestById"
      }
    },
    "/_apis/git/repositories": {
      "post": {
        "tags": [
          "repositories"
        ],
        "summary": "CreateRepository",
        "description": "Create a git repository",
        "operationId": "createRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepositories",
        "description": "Retrieve git repositories.",
        "operationId": "getRepositories",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "repositories"
        ],
        "summary": "DeleteRepository",
        "description": "Delete a git repository",
        "operationId": "deleteRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepository",
        "description": "",
        "operationId": "getRepository",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "repositories"
        ],
        "summary": "UpdateRepository",
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "updateRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlobsZip",
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "getBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlob",
        "description": "Gets a single blob.",
        "operationId": "getBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommits",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommit",
        "description": "Retrieve a particular commit.",
        "operationId": "getCommit",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetChanges",
        "description": "Retrieve changes for a particular commit.",
        "operationId": "getChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateCommitStatus",
        "description": "",
        "operationId": "createCommitStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetStatuses",
        "description": "",
        "operationId": "getStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "commitsBatch"
        ],
        "summary": "GetCommitsBatch",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommitsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "commitDiffs"
        ],
        "summary": "GetCommitDiffs",
        "description": "Get differences in committed items between two commits.",
        "operationId": "getCommitDiffs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "itemsBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "pullRequestQuery"
        ],
        "summary": "GetPullRequestQuery",
        "description": "Query for pull requests",
        "operationId": "getPullRequestQuery",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "pullRequests"
        ],
        "summary": "CreatePullRequest",
        "description": "Create a git pull request",
        "operationId": "createPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequests",
        "description": "Query for pull requests",
        "operationId": "getPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequest",
        "description": "Retrieve a pull request",
        "operationId": "getPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequests"
        ],
        "summary": "UpdatePullRequest",
        "description": "Updates a pull request",
        "operationId": "updatePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachments",
        "description": "",
        "operationId": "getAttachments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "CreateAttachment",
        "description": "Create a new attachment",
        "operationId": "createAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "DeleteAttachment",
        "description": "",
        "operationId": "deleteAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachmentContent",
        "description": "",
        "operationId": "getAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestCommits",
        "description": "Retrieve pull request's commits",
        "operationId": "getPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflicts",
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "getPullRequestConflicts",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflict",
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "getPullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "UpdatePullRequestConflict",
        "description": "Update merge conflict resolution",
        "operationId": "updatePullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIterations",
        "description": "",
        "operationId": "getPullRequestIterations",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIteration",
        "description": "",
        "operationId": "getPullRequestIteration",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "pullRequestIterationChanges"
        ],
        "summary": "GetPullRequestIterationChanges",
        "description": "",
        "operationId": "getPullRequestIterationChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestIterationCommits",
        "description": "Get the commits for an iteration.",
        "operationId": "getPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestIterationStatus",
        "description": "Create a pull request iteration status",
        "operationId": "createPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatuses",
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "getPullRequestIterationStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatus",
        "description": "Get the specific pull request iteration status.",
        "operationId": "getPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewers",
        "description": "Adds reviewers to a git pull request",
        "operationId": "createPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewers",
        "description": "Retrieve a pull request reviewers",
        "operationId": "getPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewer",
        "description": "Adds a reviewer to a git pull request",
        "operationId": "createPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "DeletePullRequestReviewer",
        "description": "Removes a reviewer from a git pull request",
        "operationId": "deletePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewer",
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "getPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "pullRequestShare"
        ],
        "summary": "SharePullRequest",
        "description": "",
        "operationId": "sharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestStatus",
        "description": "Create a pull request status",
        "operationId": "createPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatuses",
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "getPullRequestStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatus",
        "description": "Get the specific pull request status.",
        "operationId": "getPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "CreateThread",
        "description": "Create a pull request review comment thread",
        "operationId": "createThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetThreads",
        "description": "Get all pull request comment threads.",
        "operationId": "getThreads",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetPullRequestThread",
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "getPullRequestThread",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "UpdateThread",
        "description": "Update a pull request review comment thread",
        "operationId": "updateThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "CreateComment",
        "description": "Create a pull request review comment",
        "operationId": "createComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComments",
        "description": "Get all pull request comments in a thread.",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "DeleteComment",
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "deleteComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComment",
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "UpdateComment",
        "description": "Update a pull request review comment thread",
        "operationId": "updateComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "pullRequestWorkItems"
        ],
        "summary": "GetPullRequestWorkItems",
        "description": "Retrieve a pull request work items",
        "operationId": "getPullRequestWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "pushes"
        ],
        "summary": "CreatePush",
        "description": "Push changes to the repository.",
        "operationId": "createPush",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPushes",
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "getPushes",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPush",
        "description": "Retrieve a particular push.",
        "operationId": "getPush",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRefs",
        "description": "Creates or updates refs with the given information",
        "operationId": "updateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "refs"
        ],
        "summary": "GetRefs",
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "getRefs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRef",
        "description": "",
        "operationId": "updateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranch",
        "description": "Retrieve statistics about a single branch.",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranchStatsBatch",
        "description": "Retrieve statistics for multiple commits",
        "operationId": "getBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "suggestions"
        ],
        "summary": "GetSuggestions",
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "getSuggestions",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "trees"
        ],
        "summary": "GetTree",
        "description": "",
        "operationId": "getTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/deletedrepositories": {
      "get": {
        "tags": [
          "deletedRepositories"
        ],
        "summary": "GetDeletedRepositories",
        "description": "Retrieve deleted git repositories.",
        "operationId": "getDeletedRepositories"
      }
    },
    "/{project}/_apis/git/favorites/refs": {
      "post": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "CreateFavorite",
        "description": "Creates a ref favorite",
        "operationId": "createFavorite",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "GetRefFavorites",
        "description": "Gets the refs favorites for a repo and an identity.",
        "operationId": "getRefFavorites",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/favorites/refs/{favoriteId}": {
      "delete": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "DeleteRefFavorite",
        "description": "",
        "operationId": "deleteRefFavorite"
      },
      "get": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "GetRefFavorite",
        "description": "",
        "operationId": "getRefFavorite",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/pullrequests": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequestsByProject",
        "description": "Query pull requests by project",
        "operationId": "getPullRequestsByProject",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories": {
      "post": {
        "tags": [
          "repositories"
        ],
        "summary": "CreateRepository",
        "description": "Create a git repository",
        "operationId": "createRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepositories",
        "description": "Retrieve git repositories.",
        "operationId": "getRepositories",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "repositories"
        ],
        "summary": "DeleteRepository",
        "description": "Delete a git repository",
        "operationId": "deleteRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepository",
        "description": "",
        "operationId": "getRepository",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "repositories"
        ],
        "summary": "UpdateRepository",
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "updateRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags": {
      "post": {
        "tags": [
          "annotatedTags"
        ],
        "summary": "CreateAnnotatedTag",
        "description": "Create an annotated tag",
        "operationId": "createAnnotatedTag",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags/{objectId}": {
      "get": {
        "tags": [
          "annotatedTags"
        ],
        "summary": "GetAnnotatedTag",
        "description": "Get an annotated tag",
        "operationId": "getAnnotatedTag",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlobsZip",
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "getBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlob",
        "description": "Gets a single blob.",
        "operationId": "getBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks": {
      "post": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "CreateCherryPick",
        "description": "",
        "operationId": "createCherryPick",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "GetCherryPickForRefName",
        "description": "",
        "operationId": "getCherryPickForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks/{cherryPickId}": {
      "get": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "GetCherryPick",
        "description": "",
        "operationId": "getCherryPick",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommits",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommit",
        "description": "Retrieve a particular commit.",
        "operationId": "getCommit",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetChanges",
        "description": "Retrieve changes for a particular commit.",
        "operationId": "getChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateCommitStatus",
        "description": "",
        "operationId": "createCommitStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetStatuses",
        "description": "",
        "operationId": "getStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "commitsBatch"
        ],
        "summary": "GetCommitsBatch",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommitsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "commitDiffs"
        ],
        "summary": "GetCommitDiffs",
        "description": "Get differences in committed items between two commits.",
        "operationId": "getCommitDiffs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests": {
      "post": {
        "tags": [
          "importRequests"
        ],
        "summary": "CreateImportRequest",
        "description": "Create an import request",
        "operationId": "createImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "importRequests"
        ],
        "summary": "QueryImportRequests",
        "description": "Retrieve import requests for a repository",
        "operationId": "queryImportRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests/{importRequestId}": {
      "get": {
        "tags": [
          "importRequests"
        ],
        "summary": "GetImportRequest",
        "description": "Retrieve a particular import request",
        "operationId": "getImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "importRequests"
        ],
        "summary": "UpdateImportRequest",
        "description": "Update an import request",
        "operationId": "updateImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "itemsBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "pullRequestQuery"
        ],
        "summary": "GetPullRequestQuery",
        "description": "Query for pull requests",
        "operationId": "getPullRequestQuery",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "pullRequests"
        ],
        "summary": "CreatePullRequest",
        "description": "Create a git pull request",
        "operationId": "createPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequests",
        "description": "Query for pull requests",
        "operationId": "getPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequest",
        "description": "Retrieve a pull request",
        "operationId": "getPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequests"
        ],
        "summary": "UpdatePullRequest",
        "description": "Updates a pull request",
        "operationId": "updatePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachments",
        "description": "",
        "operationId": "getAttachments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "CreateAttachment",
        "description": "Create a new attachment",
        "operationId": "createAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "DeleteAttachment",
        "description": "",
        "operationId": "deleteAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachmentContent",
        "description": "",
        "operationId": "getAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestCommits",
        "description": "Retrieve pull request's commits",
        "operationId": "getPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflicts",
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "getPullRequestConflicts",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflict",
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "getPullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "UpdatePullRequestConflict",
        "description": "Update merge conflict resolution",
        "operationId": "updatePullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIterations",
        "description": "",
        "operationId": "getPullRequestIterations",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIteration",
        "description": "",
        "operationId": "getPullRequestIteration",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "pullRequestIterationChanges"
        ],
        "summary": "GetPullRequestIterationChanges",
        "description": "",
        "operationId": "getPullRequestIterationChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestIterationCommits",
        "description": "Get the commits for an iteration.",
        "operationId": "getPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestIterationStatus",
        "description": "Create a pull request iteration status",
        "operationId": "createPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatuses",
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "getPullRequestIterationStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatus",
        "description": "Get the specific pull request iteration status.",
        "operationId": "getPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewers",
        "description": "Adds reviewers to a git pull request",
        "operationId": "createPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewers",
        "description": "Retrieve a pull request reviewers",
        "operationId": "getPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewer",
        "description": "Adds a reviewer to a git pull request",
        "operationId": "createPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "DeletePullRequestReviewer",
        "description": "Removes a reviewer from a git pull request",
        "operationId": "deletePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewer",
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "getPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "pullRequestShare"
        ],
        "summary": "SharePullRequest",
        "description": "",
        "operationId": "sharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestStatus",
        "description": "Create a pull request status",
        "operationId": "createPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatuses",
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "getPullRequestStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatus",
        "description": "Get the specific pull request status.",
        "operationId": "getPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "CreateThread",
        "description": "Create a pull request review comment thread",
        "operationId": "createThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetThreads",
        "description": "Get all pull request comment threads.",
        "operationId": "getThreads",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetPullRequestThread",
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "getPullRequestThread",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "UpdateThread",
        "description": "Update a pull request review comment thread",
        "operationId": "updateThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "CreateComment",
        "description": "Create a pull request review comment",
        "operationId": "createComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComments",
        "description": "Get all pull request comments in a thread.",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "DeleteComment",
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "deleteComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComment",
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "UpdateComment",
        "description": "Update a pull request review comment thread",
        "operationId": "updateComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "pullRequestWorkItems"
        ],
        "summary": "GetPullRequestWorkItems",
        "description": "Retrieve a pull request work items",
        "operationId": "getPullRequestWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "pushes"
        ],
        "summary": "CreatePush",
        "description": "Push changes to the repository.",
        "operationId": "createPush",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPushes",
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "getPushes",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPush",
        "description": "Retrieve a particular push.",
        "operationId": "getPush",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRefs",
        "description": "Creates or updates refs with the given information",
        "operationId": "updateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "refs"
        ],
        "summary": "GetRefs",
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "getRefs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRef",
        "description": "",
        "operationId": "updateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts": {
      "post": {
        "tags": [
          "reverts"
        ],
        "summary": "CreateRevert",
        "description": "",
        "operationId": "createRevert",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "reverts"
        ],
        "summary": "GetRevertForRefName",
        "description": "",
        "operationId": "getRevertForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts/{revertId}": {
      "get": {
        "tags": [
          "reverts"
        ],
        "summary": "GetRevert",
        "description": "",
        "operationId": "getRevert",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranch",
        "description": "Retrieve statistics about a single branch.",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranchStatsBatch",
        "description": "Retrieve statistics for multiple commits",
        "operationId": "getBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "suggestions"
        ],
        "summary": "GetSuggestions",
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "getSuggestions",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "trees"
        ],
        "summary": "GetTree",
        "description": "",
        "operationId": "getTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.code": "Grants the ability to read source code and metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to get notified about version control events via service hooks.",
        "vso.code_manage": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage code repositories, create and manage pull requests and code reviews, and to receive notifications about version control events via service hooks.",
        "vso.code_write": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage pull requests and code reviews and to receive notifications about version control events via service hooks.",
        "vso.code_status": "Grants the ability to read and write commit and pull request status."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}