{
  "swagger": "2.0",
  "info": {
    "title": "Git",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "annotatedTags"
    },
    {
      "name": "blobs"
    },
    {
      "name": "branchStats"
    },
    {
      "name": "changes"
    },
    {
      "name": "cherryPicks"
    },
    {
      "name": "commitDiffs"
    },
    {
      "name": "commits"
    },
    {
      "name": "commitsBatch"
    },
    {
      "name": "deletedRepositories"
    },
    {
      "name": "importRequests"
    },
    {
      "name": "items"
    },
    {
      "name": "itemsBatch"
    },
    {
      "name": "pullRequestAttachments"
    },
    {
      "name": "pullRequestCommits"
    },
    {
      "name": "pullRequestConflicts"
    },
    {
      "name": "pullRequestIterationChanges"
    },
    {
      "name": "pullRequestIterations"
    },
    {
      "name": "pullRequestQuery"
    },
    {
      "name": "pullRequestReviewers"
    },
    {
      "name": "pullRequests"
    },
    {
      "name": "pullRequestShare"
    },
    {
      "name": "pullRequestStatuses"
    },
    {
      "name": "pullRequestThreadComments"
    },
    {
      "name": "pullRequestThreads"
    },
    {
      "name": "pullRequestWorkItems"
    },
    {
      "name": "pushes"
    },
    {
      "name": "refLockRequest"
    },
    {
      "name": "refs"
    },
    {
      "name": "refsFavorites"
    },
    {
      "name": "repositories"
    },
    {
      "name": "reverts"
    },
    {
      "name": "statuses"
    },
    {
      "name": "suggestions"
    },
    {
      "name": "treeDiffs"
    },
    {
      "name": "trees"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/git/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequestById",
        "description": "Get a pull request using its ID",
        "operationId": "getPullRequestById"
      }
    },
    "/_apis/git/repositories": {
      "post": {
        "tags": [
          "repositories"
        ],
        "summary": "CreateRepository",
        "description": "Create a git repository",
        "operationId": "createRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepositories",
        "description": "Retrieve git repositories.",
        "operationId": "getRepositories",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "repositories"
        ],
        "summary": "DeleteRepository",
        "description": "Delete a git repository",
        "operationId": "deleteRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepository",
        "description": "",
        "operationId": "getRepository",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "repositories"
        ],
        "summary": "UpdateRepository",
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "updateRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlobsZip",
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "getBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlob",
        "description": "Gets a single blob.",
        "operationId": "getBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommits",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommit",
        "description": "Retrieve a particular commit.",
        "operationId": "getCommit",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetChanges",
        "description": "Retrieve changes for a particular commit.",
        "operationId": "getChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateCommitStatus",
        "description": "",
        "operationId": "createCommitStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetStatuses",
        "description": "",
        "operationId": "getStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "commitsBatch"
        ],
        "summary": "GetCommitsBatch",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommitsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "commitDiffs"
        ],
        "summary": "GetCommitDiffs",
        "description": "Get differences in committed items between two commits.",
        "operationId": "getCommitDiffs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "itemsBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "pullRequestQuery"
        ],
        "summary": "GetPullRequestQuery",
        "description": "Query for pull requests",
        "operationId": "getPullRequestQuery",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "pullRequests"
        ],
        "summary": "CreatePullRequest",
        "description": "Create a git pull request",
        "operationId": "createPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequests",
        "description": "Query for pull requests",
        "operationId": "getPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequest",
        "description": "Retrieve a pull request",
        "operationId": "getPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequests"
        ],
        "summary": "UpdatePullRequest",
        "description": "Updates a pull request",
        "operationId": "updatePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachments",
        "description": "",
        "operationId": "getAttachments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "CreateAttachment",
        "description": "Create a new attachment",
        "operationId": "createAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "DeleteAttachment",
        "description": "",
        "operationId": "deleteAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachmentContent",
        "description": "",
        "operationId": "getAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestCommits",
        "description": "Retrieve pull request's commits",
        "operationId": "getPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflicts",
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "getPullRequestConflicts",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflict",
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "getPullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "UpdatePullRequestConflict",
        "description": "Update merge conflict resolution",
        "operationId": "updatePullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIterations",
        "description": "",
        "operationId": "getPullRequestIterations",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIteration",
        "description": "",
        "operationId": "getPullRequestIteration",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "pullRequestIterationChanges"
        ],
        "summary": "GetPullRequestIterationChanges",
        "description": "",
        "operationId": "getPullRequestIterationChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestIterationCommits",
        "description": "Get the commits for an iteration.",
        "operationId": "getPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestIterationStatus",
        "description": "Create a pull request iteration status",
        "operationId": "createPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatuses",
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "getPullRequestIterationStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatus",
        "description": "Get the specific pull request iteration status.",
        "operationId": "getPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewers",
        "description": "Adds reviewers to a git pull request",
        "operationId": "createPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewers",
        "description": "Retrieve a pull request reviewers",
        "operationId": "getPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewer",
        "description": "Adds a reviewer to a git pull request",
        "operationId": "createPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "DeletePullRequestReviewer",
        "description": "Removes a reviewer from a git pull request",
        "operationId": "deletePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewer",
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "getPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "pullRequestShare"
        ],
        "summary": "SharePullRequest",
        "description": "",
        "operationId": "sharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestStatus",
        "description": "Create a pull request status",
        "operationId": "createPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatuses",
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "getPullRequestStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatus",
        "description": "Get the specific pull request status.",
        "operationId": "getPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "CreateThread",
        "description": "Create a pull request review comment thread",
        "operationId": "createThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetThreads",
        "description": "Get all pull request comment threads.",
        "operationId": "getThreads",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetPullRequestThread",
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "getPullRequestThread",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "UpdateThread",
        "description": "Update a pull request review comment thread",
        "operationId": "updateThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "CreateComment",
        "description": "Create a pull request review comment",
        "operationId": "createComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComments",
        "description": "Get all pull request comments in a thread.",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "DeleteComment",
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "deleteComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComment",
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "UpdateComment",
        "description": "Update a pull request review comment thread",
        "operationId": "updateComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "pullRequestWorkItems"
        ],
        "summary": "GetPullRequestWorkItems",
        "description": "Retrieve a pull request work items",
        "operationId": "getPullRequestWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "pushes"
        ],
        "summary": "CreatePush",
        "description": "Push changes to the repository.",
        "operationId": "createPush",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPushes",
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "getPushes",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPush",
        "description": "Retrieve a particular push.",
        "operationId": "getPush",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRefs",
        "description": "Creates or updates refs with the given information",
        "operationId": "updateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "refs"
        ],
        "summary": "GetRefs",
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "getRefs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRef",
        "description": "",
        "operationId": "updateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranch",
        "description": "Retrieve statistics about a single branch.",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranchStatsBatch",
        "description": "Retrieve statistics for multiple commits",
        "operationId": "getBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "suggestions"
        ],
        "summary": "GetSuggestions",
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "getSuggestions",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "trees"
        ],
        "summary": "GetTree",
        "description": "",
        "operationId": "getTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/deletedrepositories": {
      "get": {
        "tags": [
          "deletedRepositories"
        ],
        "summary": "GetDeletedRepositories",
        "description": "Retrieve deleted git repositories.",
        "operationId": "getDeletedRepositories"
      }
    },
    "/{project}/_apis/git/favorites/refs": {
      "post": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "CreateFavorite",
        "description": "Creates a ref favorite",
        "operationId": "createFavorite",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "GetRefFavorites",
        "description": "Gets the refs favorites for a repo and an identity.",
        "operationId": "getRefFavorites",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/favorites/refs/{favoriteId}": {
      "delete": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "DeleteRefFavorite",
        "description": "",
        "operationId": "deleteRefFavorite"
      },
      "get": {
        "tags": [
          "refsFavorites"
        ],
        "summary": "GetRefFavorite",
        "description": "",
        "operationId": "getRefFavorite",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/pullrequests": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequestsByProject",
        "description": "Query pull requests by project",
        "operationId": "getPullRequestsByProject",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories": {
      "post": {
        "tags": [
          "repositories"
        ],
        "summary": "CreateRepository",
        "description": "Create a git repository",
        "operationId": "createRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepositories",
        "description": "Retrieve git repositories.",
        "operationId": "getRepositories",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}": {
      "delete": {
        "tags": [
          "repositories"
        ],
        "summary": "DeleteRepository",
        "description": "Delete a git repository",
        "operationId": "deleteRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "repositories"
        ],
        "summary": "GetRepository",
        "description": "",
        "operationId": "getRepository",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "repositories"
        ],
        "summary": "UpdateRepository",
        "description": "Updates the Git repository with the single populated change in the specified repository information.",
        "operationId": "updateRepository",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags": {
      "post": {
        "tags": [
          "annotatedTags"
        ],
        "summary": "CreateAnnotatedTag",
        "description": "Create an annotated tag",
        "operationId": "createAnnotatedTag",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/annotatedtags/{objectId}": {
      "get": {
        "tags": [
          "annotatedTags"
        ],
        "summary": "GetAnnotatedTag",
        "description": "Get an annotated tag",
        "operationId": "getAnnotatedTag",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs": {
      "post": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlobsZip",
        "description": "Gets one or more blobs in a zip file download.",
        "operationId": "getBlobsZip",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/blobs/{sha1}": {
      "get": {
        "tags": [
          "blobs"
        ],
        "summary": "GetBlob",
        "description": "Gets a single blob.",
        "operationId": "getBlob",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks": {
      "post": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "CreateCherryPick",
        "description": "",
        "operationId": "createCherryPick",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "GetCherryPickForRefName",
        "description": "",
        "operationId": "getCherryPickForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/cherryPicks/{cherryPickId}": {
      "get": {
        "tags": [
          "cherryPicks"
        ],
        "summary": "GetCherryPick",
        "description": "",
        "operationId": "getCherryPick",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommits",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}": {
      "get": {
        "tags": [
          "commits"
        ],
        "summary": "GetCommit",
        "description": "Retrieve a particular commit.",
        "operationId": "getCommit",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetChanges",
        "description": "Retrieve changes for a particular commit.",
        "operationId": "getChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commits/{commitId}/statuses": {
      "post": {
        "tags": [
          "statuses"
        ],
        "summary": "CreateCommitStatus",
        "description": "",
        "operationId": "createCommitStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "statuses"
        ],
        "summary": "GetStatuses",
        "description": "",
        "operationId": "getStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/commitsbatch": {
      "post": {
        "tags": [
          "commitsBatch"
        ],
        "summary": "GetCommitsBatch",
        "description": "Retrieve git commits for a project",
        "operationId": "getCommitsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/diffs/commits": {
      "get": {
        "tags": [
          "commitDiffs"
        ],
        "summary": "GetCommitDiffs",
        "description": "Get differences in committed items between two commits.",
        "operationId": "getCommitDiffs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests": {
      "post": {
        "tags": [
          "importRequests"
        ],
        "summary": "CreateImportRequest",
        "description": "Create an import request",
        "operationId": "createImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "importRequests"
        ],
        "summary": "QueryImportRequests",
        "description": "Retrieve import requests for a repository",
        "operationId": "queryImportRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/importRequests/{importRequestId}": {
      "get": {
        "tags": [
          "importRequests"
        ],
        "summary": "GetImportRequest",
        "description": "Retrieve a particular import request",
        "operationId": "getImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "importRequests"
        ],
        "summary": "UpdateImportRequest",
        "description": "Update an import request",
        "operationId": "updateImportRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get Item Metadata and/or Content for a collection of items. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/itemsbatch": {
      "post": {
        "tags": [
          "itemsBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a creating a batch out of a set of items in a repo / project given a list of paths or a long path",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequestquery": {
      "post": {
        "tags": [
          "pullRequestQuery"
        ],
        "summary": "GetPullRequestQuery",
        "description": "Query for pull requests",
        "operationId": "getPullRequestQuery",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests": {
      "post": {
        "tags": [
          "pullRequests"
        ],
        "summary": "CreatePullRequest",
        "description": "Create a git pull request",
        "operationId": "createPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequests",
        "description": "Query for pull requests",
        "operationId": "getPullRequests",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullrequests/{pullRequestId}": {
      "get": {
        "tags": [
          "pullRequests"
        ],
        "summary": "GetPullRequest",
        "description": "Retrieve a pull request",
        "operationId": "getPullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequests"
        ],
        "summary": "UpdatePullRequest",
        "description": "Updates a pull request",
        "operationId": "updatePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments": {
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachments",
        "description": "",
        "operationId": "getAttachments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/attachments/{fileName}": {
      "post": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "CreateAttachment",
        "description": "Create a new attachment",
        "operationId": "createAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "DeleteAttachment",
        "description": "",
        "operationId": "deleteAttachment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestAttachments"
        ],
        "summary": "GetAttachmentContent",
        "description": "",
        "operationId": "getAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestCommits",
        "description": "Retrieve pull request's commits",
        "operationId": "getPullRequestCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflicts",
        "description": "Retrieve all conflicts for a pull request",
        "operationId": "getPullRequestConflicts",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/conflicts/{conflictId}": {
      "get": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "GetPullRequestConflict",
        "description": "Retrieve one conflict for a pull request by ID",
        "operationId": "getPullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestConflicts"
        ],
        "summary": "UpdatePullRequestConflict",
        "description": "Update merge conflict resolution",
        "operationId": "updatePullRequestConflict",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIterations",
        "description": "",
        "operationId": "getPullRequestIterations",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "pullRequestIterations"
        ],
        "summary": "GetPullRequestIteration",
        "description": "",
        "operationId": "getPullRequestIteration",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/changes": {
      "get": {
        "tags": [
          "pullRequestIterationChanges"
        ],
        "summary": "GetPullRequestIterationChanges",
        "description": "",
        "operationId": "getPullRequestIterationChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/commits": {
      "get": {
        "tags": [
          "pullRequestCommits"
        ],
        "summary": "GetPullRequestIterationCommits",
        "description": "Get the commits for an iteration.",
        "operationId": "getPullRequestIterationCommits",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestIterationStatus",
        "description": "Create a pull request iteration status",
        "operationId": "createPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatuses",
        "description": "Get all the statuses associated with a pull request iteration.",
        "operationId": "getPullRequestIterationStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/iterations/{iterationId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestIterationStatus",
        "description": "Get the specific pull request iteration status.",
        "operationId": "getPullRequestIterationStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers": {
      "post": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewers",
        "description": "Adds reviewers to a git pull request",
        "operationId": "createPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewers",
        "description": "Retrieve a pull request reviewers",
        "operationId": "getPullRequestReviewers",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/reviewers/{reviewerId}": {
      "put": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "CreatePullRequestReviewer",
        "description": "Adds a reviewer to a git pull request",
        "operationId": "createPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "DeletePullRequestReviewer",
        "description": "Removes a reviewer from a git pull request",
        "operationId": "deletePullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestReviewers"
        ],
        "summary": "GetPullRequestReviewer",
        "description": "Retrieve a reviewer from a pull request",
        "operationId": "getPullRequestReviewer",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/share": {
      "post": {
        "tags": [
          "pullRequestShare"
        ],
        "summary": "SharePullRequest",
        "description": "",
        "operationId": "sharePullRequest",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses": {
      "post": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "CreatePullRequestStatus",
        "description": "Create a pull request status",
        "operationId": "createPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code_write",
              "vso.code_status"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatuses",
        "description": "Get all the statuses associated with a pull request.",
        "operationId": "getPullRequestStatuses",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/statuses/{statusId}": {
      "get": {
        "tags": [
          "pullRequestStatuses"
        ],
        "summary": "GetPullRequestStatus",
        "description": "Get the specific pull request status.",
        "operationId": "getPullRequestStatus",
        "security": [
          {
            "oauth2": [
              "vso.code",
              "vso.code_status"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads": {
      "post": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "CreateThread",
        "description": "Create a pull request review comment thread",
        "operationId": "createThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetThreads",
        "description": "Get all pull request comment threads.",
        "operationId": "getThreads",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}": {
      "get": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "GetPullRequestThread",
        "description": "Get a pull request comment thread by id for a pull request",
        "operationId": "getPullRequestThread",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreads"
        ],
        "summary": "UpdateThread",
        "description": "Update a pull request review comment thread",
        "operationId": "updateThread",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments": {
      "post": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "CreateComment",
        "description": "Create a pull request review comment",
        "operationId": "createComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComments",
        "description": "Get all pull request comments in a thread.",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/threads/{threadId}/comments/{commentId}": {
      "delete": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "DeleteComment",
        "description": "Delete a pull request comment by id for a pull request",
        "operationId": "deleteComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "GetComment",
        "description": "Get a pull request comment by id for a pull request",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pullRequestThreadComments"
        ],
        "summary": "UpdateComment",
        "description": "Update a pull request review comment thread",
        "operationId": "updateComment",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pullRequests/{pullRequestId}/workitems": {
      "get": {
        "tags": [
          "pullRequestWorkItems"
        ],
        "summary": "GetPullRequestWorkItems",
        "description": "Retrieve a pull request work items",
        "operationId": "getPullRequestWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes": {
      "post": {
        "tags": [
          "pushes"
        ],
        "summary": "CreatePush",
        "description": "Push changes to the repository.",
        "operationId": "createPush",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPushes",
        "description": "Retrieves pushes associated with the specified repository.",
        "operationId": "getPushes",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/pushes/{pushId}": {
      "get": {
        "tags": [
          "pushes"
        ],
        "summary": "GetPush",
        "description": "Retrieve a particular push.",
        "operationId": "getPush",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs": {
      "post": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRefs",
        "description": "Creates or updates refs with the given information",
        "operationId": "updateRefs",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{*filter}": {
      "get": {
        "tags": [
          "refs"
        ],
        "summary": "GetRefs",
        "description": "Queries the provided repository for its refs and returns them.",
        "operationId": "getRefs",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/refs/{filter}": {
      "patch": {
        "tags": [
          "refs"
        ],
        "summary": "UpdateRef",
        "description": "",
        "operationId": "updateRef",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts": {
      "post": {
        "tags": [
          "reverts"
        ],
        "summary": "CreateRevert",
        "description": "",
        "operationId": "createRevert",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "reverts"
        ],
        "summary": "GetRevertForRefName",
        "description": "",
        "operationId": "getRevertForRefName",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/reverts/{revertId}": {
      "get": {
        "tags": [
          "reverts"
        ],
        "summary": "GetRevert",
        "description": "",
        "operationId": "getRevert",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/stats/branches": {
      "get": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranch",
        "description": "Retrieve statistics about a single branch.",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "branchStats"
        ],
        "summary": "GetBranchStatsBatch",
        "description": "Retrieve statistics for multiple commits",
        "operationId": "getBranchStatsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/suggestions": {
      "get": {
        "tags": [
          "suggestions"
        ],
        "summary": "GetSuggestions",
        "description": "Retrieve a set of suggestions (including a pull request suggestion).",
        "operationId": "getSuggestions",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/git/repositories/{repositoryId}/trees/{sha1}": {
      "get": {
        "tags": [
          "trees"
        ],
        "summary": "GetTree",
        "description": "",
        "operationId": "getTree",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    }
  },
  "definitions": {
    "AssociatedWorkItem": {
      "type": "object",
      "properties": {
        "assignedTo": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "state": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "description": "REST url",
          "type": "string"
        },
        "webUrl": {
          "type": "string"
        },
        "workItemType": {
          "type": "string"
        }
      }
    },
    "AsyncGitOperationNotification": {
      "type": "object",
      "properties": {
        "operationId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "AsyncRefOperationCommitLevelEventNotification": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
        "commitId": {
          "type": "string"
        }
      }
    },
    "AsyncRefOperationCompletedNotification": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
        "newRefName": {
          "type": "string"
        }
      }
    },
    "AsyncRefOperationConflictNotification": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncRefOperationCommitLevelEventNotification"
        }
      ],
      "properties": {
      }
    },
    "AsyncRefOperationGeneralFailureNotification": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncGitOperationNotification"
        }
      ],
      "properties": {
      }
    },
    "AsyncRefOperationProgressNotification": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/AsyncRefOperationCommitLevelEventNotification"
        }
      ],
      "properties": {
        "progress": {
          "type": "number",
          "format": "double"
        }
      }
    },
    "Attachment": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "description": "The person that uploaded this attachment",
          "$ref": "#/definitions/IdentityRef"
        },
        "contentHash": {
          "description": "Content hash of on-disk representation of file content. Its calculated by the server by using SHA1 hash function.",
          "type": "string"
        },
        "createdDate": {
          "description": "The time the attachment was uploaded",
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "description": "The description of the attachment, can be null.",
          "type": "string"
        },
        "displayName": {
          "description": "The display name of the attachment, can't be null or empty.",
          "type": "string"
        },
        "id": {
          "description": "Id of the code review attachment",
          "type": "integer",
          "format": "int32"
        },
        "properties": {
          "$ref": "#/definitions/PropertiesCollection"
        },
        "url": {
          "description": "The url to download the content of the attachment",
          "type": "string"
        }
      }
    },
    "Change": {
      "type": "object",
      "properties": {
        "changeType": {
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "item": {
          "type": "string",
          "format": "T"
        },
        "newContent": {
          "$ref": "#/definitions/ItemContent"
        },
        "sourceServerItem": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "ChangeCountDictionary": {
      "type": "object",
      "allOf": [
        {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        }
      ],
      "properties": {
      }
    },
    "ChangeList": {
      "type": "object",
      "properties": {
        "allChangesIncluded": {
          "type": "boolean"
        },
        "changeCounts": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "changes": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "Change"
          }
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "creationDate": {
          "type": "string",
          "format": "date-time"
        },
        "notes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "owner": {
          "type": "string"
        },
        "ownerDisplayName": {
          "type": "string"
        },
        "ownerId": {
          "type": "string",
          "format": "uuid"
        },
        "sortDate": {
          "type": "string",
          "format": "date-time"
        },
        "version": {
          "type": "string"
        }
      }
    },
    "ChangeListSearchCriteria": {
      "type": "object",
      "properties": {
        "compareVersion": {
          "description": "If provided, a version descriptor to compare against base",
          "type": "string"
        },
        "excludeDeletes": {
          "description": "If true, don't include delete history entries",
          "type": "boolean"
        },
        "followRenames": {
          "description": "Whether or not to follow renames for the given item being queried",
          "type": "boolean"
        },
        "fromDate": {
          "description": "If provided, only include history entries created after this date (string)",
          "type": "string"
        },
        "fromVersion": {
          "description": "If provided, a version descriptor for the earliest change list to include",
          "type": "string"
        },
        "itemPath": {
          "description": "Path of item to search under. If the itemPaths memebr is used then it will take precedence over this.",
          "type": "string"
        },
        "itemPaths": {
          "description": "List of item paths to search under. If this member is used then itemPath will be ignored.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "itemVersion": {
          "description": "Version of the items to search",
          "type": "string"
        },
        "skip": {
          "description": "Number of results to skip (used when clicking more...)",
          "type": "integer",
          "format": "int32"
        },
        "toDate": {
          "description": "If provided, only include history entries created before this date (string)",
          "type": "string"
        },
        "top": {
          "description": "If provided, the maximum number of history entries to return",
          "type": "integer",
          "format": "int32"
        },
        "toVersion": {
          "description": "If provided, a version descriptor for the latest change list to include",
          "type": "string"
        },
        "user": {
          "description": "Alias or display name of user who made the changes",
          "type": "string"
        }
      }
    },
    "CheckinNote": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    },
    "Comment": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "description": "The author of the pull request comment.",
          "$ref": "#/definitions/IdentityRef"
        },
        "commentType": {
          "description": "Determines what kind of comment when it was created.",
          "enum": [
            "unknown",
            "text",
            "codeChange",
            "system"
          ]
        },
        "content": {
          "description": "The comment's content.",
          "type": "string"
        },
        "id": {
          "description": "The pull request comment id. It always starts from 1.",
          "type": "integer",
          "format": "int16"
        },
        "isDeleted": {
          "description": "Marks if this comment was soft-deleted.",
          "type": "boolean"
        },
        "lastUpdatedDate": {
          "description": "The date a comment was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "parentCommentId": {
          "description": "The pull request comment id of the parent comment. This is used for replies",
          "type": "integer",
          "format": "int16"
        },
        "publishedDate": {
          "description": "The date a comment was first published.",
          "type": "string",
          "format": "date-time"
        },
        "usersLiked": {
          "description": "A list of the users who've liked this comment.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRef"
          }
        }
      }
    },
    "CommentIterationContext": {
      "type": "object",
      "properties": {
        "firstComparingIteration": {
          "description": "First comparing iteration Id. Minimum value is 1.",
          "type": "integer",
          "format": "int16"
        },
        "secondComparingIteration": {
          "description": "Second comparing iteration Id. Minimum value is 1.",
          "type": "integer",
          "format": "int16"
        }
      }
    },
    "CommentPosition": {
      "type": "object",
      "properties": {
        "line": {
          "description": "Position line starting with one.",
          "type": "integer",
          "format": "int32"
        },
        "offset": {
          "description": "Position offset starting with zero.",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "CommentThread": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "comments": {
          "description": "A list of the comments.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Comment"
          }
        },
        "id": {
          "description": "The comment thread id.",
          "type": "integer",
          "format": "int32"
        },
        "isDeleted": {
          "description": "Specify if the thread is deleted which happens when all comments are deleted",
          "type": "boolean"
        },
        "lastUpdatedDate": {
          "description": "The time this thread was last updated.",
          "type": "string",
          "format": "date-time"
        },
        "properties": {
          "description": "A list of (optional) thread properties.",
          "$ref": "#/definitions/PropertiesCollection"
        },
        "publishedDate": {
          "description": "The time this thread was published.",
          "type": "string",
          "format": "date-time"
        },
        "status": {
          "description": "The status of the comment thread.",
          "enum": [
            "unknown",
            "active",
            "fixed",
            "wontFix",
            "closed",
            "byDesign",
            "pending"
          ]
        },
        "threadContext": {
          "description": "Specify thread context such as position in left/right file.",
          "$ref": "#/definitions/CommentThreadContext"
        }
      }
    },
    "CommentThreadContext": {
      "type": "object",
      "properties": {
        "filePath": {
          "description": "File path relative to the root of the repository. It's up to the client to use any path format.",
          "type": "string"
        },
        "leftFileEnd": {
          "description": "Position of last character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "leftFileStart": {
          "description": "Position of first character of the comment in left file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "rightFileEnd": {
          "description": "Position of last character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        },
        "rightFileStart": {
          "description": "Position of first character of the comment in right file.",
          "$ref": "#/definitions/CommentPosition"
        }
      }
    },
    "CommentTrackingCriteria": {
      "type": "object",
      "properties": {
        "firstComparingIteration": {
          "description": "The first comparing iteration being viewed. Threads will be tracked if this is greater than 0.",
          "type": "integer",
          "format": "int32"
        },
        "secondComparingIteration": {
          "description": "The second comparing iteration being viewed. Threads will be tracked if this is greater than 0.",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "FileContentMetadata": {
      "type": "object",
      "properties": {
        "contentType": {
          "type": "string"
        },
        "encoding": {
          "type": "integer",
          "format": "int32"
        },
        "extension": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "isBinary": {
          "type": "boolean"
        },
        "isImage": {
          "type": "boolean"
        },
        "vsLink": {
          "type": "string"
        }
      }
    },
    "GitAnnotatedTag": {
      "type": "object",
      "properties": {
        "message": {
          "description": "Tagging Message",
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "objectId": {
          "type": "string"
        },
        "taggedBy": {
          "description": "User name, Email and date of tagging",
          "$ref": "#/definitions/GitUserDate"
        },
        "taggedObjectId": {
          "description": "Sha1Id of target object",
          "type": "string"
        },
        "taggedObjectType": {
          "description": "Type of object being tagged - commit, tag, blob...",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitAsyncRefOperation": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "detailedStatus": {
          "$ref": "#/definitions/GitAsyncRefOperationDetail"
        },
        "status": {
          "enum": [
            "queued",
            "inProgress",
            "completed",
            "failed",
            "abandoned"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitAsyncRefOperationDetail": {
      "type": "object",
      "properties": {
        "conflict": {
          "type": "boolean"
        },
        "currentCommitId": {
          "type": "string"
        },
        "progress": {
          "type": "number",
          "format": "double"
        }
      }
    },
    "GitAsyncRefOperationParameters": {
      "type": "object",
      "properties": {
        "generatedRefName": {
          "type": "string"
        },
        "ontoRefName": {
          "type": "string"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "source": {
          "$ref": "#/definitions/GitAsyncRefOperationSource"
        }
      }
    },
    "GitAsyncRefOperationSource": {
      "type": "object",
      "properties": {
        "commitList": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitBaseVersionDescriptor": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitVersionDescriptor"
        }
      ],
      "properties": {
        "baseVersion": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "baseVersionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "baseVersionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitBlobRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "size": {
          "description": "Size of blob content (in bytes)",
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitBranchStats": {
      "type": "object",
      "properties": {
        "aheadCount": {
          "type": "integer",
          "format": "int32"
        },
        "behindCount": {
          "type": "integer",
          "format": "int32"
        },
        "commit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "isBaseVersion": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitChange": {
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "Change"
        }
      ],
      "properties": {
        "changeId": {
          "description": "Id of the change within the group.  For example, within the iteration",
          "type": "integer",
          "format": "int32"
        },
        "newContentTemplate": {
          "description": "New Content template to be used",
          "$ref": "#/definitions/GitTemplate"
        },
        "originalPath": {
          "description": "Original path of item if different from current path",
          "type": "string"
        }
      }
    },
    "GitCherryPick": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitAsyncRefOperation"
        }
      ],
      "properties": {
        "cherryPickId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitCommit": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitCommitRef"
        }
      ],
      "properties": {
        "push": {
          "$ref": "#/definitions/GitPushRef"
        },
        "treeId": {
          "type": "string"
        }
      }
    },
    "GitCommitChanges": {
      "type": "object",
      "properties": {
        "changeCounts": {
          "$ref": "#/definitions/ChangeCountDictionary"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        }
      }
    },
    "GitCommitDiffs": {
      "type": "object",
      "properties": {
        "aheadCount": {
          "type": "integer",
          "format": "int32"
        },
        "allChangesIncluded": {
          "type": "boolean"
        },
        "baseCommit": {
          "type": "string"
        },
        "behindCount": {
          "type": "integer",
          "format": "int32"
        },
        "changeCounts": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        },
        "commonCommit": {
          "type": "string"
        },
        "targetCommit": {
          "type": "string"
        }
      }
    },
    "GitCommitRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/GitUserDate"
        },
        "changeCounts": {
          "$ref": "#/definitions/ChangeCountDictionary"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitChange"
          }
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "commitId": {
          "type": "string"
        },
        "committer": {
          "$ref": "#/definitions/GitUserDate"
        },
        "parents": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "remoteUrl": {
          "type": "string"
        },
        "statuses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitStatus"
          }
        },
        "url": {
          "type": "string"
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRef"
          }
        }
      }
    },
    "GitCommitToCreate": {
      "type": "object",
      "properties": {
        "baseRef": {
          "$ref": "#/definitions/GitRef"
        },
        "comment": {
          "type": "string"
        },
        "pathActions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPathAction"
          }
        }
      }
    },
    "GitConflict": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "conflictId": {
          "type": "integer",
          "format": "int32"
        },
        "conflictPath": {
          "type": "string"
        },
        "conflictType": {
          "enum": [
            "none",
            "addAdd",
            "addRename",
            "deleteEdit",
            "deleteRename",
            "directoryFile",
            "directoryChild",
            "editDelete",
            "editEdit",
            "fileDirectory",
            "rename1to2",
            "rename2to1",
            "renameAdd",
            "renameDelete",
            "renameRename"
          ]
        },
        "mergeBaseCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeOrigin": {
          "$ref": "#/definitions/GitMergeOriginRef"
        },
        "mergeSourceCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeTargetCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "resolutionError": {
          "enum": [
            "none",
            "mergeContentNotFound",
            "pathInUse",
            "invalidPath",
            "unknownAction",
            "unknownMergeType",
            "otherError"
          ]
        },
        "resolutionStatus": {
          "enum": [
            "unresolved",
            "partiallyResolved",
            "resolved"
          ]
        },
        "resolvedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "resolvedDate": {
          "type": "string",
          "format": "date-time"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitConflictAddAdd": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictAddRename": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalPath": {
          "type": "string"
        }
      }
    },
    "GitConflictDeleteEdit": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictDeleteRename": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictDirectoryFile": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceTree": {
          "$ref": "#/definitions/GitTreeRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictEditDelete": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictEditEdit": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictFileDirectory": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetTree": {
          "$ref": "#/definitions/GitTreeRef"
        }
      }
    },
    "GitConflictRename1to2": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionRename1to2"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceNewPath": {
          "type": "string"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRename2to1": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceNewBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalPath": {
          "type": "string"
        },
        "targetNewBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetOriginalPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRenameAdd": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPathConflict"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceOriginalPath": {
          "type": "string"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitConflictRenameDelete": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionPickOneAction"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "sourceNewPath": {
          "type": "string"
        }
      }
    },
    "GitConflictRenameRename": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitConflict"
        }
      ],
      "properties": {
        "baseBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "originalPath": {
          "type": "string"
        },
        "resolution": {
          "$ref": "#/definitions/GitResolutionMergeContent"
        },
        "sourceBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "targetBlob": {
          "$ref": "#/definitions/GitBlobRef"
        }
      }
    },
    "GitDeletedRepository": {
      "type": "object",
      "properties": {
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "deletedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "deletedDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        }
      }
    },
    "GitFilePathsCollection": {
      "type": "object",
      "properties": {
        "commitId": {
          "type": "string"
        },
        "paths": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitImportFailedEvent": {
      "type": "object",
      "properties": {
        "sourceRepositoryName": {
          "type": "string"
        },
        "targetRepository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitImportGitSource": {
      "type": "object",
      "properties": {
        "overwrite": {
          "description": "Tells if this is a sync request or not",
          "type": "boolean"
        },
        "url": {
          "description": "Url for the source repo",
          "type": "string"
        }
      }
    },
    "GitImportRequest": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "detailedStatus": {
          "$ref": "#/definitions/GitImportStatusDetail"
        },
        "importRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "status": {
          "enum": [
            "queued",
            "inProgress",
            "completed",
            "failed",
            "abandoned"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitImportRequestParameters": {
      "type": "object",
      "properties": {
        "deleteServiceEndpointAfterImportIsDone": {
          "description": "Option to delete service endpoint when import is done",
          "type": "boolean"
        },
        "gitSource": {
          "description": "Source for importing git repository",
          "$ref": "#/definitions/GitImportGitSource"
        },
        "serviceEndpointId": {
          "description": "Service Endpoint for connection to external endpoint",
          "type": "string",
          "format": "uuid"
        },
        "tfvcSource": {
          "description": "Source for importing tfvc repository",
          "$ref": "#/definitions/GitImportTfvcSource"
        }
      }
    },
    "GitImportStatusDetail": {
      "type": "object",
      "properties": {
        "allSteps": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "currentStep": {
          "type": "integer",
          "format": "int32"
        },
        "errorMessage": {
          "type": "string"
        }
      }
    },
    "GitImportSucceededEvent": {
      "type": "object",
      "properties": {
        "sourceRepositoryName": {
          "type": "string"
        },
        "targetRepository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitImportTfvcSource": {
      "type": "object",
      "properties": {
        "importHistory": {
          "description": "Set true to import History, false otherwise",
          "type": "boolean"
        },
        "importHistoryDurationInDays": {
          "description": "Get history for last n days (max allowed value is 180 days)",
          "type": "integer",
          "format": "int32"
        },
        "path": {
          "description": "Path which we want to import (this can be copied from Path Control in Explorer)",
          "type": "string"
        }
      }
    },
    "GitItem": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ItemModel"
        }
      ],
      "properties": {
        "commitId": {
          "description": "SHA1 of commit item was fetched at",
          "type": "string"
        },
        "gitObjectType": {
          "description": "Type of object (Commit, Tree, Blob, Tag, ...)",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "latestProcessedChange": {
          "description": "Shallow ref to commit that last changed this item Only populated if latestProcessedChange is requested May not be accurate if latest change is not yet cached",
          "$ref": "#/definitions/GitCommitRef"
        },
        "objectId": {
          "description": "Git object id",
          "type": "string"
        },
        "originalObjectId": {
          "description": "Git object id",
          "type": "string"
        }
      }
    },
    "GitItemDescriptor": {
      "type": "object",
      "properties": {
        "path": {
          "description": "Path to item",
          "type": "string"
        },
        "recursionLevel": {
          "description": "Specifies whether to include children (OneLevel), all descendants (Full), or None",
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        },
        "version": {
          "description": "Version string (interpretation based on VersionType defined in subclass",
          "type": "string"
        },
        "versionOptions": {
          "description": "Version modifiers (e.g. previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "versionType": {
          "description": "How to interpret version (branch,tag,commit)",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitItemRequestData": {
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "Whether to include metadata for all items",
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemDescriptors": {
          "description": "Collection of items to fetch, including path, version, and recursion level",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitItemDescriptor"
          }
        },
        "latestProcessedChange": {
          "description": "Whether to include shallow ref to commit that last changed each item",
          "type": "boolean"
        }
      }
    },
    "GitLastChangeItem": {
      "type": "object",
      "properties": {
        "commitId": {
          "description": "Gets or sets the commit Id this item was modified most recently for the provided version.",
          "type": "string"
        },
        "path": {
          "description": "Gets or sets the path of the item.",
          "type": "string"
        }
      }
    },
    "GitLastChangeTreeItems": {
      "type": "object",
      "properties": {
        "commits": {
          "description": "The list of commits referenced by Items, if they were requested.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "items": {
          "description": "The last change of items.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitLastChangeItem"
          }
        },
        "lastExploredTime": {
          "description": "The last explored time, in case the result is not comprehensive. Null otherwise.",
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitMergeOriginRef": {
      "type": "object",
      "properties": {
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPathAction": {
      "type": "object",
      "properties": {
        "action": {
          "enum": [
            "none",
            "edit",
            "delete",
            "add",
            "rename"
          ]
        },
        "base64Content": {
          "type": "string"
        },
        "path": {
          "type": "string"
        },
        "rawTextContent": {
          "type": "string"
        },
        "targetPath": {
          "type": "string"
        }
      }
    },
    "GitPathToItemsCollection": {
      "type": "object",
      "properties": {
        "items": {
          "type": "object",
          "additionalProperties": {
            "type": "array"
          }
        }
      }
    },
    "GitPullRequest": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "artifactId": {
          "type": "string"
        },
        "autoCompleteSetBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "closedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "closedDate": {
          "type": "string",
          "format": "date-time"
        },
        "codeReviewId": {
          "type": "integer",
          "format": "int32"
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "completionOptions": {
          "$ref": "#/definitions/GitPullRequestCompletionOptions"
        },
        "completionQueueTime": {
          "type": "string",
          "format": "date-time"
        },
        "createdBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "creationDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "lastMergeCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "lastMergeSourceCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "lastMergeTargetCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "mergeId": {
          "type": "string",
          "format": "uuid"
        },
        "mergeStatus": {
          "enum": [
            "notSet",
            "queued",
            "conflicts",
            "succeeded",
            "rejectedByPolicy",
            "failure"
          ]
        },
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "remoteUrl": {
          "type": "string"
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        },
        "reviewers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRefWithVote"
          }
        },
        "sourceRefName": {
          "type": "string"
        },
        "status": {
          "enum": [
            "notSet",
            "active",
            "abandoned",
            "completed",
            "all"
          ]
        },
        "supportsIterations": {
          "type": "boolean"
        },
        "targetRefName": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "workItemRefs": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ResourceRef"
          }
        }
      }
    },
    "GitPullRequestChange": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitChange"
        }
      ],
      "properties": {
        "changeTrackingId": {
          "description": "Id used to track files through multiple changes",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPullRequestCommentThread": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/CommentThread"
        }
      ],
      "properties": {
        "pullRequestThreadContext": {
          "description": "Extended context information unique to pull requests",
          "$ref": "#/definitions/GitPullRequestCommentThreadContext"
        }
      }
    },
    "GitPullRequestCommentThreadContext": {
      "type": "object",
      "properties": {
        "changeTrackingId": {
          "description": "Used to track a comment across iterations. This value can be found by looking at the iteration's changes list. Must be set for pull requests with iteration support. Otherwise, it's not required for 'legacy' pull requests.",
          "type": "integer",
          "format": "int32"
        },
        "iterationContext": {
          "description": "Specify comparing iteration Ids when a comment thread is added while comparing 2 iterations.",
          "$ref": "#/definitions/CommentIterationContext"
        },
        "trackingCriteria": {
          "description": "The criteria used to track this thread. If this property is filled out when the thread is returned, then the thread has been tracked from its original location using the given criteria.",
          "$ref": "#/definitions/CommentTrackingCriteria"
        }
      }
    },
    "GitPullRequestCompletionOptions": {
      "type": "object",
      "properties": {
        "bypassPolicy": {
          "type": "boolean"
        },
        "deleteSourceBranch": {
          "type": "boolean"
        },
        "mergeCommitMessage": {
          "type": "string"
        },
        "squashMerge": {
          "type": "boolean"
        }
      }
    },
    "GitPullRequestIteration": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/IdentityRef"
        },
        "changeList": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestChange"
          }
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "commonRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "hasMoreCommits": {
          "type": "boolean"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "push": {
          "$ref": "#/definitions/GitPushRef"
        },
        "reason": {
          "enum": [
            "push",
            "forcePush",
            "create",
            "rebase",
            "unknown"
          ]
        },
        "sourceRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "targetRefCommit": {
          "$ref": "#/definitions/GitCommitRef"
        },
        "updatedDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitPullRequestIterationChanges": {
      "type": "object",
      "properties": {
        "changeEntries": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestChange"
          }
        },
        "nextSkip": {
          "type": "integer",
          "format": "int32"
        },
        "nextTop": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPullRequestQuery": {
      "type": "object",
      "properties": {
        "queries": {
          "description": "The query to perform",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitPullRequestQueryInput"
          }
        },
        "results": {
          "description": "The results of the query",
          "type": "array",
          "items": {
            "type": "object"
          }
        }
      }
    },
    "GitPullRequestQueryInput": {
      "type": "object",
      "properties": {
        "items": {
          "description": "The list commit ids to search for.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "type": {
          "description": "The type of query to perform",
          "enum": [
            "notSet",
            "lastMergeCommit",
            "commit"
          ]
        }
      }
    },
    "GitPullRequestReviewFileContentInfo": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "path": {
          "description": "The file change path.",
          "type": "string"
        },
        "sHA1Hash": {
          "description": "Content hash of on-disk representation of file content. Its calculated by the client by using SHA1 hash function. Ensure that uploaded file has same encoding as in source control.",
          "type": "string"
        }
      }
    },
    "GitPullRequestSearchCriteria": {
      "type": "object",
      "properties": {
        "creatorId": {
          "type": "string",
          "format": "uuid"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "reviewerId": {
          "type": "string",
          "format": "uuid"
        },
        "sourceRefName": {
          "type": "string"
        },
        "status": {
          "enum": [
            "notSet",
            "active",
            "abandoned",
            "completed",
            "all"
          ]
        },
        "targetRefName": {
          "type": "string"
        }
      }
    },
    "GitPullRequestStatus": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitStatus"
        }
      ],
      "properties": {
        "iterationId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitPush": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitPushRef"
        }
      ],
      "properties": {
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommitRef"
          }
        },
        "refUpdates": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitRefUpdate"
          }
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitPushEventData": {
      "type": "object",
      "properties": {
        "afterId": {
          "type": "string"
        },
        "beforeId": {
          "type": "string"
        },
        "branch": {
          "type": "string"
        },
        "commits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitCommit"
          }
        },
        "repository": {
          "$ref": "#/definitions/GitRepository"
        }
      }
    },
    "GitPushRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "pushCorrelationId": {
          "type": "string",
          "format": "uuid"
        },
        "pushedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "pushId": {
          "type": "integer",
          "format": "int32"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitPushSearchCriteria": {
      "type": "object",
      "properties": {
        "fromDate": {
          "type": "string",
          "format": "date-time"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "includeRefUpdates": {
          "type": "boolean"
        },
        "pusherId": {
          "type": "string",
          "format": "uuid"
        },
        "refName": {
          "type": "string"
        },
        "toDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitQueryBranchStatsCriteria": {
      "type": "object",
      "properties": {
        "baseCommit": {
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "targetCommits": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitVersionDescriptor"
          }
        }
      }
    },
    "GitQueryCommitsCriteria": {
      "type": "object",
      "properties": {
        "$skip": {
          "description": "Number of entries to skip",
          "type": "integer",
          "format": "int32"
        },
        "$top": {
          "description": "Maximum number of entries to retrieve",
          "type": "integer",
          "format": "int32"
        },
        "author": {
          "description": "Alias or display name of the author",
          "type": "string"
        },
        "compareVersion": {
          "description": "If provided, the earliest commit in the graph to search",
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "excludeDeletes": {
          "description": "If true, don't include delete history entries",
          "type": "boolean"
        },
        "fromCommitId": {
          "description": "If provided, a lower bound for filtering commits alphabetically",
          "type": "string"
        },
        "fromDate": {
          "description": "If provided, only include history entries created after this date (string)",
          "type": "string"
        },
        "ids": {
          "description": "If provided, specifies the exact commit ids of the commits to fetch. May not be combined with other parameters.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "includeWorkItems": {
          "description": "Whether to include linked work items",
          "type": "boolean"
        },
        "itemPath": {
          "description": "Path of item to search under",
          "type": "string"
        },
        "itemVersion": {
          "description": "If provided, identifies the commit or branch to search",
          "$ref": "#/definitions/GitVersionDescriptor"
        },
        "toCommitId": {
          "description": "If provided, an upper bound for filtering commits alphabetically",
          "type": "string"
        },
        "toDate": {
          "description": "If provided, only include history entries created before this date (string)",
          "type": "string"
        },
        "user": {
          "description": "Alias or display name of the committer",
          "type": "string"
        }
      }
    },
    "GitRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "isLocked": {
          "type": "boolean"
        },
        "isLockedBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "name": {
          "type": "string"
        },
        "objectId": {
          "type": "string"
        },
        "peeledObjectId": {
          "type": "string"
        },
        "statuses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitStatus"
          }
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitRefFavorite": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "identityId": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        },
        "type": {
          "enum": [
            "invalid",
            "folder",
            "ref"
          ]
        },
        "url": {
          "type": "string"
        }
      }
    },
    "GitRefLockRequest": {
      "type": "object",
      "properties": {
        "lock": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitRefUpdate": {
      "type": "object",
      "properties": {
        "isLocked": {
          "type": "boolean"
        },
        "name": {
          "type": "string"
        },
        "newObjectId": {
          "type": "string"
        },
        "oldObjectId": {
          "type": "string"
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "GitRefUpdateResult": {
      "type": "object",
      "properties": {
        "customMessage": {
          "description": "Custom message for the result object For instance, Reason for failing.",
          "type": "string"
        },
        "isLocked": {
          "description": "Whether the ref is locked or not",
          "type": "boolean"
        },
        "name": {
          "description": "Ref name",
          "type": "string"
        },
        "newObjectId": {
          "description": "New object ID",
          "type": "string"
        },
        "oldObjectId": {
          "description": "Old object ID",
          "type": "string"
        },
        "rejectedBy": {
          "description": "Name of the plugin that rejected the updated.",
          "type": "string"
        },
        "repositoryId": {
          "description": "Repository ID",
          "type": "string",
          "format": "uuid"
        },
        "success": {
          "description": "True if the ref update succeeded, false otherwise",
          "type": "boolean"
        },
        "updateStatus": {
          "description": "Status of the update from the TFS server.",
          "enum": [
            "succeeded",
            "forcePushRequired",
            "staleOldObjectId",
            "invalidRefName",
            "unprocessed",
            "unresolvableToCommit",
            "writePermissionRequired",
            "manageNotePermissionRequired",
            "createBranchPermissionRequired",
            "createTagPermissionRequired",
            "rejectedByPlugin",
            "locked",
            "refNameConflict",
            "rejectedByPolicy",
            "succeededNonExistentRef",
            "succeededCorruptRef"
          ]
        }
      }
    },
    "GitRefUpdateResultSet": {
      "type": "object",
      "properties": {
        "countFailed": {
          "type": "integer",
          "format": "int32"
        },
        "countSucceeded": {
          "type": "integer",
          "format": "int32"
        },
        "pushCorrelationId": {
          "type": "string",
          "format": "uuid"
        },
        "pushIds": {
          "type": "object",
          "additionalProperties": {
            "type": "integer",
            "format": "int32"
          }
        },
        "pushTime": {
          "type": "string",
          "format": "date-time"
        },
        "results": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitRefUpdateResult"
          }
        }
      }
    },
    "GitRepository": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "defaultBranch": {
          "type": "string"
        },
        "id": {
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "type": "string"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        },
        "remoteUrl": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "validRemoteUrls": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "GitRepositoryStats": {
      "type": "object",
      "properties": {
        "activePullRequestsCount": {
          "type": "integer",
          "format": "int32"
        },
        "branchesCount": {
          "type": "integer",
          "format": "int32"
        },
        "commitsCount": {
          "type": "integer",
          "format": "int32"
        },
        "repositoryId": {
          "type": "string"
        }
      }
    },
    "GitResolution": {
      "type": "object",
      "properties": {
      }
    },
    "GitResolutionMergeContent": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "mergeType": {
          "enum": [
            "undecided",
            "takeSourceContent",
            "takeTargetContent",
            "autoMerged",
            "userMerged"
          ]
        },
        "userMergedBlob": {
          "$ref": "#/definitions/GitBlobRef"
        },
        "userMergedContent": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "byte"
          }
        }
      }
    },
    "GitResolutionPathConflict": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "keepSourceRenameTarget",
            "keepSourceDeleteTarget",
            "keepTargetRenameSource",
            "keepTargetDeleteSource"
          ]
        },
        "renamePath": {
          "type": "string"
        }
      }
    },
    "GitResolutionPickOneAction": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolution"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "pickSourceAction",
            "pickTargetAction"
          ]
        }
      }
    },
    "GitResolutionRename1to2": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitResolutionMergeContent"
        }
      ],
      "properties": {
        "action": {
          "enum": [
            "undecided",
            "keepSourcePath",
            "keepTargetPath",
            "keepBothFiles"
          ]
        }
      }
    },
    "GitRevert": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitAsyncRefOperation"
        }
      ],
      "properties": {
        "revertId": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "GitStatus": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "context": {
          "$ref": "#/definitions/GitStatusContext"
        },
        "createdBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "creationDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "state": {
          "enum": [
            "notSet",
            "pending",
            "succeeded",
            "failed",
            "error"
          ]
        },
        "targetUrl": {
          "type": "string"
        },
        "updatedDate": {
          "type": "string",
          "format": "date-time"
        }
      }
    },
    "GitStatusContext": {
      "type": "object",
      "properties": {
        "genre": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitSuggestion": {
      "type": "object",
      "properties": {
        "properties": {
          "type": "object",
          "additionalProperties": {
            "type": "object"
          }
        },
        "type": {
          "type": "string"
        }
      }
    },
    "GitTargetVersionDescriptor": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/GitVersionDescriptor"
        }
      ],
      "properties": {
        "targetVersion": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "targetVersionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "targetVersionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "GitTemplate": {
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the Template",
          "type": "string"
        },
        "type": {
          "description": "Type of the Template",
          "type": "string"
        }
      }
    },
    "GitTreeDiff": {
      "type": "object",
      "properties": {
        "baseTreeId": {
          "description": "ObjectId of the base tree of this diff.",
          "type": "string"
        },
        "diffEntries": {
          "description": "List of tree entries that differ between the base and target tree.  Renames and object type changes are returned as a delete for the old object and add for the new object.  If a continuation token is returned in the response header, some tree entries are yet to be processed and may yeild more diff entries. If the continuation token is not returned all the diff entries have been included in this response.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitTreeDiffEntry"
          }
        },
        "targetTreeId": {
          "description": "ObjectId of the target tree of this diff.",
          "type": "string"
        },
        "url": {
          "description": "REST Url to this resource.",
          "type": "string"
        }
      }
    },
    "GitTreeDiffEntry": {
      "type": "object",
      "properties": {
        "baseObjectId": {
          "description": "SHA1 hash of the object in the base tree, if it exists. Will be null in case of adds.",
          "type": "string"
        },
        "changeType": {
          "description": "Type of change that affected this entry.",
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "objectType": {
          "description": "Object type of the tree entry. Blob, Tree or Commit(\"submodule\")",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "path": {
          "description": "Relative path in base and target trees.",
          "type": "string"
        },
        "targetObjectId": {
          "description": "SHA1 hash of the object in the target tree, if it exists. Will be null in case of deletes.",
          "type": "string"
        }
      }
    },
    "GitTreeDiffResponse": {
      "type": "object",
      "properties": {
        "continuationToken": {
          "description": "The HTTP client methods find the continuation token header in the response and populate this field.",
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "treeDiff": {
          "$ref": "#/definitions/GitTreeDiff"
        }
      }
    },
    "GitTreeEntryRef": {
      "type": "object",
      "properties": {
        "gitObjectType": {
          "description": "Blob or tree",
          "enum": [
            "bad",
            "commit",
            "tree",
            "blob",
            "tag",
            "ext2",
            "ofsDelta",
            "refDelta"
          ]
        },
        "mode": {
          "description": "Mode represented as octal string",
          "type": "string"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "relativePath": {
          "description": "Path relative to parent tree object",
          "type": "string"
        },
        "size": {
          "description": "Size of content",
          "type": "integer",
          "format": "int64"
        },
        "url": {
          "description": "url to retrieve tree or blob",
          "type": "string"
        }
      }
    },
    "GitTreeRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "objectId": {
          "description": "SHA1 hash of git object",
          "type": "string"
        },
        "size": {
          "description": "Sum of sizes of all children",
          "type": "integer",
          "format": "int64"
        },
        "treeEntries": {
          "description": "Blobs and trees under this tree",
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitTreeEntryRef"
          }
        },
        "url": {
          "description": "Url to tree",
          "type": "string"
        }
      }
    },
    "GitUserDate": {
      "type": "object",
      "properties": {
        "date": {
          "type": "string",
          "format": "date-time"
        },
        "email": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      }
    },
    "GitVersionDescriptor": {
      "type": "object",
      "properties": {
        "version": {
          "description": "Version string identifier (name of tag/branch, SHA1 of commit)",
          "type": "string"
        },
        "versionOptions": {
          "description": "Version options - Specify additional modifiers to version (e.g Previous)",
          "enum": [
            "none",
            "previousChange",
            "firstParent"
          ]
        },
        "versionType": {
          "description": "Version type (branch, tag, or commit). Determines how Id is interpreted",
          "enum": [
            "branch",
            "tag",
            "commit"
          ]
        }
      }
    },
    "HistoryEntry": {
      "type": "object",
      "properties": {
        "changeList": {
          "description": "The Change list (changeset/commit/shelveset) for this point in history",
          "type": "string",
          "format": "ChangeList"
        },
        "itemChangeType": {
          "description": "The change made to the item from this change list (only relevant for File history, not folders)",
          "enum": [
            "none",
            "add",
            "edit",
            "encoding",
            "rename",
            "delete",
            "undelete",
            "branch",
            "merge",
            "lock",
            "rollback",
            "sourceRename",
            "targetRename",
            "property",
            "all"
          ]
        },
        "serverItem": {
          "description": "The path of the item at this point in history (only relevant for File history, not folders)",
          "type": "string"
        }
      }
    },
    "IdentityRef": {
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "imageUrl": {
          "type": "string"
        },
        "inactive": {
          "type": "boolean"
        },
        "isAadIdentity": {
          "type": "boolean"
        },
        "isContainer": {
          "type": "boolean"
        },
        "profileUrl": {
          "type": "string"
        },
        "uniqueName": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "IdentityRefWithVote": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/IdentityRef"
        }
      ],
      "properties": {
        "isRequired": {
          "type": "boolean"
        },
        "reviewerUrl": {
          "type": "string"
        },
        "vote": {
          "type": "integer",
          "format": "int16"
        },
        "votedFor": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRefWithVote"
          }
        }
      }
    },
    "ImportRepositoryValidation": {
      "type": "object",
      "properties": {
        "gitSource": {
          "$ref": "#/definitions/GitImportGitSource"
        },
        "password": {
          "type": "string"
        },
        "tfvcSource": {
          "$ref": "#/definitions/GitImportTfvcSource"
        },
        "username": {
          "type": "string"
        }
      }
    },
    "IncludedGitCommit": {
      "type": "object",
      "properties": {
        "commitId": {
          "type": "string"
        },
        "commitTime": {
          "type": "string",
          "format": "date-time"
        },
        "parentCommitIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "repositoryId": {
          "type": "string",
          "format": "uuid"
        }
      }
    },
    "ItemContent": {
      "type": "object",
      "properties": {
        "content": {
          "type": "string"
        },
        "contentType": {
          "enum": [
            "rawText",
            "base64Encoded"
          ]
        }
      }
    },
    "ItemDetailsOptions": {
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "If true, include metadata about the file type",
          "type": "boolean"
        },
        "recursionLevel": {
          "description": "Specifies whether to include children (OneLevel), all descendants (Full) or None for folder items",
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        }
      }
    },
    "ItemModel": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "contentMetadata": {
          "$ref": "#/definitions/FileContentMetadata"
        },
        "isFolder": {
          "type": "boolean"
        },
        "isSymLink": {
          "type": "boolean"
        },
        "path": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "PropertiesCollection": {
      "type": "object",
      "properties": {
        "count": {
          "description": "Implements ICollection<KeyValuePair<String,Object>>.Count/>",
          "type": "integer",
          "format": "int32"
        },
        "item": {
          "type": "object"
        },
        "keys": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "values": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "PullRequestTabExtensionConfig": {
      "type": "object",
      "properties": {
        "pullRequestId": {
          "type": "integer",
          "format": "int32"
        },
        "repositoryId": {
          "type": "string"
        }
      }
    },
    "ReferenceLinks": {
      "type": "object",
      "properties": {
      }
    },
    "ResourceRef": {
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "ShareNotificationContext": {
      "type": "object",
      "properties": {
        "message": {
          "description": "Optional user note or message.",
          "type": "string"
        },
        "receivers": {
          "description": "Identities of users who will receive a share notification.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/IdentityRef"
          }
        }
      }
    },
    "SupportedIde": {
      "type": "object",
      "properties": {
        "downloadUrl": {
          "description": "The download URL for the IDE.",
          "type": "string"
        },
        "ideType": {
          "description": "The type of the IDE.",
          "enum": [
            "unknown",
            "androidStudio",
            "appCode",
            "cLion",
            "dataGrip",
            "eclipse",
            "intelliJ",
            "mPS",
            "phpStorm",
            "pyCharm",
            "rubyMine",
            "tower",
            "visualStudio",
            "webStorm"
          ]
        },
        "name": {
          "description": "The name of the IDE.",
          "type": "string"
        },
        "protocolHandlerUrl": {
          "description": "The URL to open the protocol handler for the IDE.",
          "type": "string"
        },
        "supportedPlatforms": {
          "description": "A list of SupportedPlatforms.",
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "TeamProjectReference": {
      "type": "object",
      "properties": {
        "abbreviation": {
          "description": "Project abbreviation.",
          "type": "string"
        },
        "description": {
          "description": "The project's description (if any).",
          "type": "string"
        },
        "id": {
          "description": "Project identifier.",
          "type": "string",
          "format": "uuid"
        },
        "name": {
          "description": "Project name.",
          "type": "string"
        },
        "revision": {
          "description": "Project revision.",
          "type": "integer",
          "format": "int64"
        },
        "state": {
          "description": "Project state.",
          "enum": [
            "deleting",
            "new",
            "wellFormed",
            "createPending",
            "all",
            "unchanged",
            "deleted"
          ]
        },
        "url": {
          "description": "Url to the full version of the object.",
          "type": "string"
        }
      }
    },
    "TfvcBranch": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcBranchRef"
        }
      ],
      "properties": {
        "children": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcBranch"
          }
        },
        "mappings": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcBranchMapping"
          }
        },
        "parent": {
          "$ref": "#/definitions/TfvcShallowBranchRef"
        },
        "relatedBranches": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcShallowBranchRef"
          }
        }
      }
    },
    "TfvcBranchMapping": {
      "type": "object",
      "properties": {
        "depth": {
          "type": "string"
        },
        "serverItem": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      }
    },
    "TfvcBranchRef": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcShallowBranchRef"
        }
      ],
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "description": {
          "type": "string"
        },
        "isDeleted": {
          "type": "boolean"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcChange": {
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "Change"
        }
      ],
      "properties": {
        "mergeSources": {
          "description": "List of merge sources in case of rename or branch creation.",
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcMergeSource"
          }
        },
        "pendingVersion": {
          "description": "Version at which a (shelved) change was pended against",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcChangeset": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcChangesetRef"
        }
      ],
      "properties": {
        "accountId": {
          "type": "string",
          "format": "uuid"
        },
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcChange"
          }
        },
        "checkinNotes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "collectionId": {
          "type": "string",
          "format": "uuid"
        },
        "hasMoreChanges": {
          "type": "boolean"
        },
        "policyOverride": {
          "$ref": "#/definitions/TfvcPolicyOverrideInfo"
        },
        "teamProjectIds": {
          "type": "array",
          "items": {
            "type": "string",
            "format": "uuid"
          }
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AssociatedWorkItem"
          }
        }
      }
    },
    "TfvcChangesetRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "author": {
          "$ref": "#/definitions/IdentityRef"
        },
        "changesetId": {
          "type": "integer",
          "format": "int32"
        },
        "checkedInBy": {
          "$ref": "#/definitions/IdentityRef"
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcChangesetSearchCriteria": {
      "type": "object",
      "properties": {
        "author": {
          "description": "Alias or display name of user who made the changes",
          "type": "string"
        },
        "followRenames": {
          "description": "Whether or not to follow renames for the given item being queried",
          "type": "boolean"
        },
        "fromDate": {
          "description": "If provided, only include changesets created after this date (string) Think of a better name for this.",
          "type": "string"
        },
        "fromId": {
          "description": "If provided, only include changesets after this changesetID",
          "type": "integer",
          "format": "int32"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemPath": {
          "description": "Path of item to search under",
          "type": "string"
        },
        "toDate": {
          "description": "If provided, only include changesets created before this date (string) Think of a better name for this.",
          "type": "string"
        },
        "toId": {
          "description": "If provided, a version descriptor for the latest change list to include",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcChangesetsRequestData": {
      "type": "object",
      "properties": {
        "changesetIds": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "commentLength": {
          "type": "integer",
          "format": "int32"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        }
      }
    },
    "TfvcCheckinEventData": {
      "type": "object",
      "properties": {
        "changeset": {
          "$ref": "#/definitions/TfvcChangeset"
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        }
      }
    },
    "TfvcHistoryEntry": {
      "type": "object",
      "allOf": [
        {
          "type": "string",
          "format": "HistoryEntry"
        }
      ],
      "properties": {
        "encoding": {
          "description": "The encoding of the item at this point in history (only relevant for File history, not folders)",
          "type": "integer",
          "format": "int32"
        },
        "fileId": {
          "description": "The file id of the item at this point in history (only relevant for File history, not folders)",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcItem": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/ItemModel"
        }
      ],
      "properties": {
        "changeDate": {
          "type": "string",
          "format": "date-time"
        },
        "deletionId": {
          "type": "integer",
          "format": "int32"
        },
        "hashValue": {
          "description": "MD5 hash as a base 64 string, applies to files only.",
          "type": "string"
        },
        "isBranch": {
          "type": "boolean"
        },
        "isPendingChange": {
          "type": "boolean"
        },
        "size": {
          "description": "The size of the file, if applicable.",
          "type": "integer",
          "format": "int64"
        },
        "version": {
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcItemDescriptor": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        },
        "recursionLevel": {
          "enum": [
            "none",
            "oneLevel",
            "oneLevelPlusNestedEmptyFolders",
            "full"
          ]
        },
        "version": {
          "type": "string"
        },
        "versionOption": {
          "enum": [
            "none",
            "previous",
            "useRename"
          ]
        },
        "versionType": {
          "enum": [
            "none",
            "changeset",
            "shelveset",
            "change",
            "date",
            "latest",
            "tip",
            "mergeSource"
          ]
        }
      }
    },
    "TfvcItemRequestData": {
      "type": "object",
      "properties": {
        "includeContentMetadata": {
          "description": "If true, include metadata about the file type",
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemDescriptors": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcItemDescriptor"
          }
        }
      }
    },
    "TfvcLabel": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcLabelRef"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcItem"
          }
        }
      }
    },
    "TfvcLabelRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "description": {
          "type": "string"
        },
        "id": {
          "type": "integer",
          "format": "int32"
        },
        "labelScope": {
          "type": "string"
        },
        "modifiedDate": {
          "type": "string",
          "format": "date-time"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcLabelRequestData": {
      "type": "object",
      "properties": {
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references",
          "type": "boolean"
        },
        "itemLabelFilter": {
          "type": "string"
        },
        "labelScope": {
          "type": "string"
        },
        "maxItemCount": {
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "type": "string"
        }
      }
    },
    "TfvcMergeSource": {
      "type": "object",
      "properties": {
        "isRename": {
          "description": "Indicates if this a rename source. If false, it is a merge source.",
          "type": "boolean"
        },
        "serverItem": {
          "description": "The server item of the merge source",
          "type": "string"
        },
        "versionFrom": {
          "description": "Start of the version range",
          "type": "integer",
          "format": "int32"
        },
        "versionTo": {
          "description": "End of the version range",
          "type": "integer",
          "format": "int32"
        }
      }
    },
    "TfvcPolicyFailureInfo": {
      "type": "object",
      "properties": {
        "message": {
          "type": "string"
        },
        "policyName": {
          "type": "string"
        }
      }
    },
    "TfvcPolicyOverrideInfo": {
      "type": "object",
      "properties": {
        "comment": {
          "type": "string"
        },
        "policyFailures": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcPolicyFailureInfo"
          }
        }
      }
    },
    "TfvcShallowBranchRef": {
      "type": "object",
      "properties": {
        "path": {
          "type": "string"
        }
      }
    },
    "TfvcShelveset": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/TfvcShelvesetRef"
        }
      ],
      "properties": {
        "changes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/TfvcChange"
          }
        },
        "notes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/CheckinNote"
          }
        },
        "policyOverride": {
          "$ref": "#/definitions/TfvcPolicyOverrideInfo"
        },
        "workItems": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/AssociatedWorkItem"
          }
        }
      }
    },
    "TfvcShelvesetRef": {
      "type": "object",
      "properties": {
        "_links": {
          "$ref": "#/definitions/ReferenceLinks"
        },
        "comment": {
          "type": "string"
        },
        "commentTruncated": {
          "type": "boolean"
        },
        "createdDate": {
          "type": "string",
          "format": "date-time"
        },
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "owner": {
          "$ref": "#/definitions/IdentityRef"
        },
        "url": {
          "type": "string"
        }
      }
    },
    "TfvcShelvesetRequestData": {
      "type": "object",
      "properties": {
        "includeDetails": {
          "description": "Whether to include policyOverride and notes Only applies when requesting a single deep shelveset",
          "type": "boolean"
        },
        "includeLinks": {
          "description": "Whether to include the _links field on the shallow references. Does not apply when requesting a single deep shelveset object. Links will always be included in the deep shelveset.",
          "type": "boolean"
        },
        "includeWorkItems": {
          "description": "Whether to include workItems",
          "type": "boolean"
        },
        "maxChangeCount": {
          "description": "Max number of changes to include",
          "type": "integer",
          "format": "int32"
        },
        "maxCommentLength": {
          "description": "Max length of comment",
          "type": "integer",
          "format": "int32"
        },
        "name": {
          "description": "Shelveset's name",
          "type": "string"
        },
        "owner": {
          "description": "Owner's ID. Could be a name or a guid.",
          "type": "string"
        }
      }
    },
    "TfvcVersionDescriptor": {
      "type": "object",
      "properties": {
        "version": {
          "type": "string"
        },
        "versionOption": {
          "enum": [
            "none",
            "previous",
            "useRename"
          ]
        },
        "versionType": {
          "enum": [
            "none",
            "changeset",
            "shelveset",
            "change",
            "date",
            "latest",
            "tip",
            "mergeSource"
          ]
        }
      }
    },
    "UpdateRefsRequest": {
      "type": "object",
      "properties": {
        "refUpdateRequests": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/GitRefUpdate"
          }
        },
        "updateMode": {
          "enum": [
            "bestEffort",
            "allOrNone"
          ]
        }
      }
    },
    "VersionControlProjectInfo": {
      "type": "object",
      "properties": {
        "defaultSourceControlType": {
          "enum": [
            "tfvc",
            "git"
          ]
        },
        "project": {
          "$ref": "#/definitions/TeamProjectReference"
        },
        "supportsGit": {
          "type": "boolean"
        },
        "supportsTFVC": {
          "type": "boolean"
        }
      }
    },
    "VssJsonCollectionWrapper": {
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/VssJsonCollectionWrapperBase"
        }
      ],
      "properties": {
        "value": {
          "type": "string",
          "format": "T"
        }
      }
    },
    "VssJsonCollectionWrapperBase": {
      "type": "object",
      "properties": {
        "count": {
          "type": "integer",
          "format": "int32"
        }
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.code": "Grants the ability to read source code and metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to get notified about version control events via service hooks.",
        "vso.code_manage": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage code repositories, create and manage pull requests and code reviews, and to receive notifications about version control events via service hooks.",
        "vso.code_write": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage pull requests and code reviews and to receive notifications about version control events via service hooks.",
        "vso.code_status": "Grants the ability to read and write commit and pull request status."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}