{
  "swagger": "2.0",
  "info": {
    "title": "Npm",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.0"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "content"
    },
    {
      "name": "readme"
    },
    {
      "name": "versions"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/packaging/feeds/{feedId}/npm/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}": {
      "get": {
        "tags": [
          "versions"
        ],
        "summary": "GetScopedPackageInfo",
        "description": "",
        "operationId": "getScopedPackageInfo",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "versions"
        ],
        "summary": "UnpublishScopedPackage",
        "description": "",
        "operationId": "unpublishScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "versions"
        ],
        "summary": "UpdateScopedPackage",
        "description": "",
        "operationId": "updateScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/{packageName}/versions/{packageVersion}": {
      "get": {
        "tags": [
          "versions"
        ],
        "summary": "GetPackageInfo",
        "description": "",
        "operationId": "getPackageInfo",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "versions"
        ],
        "summary": "UnpublishPackage",
        "description": "",
        "operationId": "unpublishPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "versions"
        ],
        "summary": "UpdatePackage",
        "description": "",
        "operationId": "updatePackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}/content": {
      "get": {
        "tags": [
          "content"
        ],
        "summary": "GetContentScopedPackage",
        "description": "",
        "operationId": "getContentScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}/readme": {
      "get": {
        "tags": [
          "readme"
        ],
        "summary": "GetReadmeScopedPackage",
        "description": "",
        "operationId": "getReadmeScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/{packageName}/versions/{packageVersion}/content": {
      "get": {
        "tags": [
          "content"
        ],
        "summary": "GetContentUnscopedPackage",
        "description": "",
        "operationId": "getContentUnscopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/{packageName}/versions/{packageVersion}/readme": {
      "get": {
        "tags": [
          "readme"
        ],
        "summary": "GetReadmeUnscopedPackage",
        "description": "",
        "operationId": "getReadmeUnscopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.packaging": "Grants the ability to read feeds and packages.",
        "vso.packaging_manage": "Grants the ability to create, read, update, and delete feeds and packages."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}