{
  "swagger": "2.0",
  "info": {
    "title": "Release",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "agentartifacts"
    },
    {
      "name": "approvals"
    },
    {
      "name": "changes"
    },
    {
      "name": "continuousDeployment"
    },
    {
      "name": "definitionEnvironments"
    },
    {
      "name": "definitions"
    },
    {
      "name": "deployments"
    },
    {
      "name": "environments"
    },
    {
      "name": "environmenttemplates"
    },
    {
      "name": "favorites"
    },
    {
      "name": "folders"
    },
    {
      "name": "history"
    },
    {
      "name": "inputvaluesquery"
    },
    {
      "name": "ipAddress"
    },
    {
      "name": "logs"
    },
    {
      "name": "manualInterventions"
    },
    {
      "name": "metrics"
    },
    {
      "name": "projects"
    },
    {
      "name": "releases"
    },
    {
      "name": "releasesettings"
    },
    {
      "name": "revisions"
    },
    {
      "name": "sendmail"
    },
    {
      "name": "sourcebranches"
    },
    {
      "name": "tags"
    },
    {
      "name": "tasks"
    },
    {
      "name": "types"
    },
    {
      "name": "versions"
    },
    {
      "name": "workitems"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/release/ipaddress": {
      "get": {
        "tags": [
          "ipAddress"
        ],
        "summary": "GetIPAddress",
        "description": "",
        "operationId": "getIPAddress"
      }
    },
    "/_apis/release/ipaddress/{ipDetectionMethods}": {
      "get": {
        "tags": [
          "ipAddress"
        ],
        "summary": "GetSupportedIPDetectionMethods",
        "description": "Gets supported IP detection methods for request source",
        "operationId": "getSupportedIPDetectionMethods"
      }
    },
    "/_apis/release/projects": {
      "get": {
        "tags": [
          "projects"
        ],
        "summary": "GetReleaseProjects",
        "description": "",
        "operationId": "getReleaseProjects"
      }
    },
    "/_apis/release/releases": {
      "get": {
        "tags": [
          "releases"
        ],
        "summary": "GetReleases",
        "description": "",
        "operationId": "getReleases",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/approvals": {
      "get": {
        "tags": [
          "approvals"
        ],
        "summary": "GetApprovals",
        "description": "",
        "operationId": "getApprovals",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/approvals/{approvalId}": {
      "get": {
        "tags": [
          "approvals"
        ],
        "summary": "GetApproval",
        "description": "",
        "operationId": "getApproval",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "approvals"
        ],
        "summary": "UpdateReleaseApproval",
        "description": "",
        "operationId": "updateReleaseApproval",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/approvals/{approvalStepId}/history": {
      "get": {
        "tags": [
          "approvals"
        ],
        "summary": "GetApprovalHistory",
        "description": "",
        "operationId": "getApprovalHistory",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/artifacts/inputvaluesquery": {
      "post": {
        "tags": [
          "inputvaluesquery"
        ],
        "summary": "GetInputValues",
        "description": "",
        "operationId": "getInputValues"
      }
    },
    "/{project}/_apis/release/artifacts/types": {
      "get": {
        "tags": [
          "types"
        ],
        "summary": "GetArtifactTypeDefinitions",
        "description": "",
        "operationId": "getArtifactTypeDefinitions"
      }
    },
    "/{project}/_apis/release/artifacts/versions": {
      "get": {
        "tags": [
          "versions"
        ],
        "summary": "GetArtifactVersions",
        "description": "",
        "operationId": "getArtifactVersions"
      },
      "post": {
        "tags": [
          "versions"
        ],
        "summary": "GetArtifactVersionsForSources",
        "description": "",
        "operationId": "getArtifactVersionsForSources"
      }
    },
    "/{project}/_apis/release/continuousdeployment": {
      "post": {
        "tags": [
          "continuousDeployment"
        ],
        "summary": "SetupContinuousDeployment",
        "description": "",
        "operationId": "setupContinuousDeployment"
      }
    },
    "/{project}/_apis/release/definitionenvironments": {
      "get": {
        "tags": [
          "definitionEnvironments"
        ],
        "summary": "GetDefinitionEnvironments",
        "description": "",
        "operationId": "getDefinitionEnvironments"
      }
    },
    "/{project}/_apis/release/definitions": {
      "post": {
        "tags": [
          "definitions"
        ],
        "summary": "CreateReleaseDefinition",
        "description": "",
        "operationId": "createReleaseDefinition",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "definitions"
        ],
        "summary": "GetReleaseDefinitions",
        "description": "",
        "operationId": "getReleaseDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "definitions"
        ],
        "summary": "UpdateReleaseDefinition",
        "description": "",
        "operationId": "updateReleaseDefinition",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/definitions/{definitionId}": {
      "delete": {
        "tags": [
          "definitions"
        ],
        "summary": "DeleteReleaseDefinition",
        "description": "",
        "operationId": "deleteReleaseDefinition",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "definitions"
        ],
        "summary": "GetReleaseDefinition",
        "description": "",
        "operationId": "getReleaseDefinition",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/definitions/{definitionId}/revisions": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetReleaseDefinitionHistory",
        "description": "",
        "operationId": "getReleaseDefinitionHistory",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/definitions/{definitionId}/revisions/{revision}": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetDefinitionRevision",
        "description": "",
        "operationId": "getDefinitionRevision",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/definitions/{definitionId}/sourcebranches": {
      "get": {
        "tags": [
          "sourcebranches"
        ],
        "summary": "GetSourceBranches",
        "description": "",
        "operationId": "getSourceBranches",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/definitions/{releaseDefinitionId}/tags": {
      "post": {
        "tags": [
          "tags"
        ],
        "summary": "AddDefinitionTags",
        "description": "Adds multiple tags to a definition",
        "operationId": "addDefinitionTags",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "tags"
        ],
        "summary": "GetDefinitionTags",
        "description": "Gets the tags for a definition",
        "operationId": "getDefinitionTags",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/definitions/{releaseDefinitionId}/tags/{tag}": {
      "patch": {
        "tags": [
          "tags"
        ],
        "summary": "AddDefinitionTag",
        "description": "Adds a tag to a definition",
        "operationId": "addDefinitionTag"
      },
      "delete": {
        "tags": [
          "tags"
        ],
        "summary": "DeleteDefinitionTag",
        "description": "Deletes a tag from a definition",
        "operationId": "deleteDefinitionTag",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/definitions/environmenttemplates": {
      "post": {
        "tags": [
          "environmenttemplates"
        ],
        "summary": "CreateDefinitionEnvironmentTemplate",
        "description": "",
        "operationId": "createDefinitionEnvironmentTemplate",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "environmenttemplates"
        ],
        "summary": "DeleteDefinitionEnvironmentTemplate",
        "description": "",
        "operationId": "deleteDefinitionEnvironmentTemplate",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "environmenttemplates"
        ],
        "summary": "GetDefinitionEnvironmentTemplate",
        "description": "",
        "operationId": "getDefinitionEnvironmentTemplate",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/deployments": {
      "get": {
        "tags": [
          "deployments"
        ],
        "summary": "GetDeployments",
        "description": "",
        "operationId": "getDeployments",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "deployments"
        ],
        "summary": "GetDeploymentsForMultipleEnvironments",
        "description": "",
        "operationId": "getDeploymentsForMultipleEnvironments",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/favorites/{scope}": {
      "post": {
        "tags": [
          "favorites"
        ],
        "summary": "CreateFavorites",
        "description": "",
        "operationId": "createFavorites"
      },
      "delete": {
        "tags": [
          "favorites"
        ],
        "summary": "DeleteFavorites",
        "description": "",
        "operationId": "deleteFavorites"
      },
      "get": {
        "tags": [
          "favorites"
        ],
        "summary": "GetFavorites",
        "description": "",
        "operationId": "getFavorites"
      }
    },
    "/{project}/_apis/release/folders/{*path}": {
      "get": {
        "tags": [
          "folders"
        ],
        "summary": "GetFolders",
        "description": "Gets folders",
        "operationId": "getFolders"
      }
    },
    "/{project}/_apis/release/folders/{path}": {
      "post": {
        "tags": [
          "folders"
        ],
        "summary": "CreateFolder",
        "description": "Creates a new folder",
        "operationId": "createFolder"
      },
      "delete": {
        "tags": [
          "folders"
        ],
        "summary": "DeleteFolder",
        "description": "Deletes a definition folder for given folder name and path and all it's existing definitions",
        "operationId": "deleteFolder"
      },
      "patch": {
        "tags": [
          "folders"
        ],
        "summary": "UpdateFolder",
        "description": "Updates an existing folder at given  existing path",
        "operationId": "updateFolder"
      }
    },
    "/{project}/_apis/release/metrics": {
      "get": {
        "tags": [
          "metrics"
        ],
        "summary": "GetMetrics",
        "description": "",
        "operationId": "getMetrics"
      }
    },
    "/{project}/_apis/release/releases": {
      "get": {
        "tags": [
          "releases"
        ],
        "summary": "GetReleases",
        "description": "",
        "operationId": "getReleases",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "releases"
        ],
        "summary": "CreateRelease",
        "description": "",
        "operationId": "createRelease",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}": {
      "delete": {
        "tags": [
          "releases"
        ],
        "summary": "DeleteRelease",
        "description": "",
        "operationId": "deleteRelease",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "releases"
        ],
        "summary": "GetRelease",
        "description": "",
        "operationId": "getRelease",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "releases"
        ],
        "summary": "UndeleteRelease",
        "description": "",
        "operationId": "undeleteRelease",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "releases"
        ],
        "summary": "UpdateReleaseResource",
        "description": "",
        "operationId": "updateReleaseResource",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/agentartifacts": {
      "get": {
        "tags": [
          "agentartifacts"
        ],
        "summary": "GetAgentArtifactDefinitions",
        "description": "Returns the artifact details that automation agent requires",
        "operationId": "getAgentArtifactDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/changes": {
      "get": {
        "tags": [
          "changes"
        ],
        "summary": "GetReleaseChanges",
        "description": "",
        "operationId": "getReleaseChanges",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/releases/{releaseId}/environments/{environmentId}": {
      "get": {
        "tags": [
          "environments"
        ],
        "summary": "GetReleaseEnvironment",
        "description": "",
        "operationId": "getReleaseEnvironment",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "environments"
        ],
        "summary": "UpdateReleaseEnvironment",
        "description": "",
        "operationId": "updateReleaseEnvironment",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/environments/{environmentId}/deployPhases/{releaseDeployPhaseId}/tasks": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTasksForTaskGroup",
        "description": "",
        "operationId": "getTasksForTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/environments/{environmentId}/deployPhases/{releaseDeployPhaseId}/tasks/{taskId}/logs": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "GetTaskLog",
        "description": "",
        "operationId": "getTaskLog",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/environments/{environmentId}/tasks": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTasks",
        "description": "",
        "operationId": "getTasks",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/environments/{environmentId}/tasks/{taskId}/logs": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "GetLog",
        "description": "",
        "operationId": "getLog",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/releases/{releaseId}/history": {
      "get": {
        "tags": [
          "history"
        ],
        "summary": "GetReleaseHistory",
        "description": "",
        "operationId": "getReleaseHistory",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/logs": {
      "get": {
        "tags": [
          "logs"
        ],
        "summary": "GetLogs",
        "description": "",
        "operationId": "getLogs",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/releases/{releaseId}/manualinterventions": {
      "get": {
        "tags": [
          "manualInterventions"
        ],
        "summary": "GetManualInterventions",
        "description": "",
        "operationId": "getManualInterventions",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/Release/releases/{releaseId}/manualinterventions/{manualInterventionId}": {
      "get": {
        "tags": [
          "manualInterventions"
        ],
        "summary": "GetManualIntervention",
        "description": "",
        "operationId": "getManualIntervention",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "manualInterventions"
        ],
        "summary": "UpdateManualIntervention",
        "description": "",
        "operationId": "updateManualIntervention",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/tags": {
      "post": {
        "tags": [
          "tags"
        ],
        "summary": "AddReleaseTags",
        "description": "Adds tag to a release",
        "operationId": "addReleaseTags",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "tags"
        ],
        "summary": "GetReleaseTags",
        "description": "Gets the tags for a release",
        "operationId": "getReleaseTags",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/tags/{tag}": {
      "patch": {
        "tags": [
          "tags"
        ],
        "summary": "AddReleaseTag",
        "description": "Adds a tag to a releaseId",
        "operationId": "addReleaseTag",
        "security": [
          {
            "oauth2": [
              "vso.release_execute"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "tags"
        ],
        "summary": "DeleteReleaseTag",
        "description": "Deletes a tag from a release",
        "operationId": "deleteReleaseTag",
        "security": [
          {
            "oauth2": [
              "vso.release_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releases/{releaseId}/workitems": {
      "get": {
        "tags": [
          "workitems"
        ],
        "summary": "GetReleaseWorkItemsRefs",
        "description": "",
        "operationId": "getReleaseWorkItemsRefs",
        "security": [
          {
            "oauth2": [
              "vso.release"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/release/releasesettings": {
      "get": {
        "tags": [
          "releasesettings"
        ],
        "summary": "GetReleaseSettings",
        "description": "",
        "operationId": "getReleaseSettings"
      },
      "put": {
        "tags": [
          "releasesettings"
        ],
        "summary": "UpdateReleaseSettings",
        "description": "Updates the release settings",
        "operationId": "updateReleaseSettings"
      }
    },
    "/{project}/_apis/release/sendmail/{releaseId}": {
      "get": {
        "tags": [
          "sendmail"
        ],
        "summary": "GetSummaryMailSections",
        "description": "",
        "operationId": "getSummaryMailSections"
      },
      "post": {
        "tags": [
          "sendmail"
        ],
        "summary": "SendSummaryMail",
        "description": "",
        "operationId": "sendSummaryMail"
      }
    },
    "/{project}/_apis/release/tags": {
      "get": {
        "tags": [
          "tags"
        ],
        "summary": "GetTags",
        "description": "",
        "operationId": "getTags"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.release": "Grants the ability to read release artifacts, including releases, release definitions and release environment.",
        "vso.release_execute": "Grants the ability to read and update release artifacts, including releases, release definitions and release envrionment, and the ability to queue a new release.",
        "vso.release_manage": "Grants the ability to read, update and delete release artifacts, including releases, release definitions and release envrionment, and the ability to queue and approve a new release."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}