{
  "swagger": "2.0",
  "info": {
    "title": "TaskAgent",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "agents"
    },
    {
      "name": "azurermsubscriptions"
    },
    {
      "name": "deploymentgroupaccesstoken"
    },
    {
      "name": "deploymentgroups"
    },
    {
      "name": "endpoint"
    },
    {
      "name": "hublicense"
    },
    {
      "name": "icon"
    },
    {
      "name": "inputvalidation"
    },
    {
      "name": "jobrequests"
    },
    {
      "name": "machinegroupaccesstoken"
    },
    {
      "name": "machinegroups"
    },
    {
      "name": "machines"
    },
    {
      "name": "maintenancedefinitions"
    },
    {
      "name": "maintenancejobs"
    },
    {
      "name": "messages"
    },
    {
      "name": "packages"
    },
    {
      "name": "poolroles"
    },
    {
      "name": "pools"
    },
    {
      "name": "queueroles"
    },
    {
      "name": "queues"
    },
    {
      "name": "revisions"
    },
    {
      "name": "securefiles"
    },
    {
      "name": "serviceendpointproxy"
    },
    {
      "name": "serviceendpoints"
    },
    {
      "name": "serviceendpointtypes"
    },
    {
      "name": "sessions"
    },
    {
      "name": "taskgroups"
    },
    {
      "name": "tasks"
    },
    {
      "name": "updates"
    },
    {
      "name": "usercapabilities"
    },
    {
      "name": "variablegroups"
    },
    {
      "name": "vstsaadoauth"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/distributedtask/endpoint": {
      "post": {
        "tags": [
          "endpoint"
        ],
        "summary": "QueryEndpoint",
        "description": "Proxy for a GET request defined by an 'endpoint'. The request is authorized using a service connection. The response is filtered using an XPath/Json based selector.",
        "operationId": "queryEndpoint"
      }
    },
    "/_apis/distributedtask/hublicense/{hubName}": {
      "get": {
        "tags": [
          "hublicense"
        ],
        "summary": "GetTaskHubLicenseDetails",
        "description": "",
        "operationId": "getTaskHubLicenseDetails"
      },
      "put": {
        "tags": [
          "hublicense"
        ],
        "summary": "UpdateTaskHubLicenseDetails",
        "description": "",
        "operationId": "updateTaskHubLicenseDetails"
      }
    },
    "/_apis/distributedtask/inputvalidation": {
      "post": {
        "tags": [
          "inputvalidation"
        ],
        "summary": "ValidateInputs",
        "description": "",
        "operationId": "validateInputs"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackages",
        "description": "",
        "operationId": "getPackages"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}/{version}": {
      "get": {
        "tags": [
          "packages"
        ],
        "summary": "GetPackage",
        "description": "",
        "operationId": "getPackage"
      }
    },
    "/_apis/distributedtask/poolroles/{poolId}": {
      "get": {
        "tags": [
          "poolroles"
        ],
        "summary": "GetAgentPoolRoles",
        "description": "",
        "operationId": "getAgentPoolRoles"
      }
    },
    "/_apis/distributedtask/pools": {
      "post": {
        "tags": [
          "pools"
        ],
        "summary": "AddAgentPool",
        "description": "",
        "operationId": "addAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pools"
        ],
        "summary": "GetAgentPools",
        "description": "",
        "operationId": "getAgentPools",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}": {
      "delete": {
        "tags": [
          "pools"
        ],
        "summary": "DeleteAgentPool",
        "description": "",
        "operationId": "deleteAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "pools"
        ],
        "summary": "GetAgentPool",
        "description": "",
        "operationId": "getAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "pools"
        ],
        "summary": "UpdateAgentPool",
        "description": "",
        "operationId": "updateAgentPool",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents": {
      "post": {
        "tags": [
          "agents"
        ],
        "summary": "AddAgent",
        "description": "",
        "operationId": "addAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "agents"
        ],
        "summary": "GetAgents",
        "description": "",
        "operationId": "getAgents",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}": {
      "delete": {
        "tags": [
          "agents"
        ],
        "summary": "DeleteAgent",
        "description": "",
        "operationId": "deleteAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "agents"
        ],
        "summary": "GetAgent",
        "description": "",
        "operationId": "getAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "agents"
        ],
        "summary": "ReplaceAgent",
        "description": "",
        "operationId": "replaceAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "agents"
        ],
        "summary": "UpdateAgent",
        "description": "",
        "operationId": "updateAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/updates": {
      "put": {
        "tags": [
          "updates"
        ],
        "summary": "UpdateAgentUpdateState",
        "description": "",
        "operationId": "updateAgentUpdateState",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/usercapabilities": {
      "put": {
        "tags": [
          "usercapabilities"
        ],
        "summary": "UpdateAgentUserCapabilities",
        "description": "",
        "operationId": "updateAgentUserCapabilities",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests": {
      "get": {
        "tags": [
          "jobrequests"
        ],
        "summary": "GetAgentRequestsForAgent",
        "description": "",
        "operationId": "getAgentRequestsForAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "jobrequests"
        ],
        "summary": "QueueAgentRequest",
        "description": "",
        "operationId": "queueAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests/{requestId}": {
      "delete": {
        "tags": [
          "jobrequests"
        ],
        "summary": "DeleteAgentRequest",
        "description": "",
        "operationId": "deleteAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "jobrequests"
        ],
        "summary": "GetAgentRequest",
        "description": "",
        "operationId": "getAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "jobrequests"
        ],
        "summary": "UpdateAgentRequest",
        "description": "",
        "operationId": "updateAgentRequest",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions": {
      "post": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "CreateAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "createAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "GetAgentPoolMaintenanceDefinitions",
        "description": "",
        "operationId": "getAgentPoolMaintenanceDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions/{definitionId}": {
      "delete": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "DeleteAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "deleteAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "GetAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "getAgentPoolMaintenanceDefinition",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "maintenancedefinitions"
        ],
        "summary": "UpdateAgentPoolMaintenanceDefinition",
        "description": "",
        "operationId": "updateAgentPoolMaintenanceDefinition"
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs": {
      "get": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "GetAgentPoolMaintenanceJobs",
        "description": "",
        "operationId": "getAgentPoolMaintenanceJobs",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "QueueAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "queueAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs/{jobId}": {
      "delete": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "DeleteAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "deleteAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "GetAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "getAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "maintenancejobs"
        ],
        "summary": "UpdateAgentPoolMaintenanceJob",
        "description": "",
        "operationId": "updateAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages": {
      "get": {
        "tags": [
          "messages"
        ],
        "summary": "GetMessage",
        "description": "",
        "operationId": "getMessage",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "messages"
        ],
        "summary": "RefreshAgent",
        "description": "",
        "operationId": "refreshAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages/{messageId}": {
      "delete": {
        "tags": [
          "messages"
        ],
        "summary": "DeleteMessage",
        "description": "",
        "operationId": "deleteMessage",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions": {
      "post": {
        "tags": [
          "sessions"
        ],
        "summary": "CreateAgentSession",
        "description": "",
        "operationId": "createAgentSession",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions/{sessionId}": {
      "delete": {
        "tags": [
          "sessions"
        ],
        "summary": "DeleteAgentSession",
        "description": "",
        "operationId": "deleteAgentSession",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/queueroles/{queueId}": {
      "get": {
        "tags": [
          "queueroles"
        ],
        "summary": "GetAgentQueueRoles",
        "description": "",
        "operationId": "getAgentQueueRoles"
      }
    },
    "/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "queues"
        ],
        "summary": "AddAgentQueue",
        "description": "",
        "operationId": "addAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "queues"
        ],
        "summary": "CreateTeamProject",
        "description": "",
        "operationId": "createTeamProject"
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueues",
        "description": "",
        "operationId": "getAgentQueues",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "queues"
        ],
        "summary": "DeleteAgentQueue",
        "description": "",
        "operationId": "deleteAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueue",
        "description": "",
        "operationId": "getAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/azurermsubscriptions": {
      "get": {
        "tags": [
          "azurermsubscriptions"
        ],
        "summary": "GetAzureSubscriptions",
        "description": "",
        "operationId": "getAzureSubscriptions"
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/vstsaadoauth": {
      "post": {
        "tags": [
          "vstsaadoauth"
        ],
        "summary": "AcquireAccessToken",
        "description": "",
        "operationId": "acquireAccessToken"
      },
      "get": {
        "tags": [
          "vstsaadoauth"
        ],
        "summary": "GetVstsAadTenantId",
        "description": "",
        "operationId": "getVstsAadTenantId"
      }
    },
    "/_apis/distributedtask/serviceendpointtypes": {
      "get": {
        "tags": [
          "serviceendpointtypes"
        ],
        "summary": "GetServiceEndpointTypes",
        "description": "",
        "operationId": "getServiceEndpointTypes",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}": {
      "delete": {
        "tags": [
          "tasks"
        ],
        "summary": "DeleteTaskDefinition",
        "description": "",
        "operationId": "deleteTaskDefinition"
      },
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTaskDefinitions",
        "description": "",
        "operationId": "getTaskDefinitions",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}": {
      "get": {
        "tags": [
          "tasks"
        ],
        "summary": "GetTaskContentZip",
        "description": "",
        "operationId": "getTaskContentZip",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}/icon": {
      "get": {
        "tags": [
          "icon"
        ],
        "summary": "GetTaskIcon",
        "description": "",
        "operationId": "getTaskIcon",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroupaccesstoken/{deploymentGroupId}": {
      "post": {
        "tags": [
          "deploymentgroupaccesstoken"
        ],
        "summary": "GenerateDeploymentGroupAccessToken",
        "description": "",
        "operationId": "generateDeploymentGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups": {
      "post": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "AddDeploymentGroup",
        "description": "",
        "operationId": "addDeploymentGroup"
      },
      "get": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "GetDeploymentGroups",
        "description": "",
        "operationId": "getDeploymentGroups"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}": {
      "delete": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "DeleteDeploymentGroup",
        "description": "",
        "operationId": "deleteDeploymentGroup"
      },
      "get": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "GetDeploymentGroup",
        "description": "",
        "operationId": "getDeploymentGroup"
      },
      "patch": {
        "tags": [
          "deploymentgroups"
        ],
        "summary": "UpdateDeploymentGroup",
        "description": "",
        "operationId": "updateDeploymentGroup"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines": {
      "get": {
        "tags": [
          "machines"
        ],
        "summary": "GetDeploymentMachines",
        "description": "",
        "operationId": "getDeploymentMachines"
      },
      "patch": {
        "tags": [
          "machines"
        ],
        "summary": "UpdateDeploymentMachines",
        "description": "",
        "operationId": "updateDeploymentMachines"
      }
    },
    "/{project}/_apis/distributedtask/machinegroupaccesstoken/{machineGroupId}": {
      "post": {
        "tags": [
          "machinegroupaccesstoken"
        ],
        "summary": "GenerateDeploymentMachineGroupAccessToken",
        "description": "",
        "operationId": "generateDeploymentMachineGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups": {
      "post": {
        "tags": [
          "machinegroups"
        ],
        "summary": "AddDeploymentMachineGroup",
        "description": "",
        "operationId": "addDeploymentMachineGroup"
      },
      "get": {
        "tags": [
          "machinegroups"
        ],
        "summary": "GetDeploymentMachineGroups",
        "description": "",
        "operationId": "getDeploymentMachineGroups"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}": {
      "delete": {
        "tags": [
          "machinegroups"
        ],
        "summary": "DeleteDeploymentMachineGroup",
        "description": "",
        "operationId": "deleteDeploymentMachineGroup"
      },
      "get": {
        "tags": [
          "machinegroups"
        ],
        "summary": "GetDeploymentMachineGroup",
        "description": "",
        "operationId": "getDeploymentMachineGroup"
      },
      "patch": {
        "tags": [
          "machinegroups"
        ],
        "summary": "UpdateDeploymentMachineGroup",
        "description": "",
        "operationId": "updateDeploymentMachineGroup"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}/machines": {
      "get": {
        "tags": [
          "machines"
        ],
        "summary": "GetDeploymentMachineGroupMachines",
        "description": "",
        "operationId": "getDeploymentMachineGroupMachines"
      },
      "patch": {
        "tags": [
          "machines"
        ],
        "summary": "UpdateDeploymentMachineGroupMachines",
        "description": "",
        "operationId": "updateDeploymentMachineGroupMachines"
      }
    },
    "/{project}/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "queues"
        ],
        "summary": "AddAgentQueue",
        "description": "",
        "operationId": "addAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "queues"
        ],
        "summary": "CreateTeamProject",
        "description": "",
        "operationId": "createTeamProject"
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueues",
        "description": "",
        "operationId": "getAgentQueues",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "queues"
        ],
        "summary": "DeleteAgentQueue",
        "description": "",
        "operationId": "deleteAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queues"
        ],
        "summary": "GetAgentQueue",
        "description": "",
        "operationId": "getAgentQueue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/securefiles": {
      "get": {
        "tags": [
          "securefiles"
        ],
        "summary": "GetSecureFiles",
        "description": "Get secure files",
        "operationId": "getSecureFiles"
      },
      "post": {
        "tags": [
          "securefiles"
        ],
        "summary": "QuerySecureFilesByProperties",
        "description": "Query secure files using a name pattern and a condition on file properties.",
        "operationId": "querySecureFilesByProperties"
      },
      "patch": {
        "tags": [
          "securefiles"
        ],
        "summary": "UpdateSecureFiles",
        "description": "Update properties and/or names of a set of secure files. Files are identified by their IDs. Properties provided override the existing one entirely, i.e. do not merge.",
        "operationId": "updateSecureFiles"
      }
    },
    "/{project}/_apis/distributedtask/securefiles/{secureFileId}": {
      "delete": {
        "tags": [
          "securefiles"
        ],
        "summary": "DeleteSecureFile",
        "description": "Delete a secure file",
        "operationId": "deleteSecureFile"
      },
      "get": {
        "tags": [
          "securefiles"
        ],
        "summary": "DownloadSecureFile",
        "description": "Download a secure file by Id",
        "operationId": "downloadSecureFile"
      },
      "patch": {
        "tags": [
          "securefiles"
        ],
        "summary": "UpdateSecureFile",
        "description": "Update the name or properties of an existing secure file",
        "operationId": "updateSecureFile"
      }
    },
    "/{project}/_apis/distributedtask/serviceendpointproxy": {
      "post": {
        "tags": [
          "serviceendpointproxy"
        ],
        "summary": "ExecuteServiceEndpointRequest",
        "description": "",
        "operationId": "executeServiceEndpointRequest",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_query"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints": {
      "post": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "CreateServiceEndpoint",
        "description": "",
        "operationId": "createServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "GetServiceEndpoints",
        "description": "",
        "operationId": "getServiceEndpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}": {
      "delete": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "DeleteServiceEndpoint",
        "description": "",
        "operationId": "deleteServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "GetServiceEndpointDetails",
        "description": "",
        "operationId": "getServiceEndpointDetails",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "serviceendpoints"
        ],
        "summary": "UpdateServiceEndpoint",
        "description": "",
        "operationId": "updateServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups": {
      "post": {
        "tags": [
          "taskgroups"
        ],
        "summary": "AddTaskGroup",
        "description": "",
        "operationId": "addTaskGroup"
      },
      "put": {
        "tags": [
          "taskgroups"
        ],
        "summary": "UpdateTaskGroup",
        "description": "",
        "operationId": "updateTaskGroup"
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}": {
      "delete": {
        "tags": [
          "taskgroups"
        ],
        "summary": "DeleteTaskGroup",
        "description": "",
        "operationId": "deleteTaskGroup"
      },
      "get": {
        "tags": [
          "taskgroups"
        ],
        "summary": "GetTaskGroupRevision",
        "description": "",
        "operationId": "getTaskGroupRevision"
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}/revisions": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetTaskGroupHistory",
        "description": "",
        "operationId": "getTaskGroupHistory"
      }
    },
    "/{project}/_apis/distributedtask/variablegroups": {
      "post": {
        "tags": [
          "variablegroups"
        ],
        "summary": "AddVariableGroup",
        "description": "",
        "operationId": "addVariableGroup"
      },
      "get": {
        "tags": [
          "variablegroups"
        ],
        "summary": "GetVariableGroups",
        "description": "",
        "operationId": "getVariableGroups"
      }
    },
    "/{project}/_apis/distributedtask/variablegroups/{groupId}": {
      "delete": {
        "tags": [
          "variablegroups"
        ],
        "summary": "DeleteVariableGroup",
        "description": "",
        "operationId": "deleteVariableGroup"
      },
      "get": {
        "tags": [
          "variablegroups"
        ],
        "summary": "GetVariableGroup",
        "description": "",
        "operationId": "getVariableGroup"
      },
      "put": {
        "tags": [
          "variablegroups"
        ],
        "summary": "UpdateVariableGroup",
        "description": "",
        "operationId": "updateVariableGroup"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.agentpools": "Grants the ability to view tasks, pools, queues, agents, and currently running or recently completed jobs for agents",
        "vso.agentpools_manage": "Grants the ability to manage pools, queues, and agents",
        "vso.serviceendpoint": "Grants the ability to read service endpoints.",
        "vso.serviceendpoint_manage": "Grants the ability to read, query and manage service endpoints.",
        "vso.serviceendpoint_query": "Grants the ability to read and query service endpoints."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}