{
  "swagger": "2.0",
  "info": {
    "title": "Test",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "actionResults"
    },
    {
      "name": "attachments"
    },
    {
      "name": "bugs"
    },
    {
      "name": "cloneOperation"
    },
    {
      "name": "codeCoverage"
    },
    {
      "name": "configurations"
    },
    {
      "name": "extensionFields"
    },
    {
      "name": "history"
    },
    {
      "name": "iterations"
    },
    {
      "name": "linkedWorkItemsQuery"
    },
    {
      "name": "messageLogs"
    },
    {
      "name": "parameterResults"
    },
    {
      "name": "plans"
    },
    {
      "name": "points"
    },
    {
      "name": "resultDetailsByBuild"
    },
    {
      "name": "resultDetailsByRelease"
    },
    {
      "name": "resultDocument"
    },
    {
      "name": "resultRetentionSettings"
    },
    {
      "name": "results"
    },
    {
      "name": "resultSummaryByBuild"
    },
    {
      "name": "resultSummaryByRelease"
    },
    {
      "name": "resultSummaryByRequirement"
    },
    {
      "name": "resultTrendByBuild"
    },
    {
      "name": "resultTrendByRelease"
    },
    {
      "name": "runs"
    },
    {
      "name": "session"
    },
    {
      "name": "sharedParameter"
    },
    {
      "name": "sharedStep"
    },
    {
      "name": "suiteEntry"
    },
    {
      "name": "suites"
    },
    {
      "name": "testCases"
    },
    {
      "name": "testSettings"
    },
    {
      "name": "variables"
    },
    {
      "name": "workItems"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/test/suites": {
      "get": {
        "tags": [
          "suites"
        ],
        "summary": "GetSuitesByTestCaseId",
        "description": "",
        "operationId": "getSuitesByTestCaseId",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/cloneoperation/{cloneOperationId}": {
      "get": {
        "tags": [
          "cloneOperation"
        ],
        "summary": "GetCloneInformation",
        "description": "",
        "operationId": "getCloneInformation",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/codecoverage": {
      "get": {
        "tags": [
          "codeCoverage"
        ],
        "summary": "GetBuildCodeCoverage",
        "description": "",
        "operationId": "getBuildCodeCoverage",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "codeCoverage"
        ],
        "summary": "UpdateCodeCoverageSummary",
        "description": "http://(tfsserver):8080/tfs/DefaultCollection/_apis/test/CodeCoverage?buildId=10 Request: Json of code coverage summary",
        "operationId": "updateCodeCoverageSummary",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/configurations": {
      "post": {
        "tags": [
          "configurations"
        ],
        "summary": "CreateTestConfiguration",
        "description": "",
        "operationId": "createTestConfiguration",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "configurations"
        ],
        "summary": "GetTestConfigurations",
        "description": "",
        "operationId": "getTestConfigurations",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/configurations/{testConfigurationId}": {
      "delete": {
        "tags": [
          "configurations"
        ],
        "summary": "DeleteTestConfiguration",
        "description": "",
        "operationId": "deleteTestConfiguration",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "configurations"
        ],
        "summary": "GetTestConfigurationById",
        "description": "",
        "operationId": "getTestConfigurationById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "configurations"
        ],
        "summary": "UpdateTestConfiguration",
        "description": "",
        "operationId": "updateTestConfiguration",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/extensionfields": {
      "post": {
        "tags": [
          "extensionFields"
        ],
        "summary": "AddCustomFields",
        "description": "",
        "operationId": "addCustomFields",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "extensionFields"
        ],
        "summary": "QueryCustomFields",
        "description": "",
        "operationId": "queryCustomFields",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/linkedworkitemsquery": {
      "post": {
        "tags": [
          "linkedWorkItemsQuery"
        ],
        "summary": "GetLinkedWorkItemsByQuery",
        "description": "",
        "operationId": "getLinkedWorkItemsByQuery"
      }
    },
    "/{project}/_apis/test/plans": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "CreateTestPlan",
        "description": "",
        "operationId": "createTestPlan",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlans",
        "description": "",
        "operationId": "getPlans",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/plans/{planId}": {
      "delete": {
        "tags": [
          "plans"
        ],
        "summary": "DeleteTestPlan",
        "description": "",
        "operationId": "deleteTestPlan",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlanById",
        "description": "",
        "operationId": "getPlanById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "plans"
        ],
        "summary": "UpdateTestPlan",
        "description": "",
        "operationId": "updateTestPlan",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/cloneoperation": {
      "post": {
        "tags": [
          "cloneOperation"
        ],
        "summary": "CloneTestPlan",
        "description": "",
        "operationId": "cloneTestPlan",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/suites": {
      "get": {
        "tags": [
          "suites"
        ],
        "summary": "GetTestSuitesForPlan",
        "description": "",
        "operationId": "getTestSuitesForPlan",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/Suites/{sourceSuiteId}/cloneoperation": {
      "post": {
        "tags": [
          "cloneOperation"
        ],
        "summary": "CloneTestSuite",
        "description": "",
        "operationId": "cloneTestSuite",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/suites/{suiteId}": {
      "post": {
        "tags": [
          "suites"
        ],
        "summary": "CreateTestSuite",
        "description": "",
        "operationId": "createTestSuite",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "suites"
        ],
        "summary": "DeleteTestSuite",
        "description": "",
        "operationId": "deleteTestSuite",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "suites"
        ],
        "summary": "GetTestSuiteById",
        "description": "",
        "operationId": "getTestSuiteById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "suites"
        ],
        "summary": "UpdateTestSuite",
        "description": "",
        "operationId": "updateTestSuite",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/Suites/{suiteId}/points": {
      "get": {
        "tags": [
          "points"
        ],
        "summary": "GetPoints",
        "description": "",
        "operationId": "getPoints",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/Suites/{suiteId}/points/{pointIds}": {
      "get": {
        "tags": [
          "points"
        ],
        "summary": "GetPoint",
        "description": "",
        "operationId": "getPoint",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "points"
        ],
        "summary": "UpdateTestPoints",
        "description": "",
        "operationId": "updateTestPoints",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/suites/{suiteId}/testcases": {
      "get": {
        "tags": [
          "suites"
        ],
        "summary": "GetTestCases",
        "description": "",
        "operationId": "getTestCases",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Plans/{planId}/suites/{suiteId}/testcases/{testCaseIds}": {
      "post": {
        "tags": [
          "suites"
        ],
        "summary": "AddTestCasesToSuite",
        "description": "",
        "operationId": "addTestCasesToSuite",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "suites"
        ],
        "summary": "GetTestCaseById",
        "description": "",
        "operationId": "getTestCaseById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "suites"
        ],
        "summary": "RemoveTestCasesFromSuiteUrl",
        "description": "",
        "operationId": "removeTestCasesFromSuiteUrl",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/points": {
      "post": {
        "tags": [
          "points"
        ],
        "summary": "GetPointsByQuery",
        "description": "",
        "operationId": "getPointsByQuery",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultdetailsbybuild": {
      "get": {
        "tags": [
          "resultDetailsByBuild"
        ],
        "summary": "GetTestResultDetailsForBuild",
        "description": "",
        "operationId": "getTestResultDetailsForBuild",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultdetailsbyrelease": {
      "get": {
        "tags": [
          "resultDetailsByRelease"
        ],
        "summary": "GetTestResultDetailsForRelease",
        "description": "",
        "operationId": "getTestResultDetailsForRelease",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultretentionsettings": {
      "get": {
        "tags": [
          "resultRetentionSettings"
        ],
        "summary": "GetResultRetentionSettings",
        "description": "",
        "operationId": "getResultRetentionSettings",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "resultRetentionSettings"
        ],
        "summary": "UpdateResultRetentionSettings",
        "description": "",
        "operationId": "updateResultRetentionSettings",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/results": {
      "post": {
        "tags": [
          "results"
        ],
        "summary": "GetTestResultsByQuery",
        "description": "",
        "operationId": "getTestResultsByQuery",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Results/history": {
      "post": {
        "tags": [
          "history"
        ],
        "summary": "QueryTestResultHistory",
        "description": "",
        "operationId": "queryTestResultHistory",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Results/workitems": {
      "get": {
        "tags": [
          "workItems"
        ],
        "summary": "QueryTestResultWorkItems",
        "description": "",
        "operationId": "queryTestResultWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultsummarybybuild": {
      "get": {
        "tags": [
          "resultSummaryByBuild"
        ],
        "summary": "QueryTestResultsReportForBuild",
        "description": "",
        "operationId": "queryTestResultsReportForBuild",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultsummarybyrelease": {
      "get": {
        "tags": [
          "resultSummaryByRelease"
        ],
        "summary": "QueryTestResultsReportForRelease",
        "description": "",
        "operationId": "queryTestResultsReportForRelease",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "resultSummaryByRelease"
        ],
        "summary": "QueryTestResultsSummaryForReleases",
        "description": "",
        "operationId": "queryTestResultsSummaryForReleases",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resultsummarybyrequirement": {
      "post": {
        "tags": [
          "resultSummaryByRequirement"
        ],
        "summary": "QueryTestSummaryByRequirement",
        "description": "",
        "operationId": "queryTestSummaryByRequirement",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/resulttrendbybuild": {
      "post": {
        "tags": [
          "resultTrendByBuild"
        ],
        "summary": "QueryResultTrendForBuild",
        "description": "",
        "operationId": "queryResultTrendForBuild"
      }
    },
    "/{project}/_apis/test/resulttrendbyrelease": {
      "post": {
        "tags": [
          "resultTrendByRelease"
        ],
        "summary": "QueryResultTrendForRelease",
        "description": "",
        "operationId": "queryResultTrendForRelease"
      }
    },
    "/{project}/_apis/test/runs": {
      "post": {
        "tags": [
          "runs"
        ],
        "summary": "CreateTestRun",
        "description": "",
        "operationId": "createTestRun",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "runs"
        ],
        "summary": "GetTestRuns",
        "description": "",
        "operationId": "getTestRuns",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/runs/{runId}": {
      "delete": {
        "tags": [
          "runs"
        ],
        "summary": "DeleteTestRun",
        "description": "",
        "operationId": "deleteTestRun",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "runs"
        ],
        "summary": "GetTestRunById",
        "description": "",
        "operationId": "getTestRunById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "runs"
        ],
        "summary": "UpdateTestRun",
        "description": "",
        "operationId": "updateTestRun",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/attachments": {
      "post": {
        "tags": [
          "attachments"
        ],
        "summary": "CreateTestRunAttachment",
        "description": "",
        "operationId": "createTestRunAttachment",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetTestRunAttachments",
        "description": "Returns attachment references for test run.",
        "operationId": "getTestRunAttachments",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/attachments/{attachmentId}": {
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetTestRunAttachmentContent",
        "description": "Returns a test run attachment",
        "operationId": "getTestRunAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/codecoverage": {
      "get": {
        "tags": [
          "codeCoverage"
        ],
        "summary": "GetTestRunCodeCoverage",
        "description": "",
        "operationId": "getTestRunCodeCoverage",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/messagelogs": {
      "get": {
        "tags": [
          "messageLogs"
        ],
        "summary": "GetTestRunLogs",
        "description": "",
        "operationId": "getTestRunLogs",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/resultdocument": {
      "post": {
        "tags": [
          "resultDocument"
        ],
        "summary": "PublishTestResultDocument",
        "description": "",
        "operationId": "publishTestResultDocument",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/results": {
      "post": {
        "tags": [
          "results"
        ],
        "summary": "AddTestResultsToTestRun",
        "description": "",
        "operationId": "addTestResultsToTestRun",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "results"
        ],
        "summary": "GetTestResults",
        "description": "",
        "operationId": "getTestResults",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "results"
        ],
        "summary": "UpdateTestResults",
        "description": "",
        "operationId": "updateTestResults",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/results/{testCaseResultId}": {
      "get": {
        "tags": [
          "results"
        ],
        "summary": "GetTestResultById",
        "description": "",
        "operationId": "getTestResultById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/attachments": {
      "post": {
        "tags": [
          "attachments"
        ],
        "summary": "CreateTestIterationResultAttachment",
        "description": "",
        "operationId": "createTestIterationResultAttachment",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetTestResultAttachments",
        "description": "Returns attachment references for test result.",
        "operationId": "getTestResultAttachments",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/attachments/{attachmentId}": {
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetTestResultAttachmentContent",
        "description": "Returns a test result attachment",
        "operationId": "getTestResultAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/bugs": {
      "get": {
        "tags": [
          "bugs"
        ],
        "summary": "GetBugsLinkedToTestResult",
        "description": "",
        "operationId": "getBugsLinkedToTestResult",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/iterations": {
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTestIterations",
        "description": "",
        "operationId": "getTestIterations",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/iterations/{iterationId}": {
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTestIteration",
        "description": "",
        "operationId": "getTestIteration",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/Iterations/{iterationId}/actionresults/{actionPath}": {
      "get": {
        "tags": [
          "actionResults"
        ],
        "summary": "GetActionResults",
        "description": "",
        "operationId": "getActionResults",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/Runs/{runId}/Results/{testCaseResultId}/Iterations/{iterationId}/parameterresults": {
      "get": {
        "tags": [
          "parameterResults"
        ],
        "summary": "GetResultParameters",
        "description": "",
        "operationId": "getResultParameters",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/runs/{runId}/Statistics": {
      "get": {
        "tags": [
          "runs"
        ],
        "summary": "GetTestRunStatistics",
        "description": "",
        "operationId": "getTestRunStatistics",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/session": {
      "post": {
        "tags": [
          "session"
        ],
        "summary": "CreateTestSession",
        "description": "",
        "operationId": "createTestSession",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "session"
        ],
        "summary": "GetTestSessions",
        "description": "",
        "operationId": "getTestSessions",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "session"
        ],
        "summary": "UpdateTestSession",
        "description": "",
        "operationId": "updateTestSession",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/sharedparameter/{sharedParameterId}": {
      "delete": {
        "tags": [
          "sharedParameter"
        ],
        "summary": "DeleteSharedParameter",
        "description": "",
        "operationId": "deleteSharedParameter"
      }
    },
    "/{project}/_apis/test/sharedstep/{sharedStepId}": {
      "delete": {
        "tags": [
          "sharedStep"
        ],
        "summary": "DeleteSharedStep",
        "description": "",
        "operationId": "deleteSharedStep"
      }
    },
    "/{project}/_apis/test/suiteentry/{suiteId}": {
      "get": {
        "tags": [
          "suiteEntry"
        ],
        "summary": "GetSuiteEntries",
        "description": "",
        "operationId": "getSuiteEntries",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "suiteEntry"
        ],
        "summary": "ReorderSuiteEntries",
        "description": "",
        "operationId": "reorderSuiteEntries",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/testcases/{testCaseId}": {
      "delete": {
        "tags": [
          "testCases"
        ],
        "summary": "DeleteTestCase",
        "description": "",
        "operationId": "deleteTestCase"
      }
    },
    "/{project}/_apis/test/TestMethods/{testName}/workitems": {
      "post": {
        "tags": [
          "workItems"
        ],
        "summary": "QueryTestMethodLinkedWorkItems",
        "description": "",
        "operationId": "queryTestMethodLinkedWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/TestMethods/{testName}/workitems/{workItemId}": {
      "delete": {
        "tags": [
          "workItems"
        ],
        "summary": "DeleteTestMethodToWorkItemLink",
        "description": "",
        "operationId": "deleteTestMethodToWorkItemLink",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/TestMethods/workitems": {
      "post": {
        "tags": [
          "workItems"
        ],
        "summary": "AddWorkItemToTestLinks",
        "description": "",
        "operationId": "addWorkItemToTestLinks",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/testsettings": {
      "post": {
        "tags": [
          "testSettings"
        ],
        "summary": "CreateTestSettings",
        "description": "",
        "operationId": "createTestSettings",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/testsettings/{testSettingsId}": {
      "delete": {
        "tags": [
          "testSettings"
        ],
        "summary": "DeleteTestSettings",
        "description": "",
        "operationId": "deleteTestSettings",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "testSettings"
        ],
        "summary": "GetTestSettingsById",
        "description": "",
        "operationId": "getTestSettingsById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/variables": {
      "post": {
        "tags": [
          "variables"
        ],
        "summary": "CreateTestVariable",
        "description": "",
        "operationId": "createTestVariable",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "variables"
        ],
        "summary": "GetTestVariables",
        "description": "",
        "operationId": "getTestVariables",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/test/variables/{testVariableId}": {
      "delete": {
        "tags": [
          "variables"
        ],
        "summary": "DeleteTestVariable",
        "description": "",
        "operationId": "deleteTestVariable",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "variables"
        ],
        "summary": "GetTestVariableById",
        "description": "",
        "operationId": "getTestVariableById",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "variables"
        ],
        "summary": "UpdateTestVariable",
        "description": "",
        "operationId": "updateTestVariable",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/test/session": {
      "post": {
        "tags": [
          "session"
        ],
        "summary": "CreateTestSession",
        "description": "",
        "operationId": "createTestSession",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "session"
        ],
        "summary": "GetTestSessions",
        "description": "",
        "operationId": "getTestSessions",
        "security": [
          {
            "oauth2": [
              "vso.test"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "session"
        ],
        "summary": "UpdateTestSession",
        "description": "",
        "operationId": "updateTestSession",
        "security": [
          {
            "oauth2": [
              "vso.test_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.test_write": "Grants the ability to read, create, and update test plans, cases, results and other test management related artifacts.",
        "vso.test": "Grants the ability to read test plans, cases, results and other test management related artifacts."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}