{
  "swagger": "2.0",
  "info": {
    "title": "Tfvc",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "branches"
    },
    {
      "name": "changesetChanges"
    },
    {
      "name": "changesets"
    },
    {
      "name": "changesetsBatch"
    },
    {
      "name": "changesetWorkItems"
    },
    {
      "name": "itemBatch"
    },
    {
      "name": "items"
    },
    {
      "name": "labelItems"
    },
    {
      "name": "labels"
    },
    {
      "name": "shelvesetChanges"
    },
    {
      "name": "shelvesets"
    },
    {
      "name": "shelvesetWorkItems"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/tfvc/branches": {
      "get": {
        "tags": [
          "branches"
        ],
        "summary": "GetBranches",
        "description": "Get a collection of branch roots -- first-level children, branches with no parents",
        "operationId": "getBranches",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/branches/{path}": {
      "get": {
        "tags": [
          "branches"
        ],
        "summary": "GetBranch",
        "description": "Get a single branch hierarchy at the given path with parents or children (if specified)",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/changesets": {
      "post": {
        "tags": [
          "changesets"
        ],
        "summary": "CreateChangeset",
        "description": "",
        "operationId": "createChangeset",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "changesets"
        ],
        "summary": "GetChangesets",
        "description": "Retrieve Tfvc changesets Note: This is a new version of the GetChangesets API that doesn't expose the unneeded queryParams present in the 1.0 version of the API.",
        "operationId": "getChangesets",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/changesets/{id}": {
      "get": {
        "tags": [
          "changesets"
        ],
        "summary": "GetChangeset",
        "description": "Retrieve a Tfvc Changeset",
        "operationId": "getChangeset",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/changesets/{id}/changes": {
      "get": {
        "tags": [
          "changesetChanges"
        ],
        "summary": "GetChangesetChanges",
        "description": "Retrieve Tfvc changes for a given changeset",
        "operationId": "getChangesetChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/changesets/{id}/workItems": {
      "get": {
        "tags": [
          "changesetWorkItems"
        ],
        "summary": "GetChangesetWorkItems",
        "description": "",
        "operationId": "getChangesetWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/changesetsbatch": {
      "post": {
        "tags": [
          "changesetsBatch"
        ],
        "summary": "GetBatchedChangesets",
        "description": "",
        "operationId": "getBatchedChangesets",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/itembatch": {
      "post": {
        "tags": [
          "itemBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a set of items given a list of paths or a long path. Allows for specifying the recursionLevel and version descriptors for each path.",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get a list of Tfvc items",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/labels": {
      "get": {
        "tags": [
          "labels"
        ],
        "summary": "GetLabels",
        "description": "Get a collection of shallow label references.",
        "operationId": "getLabels",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/labels/{labelId}": {
      "get": {
        "tags": [
          "labels"
        ],
        "summary": "GetLabel",
        "description": "Get a single deep label.",
        "operationId": "getLabel",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/labels/{labelId}/items": {
      "get": {
        "tags": [
          "labelItems"
        ],
        "summary": "GetLabelItems",
        "description": "Get items under a label.",
        "operationId": "getLabelItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/shelvesets": {
      "get": {
        "tags": [
          "shelvesets"
        ],
        "summary": "GetShelveset",
        "description": "Get a single deep shelveset.",
        "operationId": "getShelveset",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/shelvesets/changes": {
      "get": {
        "tags": [
          "shelvesetChanges"
        ],
        "summary": "GetShelvesetChanges",
        "description": "Get changes included in a shelveset.",
        "operationId": "getShelvesetChanges",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/_apis/tfvc/shelvesets/workitems": {
      "get": {
        "tags": [
          "shelvesetWorkItems"
        ],
        "summary": "GetShelvesetWorkItems",
        "description": "Get work items associated with a shelveset.",
        "operationId": "getShelvesetWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/branches": {
      "get": {
        "tags": [
          "branches"
        ],
        "summary": "GetBranches",
        "description": "Get a collection of branch roots -- first-level children, branches with no parents",
        "operationId": "getBranches",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/branches/{path}": {
      "get": {
        "tags": [
          "branches"
        ],
        "summary": "GetBranch",
        "description": "Get a single branch hierarchy at the given path with parents or children (if specified)",
        "operationId": "getBranch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/changesets": {
      "post": {
        "tags": [
          "changesets"
        ],
        "summary": "CreateChangeset",
        "description": "",
        "operationId": "createChangeset",
        "security": [
          {
            "oauth2": [
              "vso.code_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "changesets"
        ],
        "summary": "GetChangesets",
        "description": "Retrieve Tfvc changesets Note: This is a new version of the GetChangesets API that doesn't expose the unneeded queryParams present in the 1.0 version of the API.",
        "operationId": "getChangesets",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/changesets/{id}": {
      "get": {
        "tags": [
          "changesets"
        ],
        "summary": "GetChangeset",
        "description": "Retrieve a Tfvc Changeset",
        "operationId": "getChangeset",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/itembatch": {
      "post": {
        "tags": [
          "itemBatch"
        ],
        "summary": "GetItemsBatch",
        "description": "Post for retrieving a set of items given a list of paths or a long path. Allows for specifying the recursionLevel and version descriptors for each path.",
        "operationId": "getItemsBatch",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/items": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItems",
        "description": "Get a list of Tfvc items",
        "operationId": "getItems",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/items/{path}": {
      "get": {
        "tags": [
          "items"
        ],
        "summary": "GetItem",
        "description": "Get Item Metadata and/or Content for a single item. The download parameter is to indicate whether the content should be available as a download or just sent as a stream in the response. Doesn't apply to zipped content which is always returned as a download.",
        "operationId": "getItem",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/labels": {
      "get": {
        "tags": [
          "labels"
        ],
        "summary": "GetLabels",
        "description": "Get a collection of shallow label references.",
        "operationId": "getLabels",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/tfvc/labels/{labelId}": {
      "get": {
        "tags": [
          "labels"
        ],
        "summary": "GetLabel",
        "description": "Get a single deep label.",
        "operationId": "getLabel",
        "security": [
          {
            "oauth2": [
              "vso.code"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.code": "Grants the ability to read source code and metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to get notified about version control events via service hooks.",
        "vso.code_write": "Grants the ability to read, update, and delete source code, access metadata about commits, changesets, branches, and other version control artifacts. Also grants the ability to create and manage pull requests and code reviews and to receive notifications about version control events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}