{
  "swagger": "2.0",
  "info": {
    "title": "Work",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "backlogconfiguration"
    },
    {
      "name": "boardcolumns"
    },
    {
      "name": "boardfiltersettings"
    },
    {
      "name": "boardparents"
    },
    {
      "name": "boardrows"
    },
    {
      "name": "boards"
    },
    {
      "name": "boardusersettings"
    },
    {
      "name": "capacities"
    },
    {
      "name": "cardrulesettings"
    },
    {
      "name": "cardsettings"
    },
    {
      "name": "charts"
    },
    {
      "name": "columns"
    },
    {
      "name": "deliverytimeline"
    },
    {
      "name": "iterations"
    },
    {
      "name": "plans"
    },
    {
      "name": "processconfiguration"
    },
    {
      "name": "rows"
    },
    {
      "name": "teamdaysoff"
    },
    {
      "name": "teamfieldvalues"
    },
    {
      "name": "teamsettings"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/work/boardcolumns": {
      "get": {
        "tags": [
          "boardcolumns"
        ],
        "summary": "GetColumnSuggestedValues",
        "description": "",
        "operationId": "getColumnSuggestedValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/work/boardrows": {
      "get": {
        "tags": [
          "boardrows"
        ],
        "summary": "GetRowSuggestedValues",
        "description": "",
        "operationId": "getRowSuggestedValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/backlogconfiguration": {
      "get": {
        "tags": [
          "backlogconfiguration"
        ],
        "summary": "GetBacklogConfigurations",
        "description": "",
        "operationId": "getBacklogConfigurations",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boardcolumns": {
      "get": {
        "tags": [
          "boardcolumns"
        ],
        "summary": "GetColumnSuggestedValues",
        "description": "",
        "operationId": "getColumnSuggestedValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boardrows": {
      "get": {
        "tags": [
          "boardrows"
        ],
        "summary": "GetRowSuggestedValues",
        "description": "",
        "operationId": "getRowSuggestedValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards": {
      "get": {
        "tags": [
          "boards"
        ],
        "summary": "GetBoards",
        "description": "",
        "operationId": "getBoards",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/boardfiltersettings": {
      "get": {
        "tags": [
          "boardfiltersettings"
        ],
        "summary": "GetBoardFilterSettings",
        "description": "Returns the board filter settings for the given board id or board by name",
        "operationId": "getBoardFilterSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "boardfiltersettings"
        ],
        "summary": "UpdateBoardFilterSettings",
        "description": "Update board filter settings for the board id or board by name",
        "operationId": "updateBoardFilterSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/boardusersettings": {
      "get": {
        "tags": [
          "boardusersettings"
        ],
        "summary": "GetBoardUserSettings",
        "description": "",
        "operationId": "getBoardUserSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "boardusersettings"
        ],
        "summary": "UpdateBoardUserSettings",
        "description": "Update board user settings for the board id",
        "operationId": "updateBoardUserSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/cardrulesettings": {
      "get": {
        "tags": [
          "cardrulesettings"
        ],
        "summary": "GetBoardCardRuleSettings",
        "description": "Get board card Rule settings for the board id or board by name",
        "operationId": "getBoardCardRuleSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "cardrulesettings"
        ],
        "summary": "UpdateBoardCardRuleSettings",
        "description": "Update board card Rule settings for the board id or board by name",
        "operationId": "updateBoardCardRuleSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/cardsettings": {
      "get": {
        "tags": [
          "cardsettings"
        ],
        "summary": "GetBoardCardSettings",
        "description": "Get board card settings for the board id or board by name",
        "operationId": "getBoardCardSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "cardsettings"
        ],
        "summary": "UpdateBoardCardSettings",
        "description": "Update board card settings for the board id or board by name",
        "operationId": "updateBoardCardSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/charts": {
      "get": {
        "tags": [
          "charts"
        ],
        "summary": "GetBoardCharts",
        "description": "Get board charts",
        "operationId": "getBoardCharts",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/charts/{name}": {
      "get": {
        "tags": [
          "charts"
        ],
        "summary": "GetBoardChart",
        "description": "Get a board chart",
        "operationId": "getBoardChart",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "charts"
        ],
        "summary": "UpdateBoardChart",
        "description": "Update a board chart",
        "operationId": "updateBoardChart",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/columns": {
      "get": {
        "tags": [
          "columns"
        ],
        "summary": "GetBoardColumns",
        "description": "",
        "operationId": "getBoardColumns",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "columns"
        ],
        "summary": "UpdateBoardColumns",
        "description": "",
        "operationId": "updateBoardColumns",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{board}/rows": {
      "get": {
        "tags": [
          "rows"
        ],
        "summary": "GetBoardRows",
        "description": "",
        "operationId": "getBoardRows",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "rows"
        ],
        "summary": "UpdateBoardRows",
        "description": "",
        "operationId": "updateBoardRows",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/{id}": {
      "get": {
        "tags": [
          "boards"
        ],
        "summary": "GetBoard",
        "description": "Get board",
        "operationId": "getBoard",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "boards"
        ],
        "summary": "SetBoardOptions",
        "description": "Update board options",
        "operationId": "setBoardOptions",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boards/boardparents": {
      "get": {
        "tags": [
          "boardparents"
        ],
        "summary": "GetBoardMappingParentItems",
        "description": "Returns the list of parent field filter model for the given list of workitem ids",
        "operationId": "getBoardMappingParentItems",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/plans": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "CreatePlan",
        "description": "Add a new plan for the team",
        "operationId": "createPlan"
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlans",
        "description": "",
        "operationId": "getPlans"
      }
    },
    "/{project}/_apis/work/plans/{id}": {
      "delete": {
        "tags": [
          "plans"
        ],
        "summary": "DeletePlan",
        "description": "Delete the specified plan",
        "operationId": "deletePlan"
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlan",
        "description": "Get the information for the specified plan",
        "operationId": "getPlan"
      },
      "put": {
        "tags": [
          "plans"
        ],
        "summary": "UpdatePlan",
        "description": "Update the information for the specified plan",
        "operationId": "updatePlan"
      }
    },
    "/{project}/_apis/work/plans/{id}/deliverytimeline": {
      "get": {
        "tags": [
          "deliverytimeline"
        ],
        "summary": "GetDeliveryTimelineData",
        "description": "Get Delivery View Data",
        "operationId": "getDeliveryTimelineData"
      }
    },
    "/{project}/_apis/work/processconfiguration": {
      "get": {
        "tags": [
          "processconfiguration"
        ],
        "summary": "GetProcessConfiguration",
        "description": "",
        "operationId": "getProcessConfiguration",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings": {
      "get": {
        "tags": [
          "teamsettings"
        ],
        "summary": "GetTeamSettings",
        "description": "",
        "operationId": "getTeamSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamsettings"
        ],
        "summary": "UpdateTeamSettings",
        "description": "",
        "operationId": "updateTeamSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/iterations": {
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTeamIterations",
        "description": "",
        "operationId": "getTeamIterations",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "iterations"
        ],
        "summary": "PostTeamIteration",
        "description": "",
        "operationId": "postTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/iterations/{id}": {
      "delete": {
        "tags": [
          "iterations"
        ],
        "summary": "DeleteTeamIteration",
        "description": "",
        "operationId": "deleteTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTeamIteration",
        "description": "",
        "operationId": "getTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/iterations/{iterationId}/capacities": {
      "get": {
        "tags": [
          "capacities"
        ],
        "summary": "GetCapacities",
        "description": "",
        "operationId": "getCapacities",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "capacities"
        ],
        "summary": "ReplaceCapacities",
        "description": "",
        "operationId": "replaceCapacities",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/iterations/{iterationId}/capacities/{teamMemberId}": {
      "get": {
        "tags": [
          "capacities"
        ],
        "summary": "GetCapacity",
        "description": "",
        "operationId": "getCapacity",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "capacities"
        ],
        "summary": "UpdateCapacity",
        "description": "",
        "operationId": "updateCapacity",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/iterations/{iterationId}/teamdaysoff": {
      "get": {
        "tags": [
          "teamdaysoff"
        ],
        "summary": "GetTeamDaysOff",
        "description": "",
        "operationId": "getTeamDaysOff",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamdaysoff"
        ],
        "summary": "UpdateTeamDaysOff",
        "description": "",
        "operationId": "updateTeamDaysOff",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/teamsettings/teamfieldvalues": {
      "get": {
        "tags": [
          "teamfieldvalues"
        ],
        "summary": "GetTeamFieldValues",
        "description": "",
        "operationId": "getTeamFieldValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamfieldvalues"
        ],
        "summary": "UpdateTeamFieldValues",
        "description": "",
        "operationId": "updateTeamFieldValues",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/backlogconfiguration": {
      "get": {
        "tags": [
          "backlogconfiguration"
        ],
        "summary": "GetBacklogConfigurations",
        "description": "",
        "operationId": "getBacklogConfigurations",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards": {
      "get": {
        "tags": [
          "boards"
        ],
        "summary": "GetBoards",
        "description": "",
        "operationId": "getBoards",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/boardfiltersettings": {
      "get": {
        "tags": [
          "boardfiltersettings"
        ],
        "summary": "GetBoardFilterSettings",
        "description": "Returns the board filter settings for the given board id or board by name",
        "operationId": "getBoardFilterSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "boardfiltersettings"
        ],
        "summary": "UpdateBoardFilterSettings",
        "description": "Update board filter settings for the board id or board by name",
        "operationId": "updateBoardFilterSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/boardusersettings": {
      "get": {
        "tags": [
          "boardusersettings"
        ],
        "summary": "GetBoardUserSettings",
        "description": "",
        "operationId": "getBoardUserSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "boardusersettings"
        ],
        "summary": "UpdateBoardUserSettings",
        "description": "Update board user settings for the board id",
        "operationId": "updateBoardUserSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardrulesettings": {
      "get": {
        "tags": [
          "cardrulesettings"
        ],
        "summary": "GetBoardCardRuleSettings",
        "description": "Get board card Rule settings for the board id or board by name",
        "operationId": "getBoardCardRuleSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "cardrulesettings"
        ],
        "summary": "UpdateBoardCardRuleSettings",
        "description": "Update board card Rule settings for the board id or board by name",
        "operationId": "updateBoardCardRuleSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardsettings": {
      "get": {
        "tags": [
          "cardsettings"
        ],
        "summary": "GetBoardCardSettings",
        "description": "Get board card settings for the board id or board by name",
        "operationId": "getBoardCardSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "cardsettings"
        ],
        "summary": "UpdateBoardCardSettings",
        "description": "Update board card settings for the board id or board by name",
        "operationId": "updateBoardCardSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts": {
      "get": {
        "tags": [
          "charts"
        ],
        "summary": "GetBoardCharts",
        "description": "Get board charts",
        "operationId": "getBoardCharts",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts/{name}": {
      "get": {
        "tags": [
          "charts"
        ],
        "summary": "GetBoardChart",
        "description": "Get a board chart",
        "operationId": "getBoardChart",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "charts"
        ],
        "summary": "UpdateBoardChart",
        "description": "Update a board chart",
        "operationId": "updateBoardChart",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/columns": {
      "get": {
        "tags": [
          "columns"
        ],
        "summary": "GetBoardColumns",
        "description": "",
        "operationId": "getBoardColumns",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "columns"
        ],
        "summary": "UpdateBoardColumns",
        "description": "",
        "operationId": "updateBoardColumns",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/rows": {
      "get": {
        "tags": [
          "rows"
        ],
        "summary": "GetBoardRows",
        "description": "",
        "operationId": "getBoardRows",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "rows"
        ],
        "summary": "UpdateBoardRows",
        "description": "",
        "operationId": "updateBoardRows",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{id}": {
      "get": {
        "tags": [
          "boards"
        ],
        "summary": "GetBoard",
        "description": "Get board",
        "operationId": "getBoard",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "boards"
        ],
        "summary": "SetBoardOptions",
        "description": "Update board options",
        "operationId": "setBoardOptions",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/boardparents": {
      "get": {
        "tags": [
          "boardparents"
        ],
        "summary": "GetBoardMappingParentItems",
        "description": "Returns the list of parent field filter model for the given list of workitem ids",
        "operationId": "getBoardMappingParentItems",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/plans": {
      "post": {
        "tags": [
          "plans"
        ],
        "summary": "CreatePlan",
        "description": "Add a new plan for the team",
        "operationId": "createPlan"
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlans",
        "description": "",
        "operationId": "getPlans"
      }
    },
    "/{project}/{team}/_apis/work/plans/{id}": {
      "delete": {
        "tags": [
          "plans"
        ],
        "summary": "DeletePlan",
        "description": "Delete the specified plan",
        "operationId": "deletePlan"
      },
      "get": {
        "tags": [
          "plans"
        ],
        "summary": "GetPlan",
        "description": "Get the information for the specified plan",
        "operationId": "getPlan"
      },
      "put": {
        "tags": [
          "plans"
        ],
        "summary": "UpdatePlan",
        "description": "Update the information for the specified plan",
        "operationId": "updatePlan"
      }
    },
    "/{project}/{team}/_apis/work/plans/{id}/deliverytimeline": {
      "get": {
        "tags": [
          "deliverytimeline"
        ],
        "summary": "GetDeliveryTimelineData",
        "description": "Get Delivery View Data",
        "operationId": "getDeliveryTimelineData"
      }
    },
    "/{project}/{team}/_apis/work/teamsettings": {
      "get": {
        "tags": [
          "teamsettings"
        ],
        "summary": "GetTeamSettings",
        "description": "",
        "operationId": "getTeamSettings",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamsettings"
        ],
        "summary": "UpdateTeamSettings",
        "description": "",
        "operationId": "updateTeamSettings",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations": {
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTeamIterations",
        "description": "",
        "operationId": "getTeamIterations",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "iterations"
        ],
        "summary": "PostTeamIteration",
        "description": "",
        "operationId": "postTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{id}": {
      "delete": {
        "tags": [
          "iterations"
        ],
        "summary": "DeleteTeamIteration",
        "description": "",
        "operationId": "deleteTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "iterations"
        ],
        "summary": "GetTeamIteration",
        "description": "",
        "operationId": "getTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities": {
      "get": {
        "tags": [
          "capacities"
        ],
        "summary": "GetCapacities",
        "description": "",
        "operationId": "getCapacities",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "capacities"
        ],
        "summary": "ReplaceCapacities",
        "description": "",
        "operationId": "replaceCapacities",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities/{teamMemberId}": {
      "get": {
        "tags": [
          "capacities"
        ],
        "summary": "GetCapacity",
        "description": "",
        "operationId": "getCapacity",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "capacities"
        ],
        "summary": "UpdateCapacity",
        "description": "",
        "operationId": "updateCapacity",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/teamdaysoff": {
      "get": {
        "tags": [
          "teamdaysoff"
        ],
        "summary": "GetTeamDaysOff",
        "description": "",
        "operationId": "getTeamDaysOff",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamdaysoff"
        ],
        "summary": "UpdateTeamDaysOff",
        "description": "",
        "operationId": "updateTeamDaysOff",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/teamfieldvalues": {
      "get": {
        "tags": [
          "teamfieldvalues"
        ],
        "summary": "GetTeamFieldValues",
        "description": "",
        "operationId": "getTeamFieldValues",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "teamfieldvalues"
        ],
        "summary": "UpdateTeamFieldValues",
        "description": "",
        "operationId": "updateTeamFieldValues",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks.",
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}