{
  "swagger": "2.0",
  "info": {
    "title": "WorkItemTracking",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "3.2"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "accountMyWork"
    },
    {
      "name": "accountMyWorkRecentActivity"
    },
    {
      "name": "attachments"
    },
    {
      "name": "classificationNodes"
    },
    {
      "name": "comments"
    },
    {
      "name": "fields"
    },
    {
      "name": "queries"
    },
    {
      "name": "recyclebin"
    },
    {
      "name": "revisions"
    },
    {
      "name": "ruleEngine"
    },
    {
      "name": "templates"
    },
    {
      "name": "updates"
    },
    {
      "name": "wiql"
    },
    {
      "name": "workItemLinks"
    },
    {
      "name": "workItemRelationTypes"
    },
    {
      "name": "workItemRevisions"
    },
    {
      "name": "workItems"
    },
    {
      "name": "workitemStateColor"
    },
    {
      "name": "workItemTypeCategories"
    },
    {
      "name": "workitemTypeColor"
    },
    {
      "name": "workItemTypes"
    },
    {
      "name": "workItemTypesField"
    },
    {
      "name": "workItemTypeStates"
    },
    {
      "name": "workItemTypeTemplate"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/wit/$ruleengine": {
      "post": {
        "tags": [
          "ruleEngine"
        ],
        "summary": "EvaluateRulesOnField",
        "description": "Validates the fields values.",
        "operationId": "evaluateRulesOnField",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments": {
      "post": {
        "tags": [
          "attachments"
        ],
        "summary": "CreateAttachment",
        "description": "Creates an attachment.",
        "operationId": "createAttachment",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/attachments/{id}": {
      "get": {
        "tags": [
          "attachments"
        ],
        "summary": "GetAttachmentContent",
        "description": "Returns an attachment",
        "operationId": "getAttachmentContent",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/fields": {
      "get": {
        "tags": [
          "fields"
        ],
        "summary": "GetFields",
        "description": "Returns information for all fields.",
        "operationId": "getFields",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/fields/{fieldNameOrRefName}": {
      "get": {
        "tags": [
          "fields"
        ],
        "summary": "GetField",
        "description": "Gets information on a specific field.",
        "operationId": "getField",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/recyclebin": {
      "get": {
        "tags": [
          "recyclebin"
        ],
        "summary": "GetDeletedWorkItems",
        "description": "",
        "operationId": "getDeletedWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/recyclebin/{id}": {
      "delete": {
        "tags": [
          "recyclebin"
        ],
        "summary": "DestroyWorkItem",
        "description": "",
        "operationId": "destroyWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recyclebin"
        ],
        "summary": "GetDeletedWorkItem",
        "description": "",
        "operationId": "getDeletedWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "recyclebin"
        ],
        "summary": "RestoreWorkItem",
        "description": "",
        "operationId": "restoreWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/reporting/workitemlinks": {
      "get": {
        "tags": [
          "workItemLinks"
        ],
        "summary": "GetReportingLinks",
        "description": "Get a batch of work item links",
        "operationId": "getReportingLinks",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/reporting/workitemrevisions": {
      "get": {
        "tags": [
          "workItemRevisions"
        ],
        "summary": "ReadReportingRevisionsGet",
        "description": "Get a batch of work item revisions with the option of including deleted items",
        "operationId": "readReportingRevisionsGet",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "workItemRevisions"
        ],
        "summary": "ReadReportingRevisionsPost",
        "description": "Get a batch of work item revisions",
        "operationId": "readReportingRevisionsPost",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/wiql": {
      "post": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryByWiql",
        "description": "Gets the results of the query.",
        "operationId": "queryByWiql",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/wiql/{id}": {
      "get": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryById",
        "description": "Gets the results of the query by id.",
        "operationId": "queryById",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemrelationtypes": {
      "get": {
        "tags": [
          "workItemRelationTypes"
        ],
        "summary": "GetRelationTypes",
        "description": "",
        "operationId": "getRelationTypes",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemrelationtypes/{relation}": {
      "get": {
        "tags": [
          "workItemRelationTypes"
        ],
        "summary": "GetRelationType",
        "description": "Gets the work item relation types.",
        "operationId": "getRelationType",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems": {
      "get": {
        "tags": [
          "workItems"
        ],
        "summary": "GetWorkItems",
        "description": "Returns a list of work items",
        "operationId": "getWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitems/{id}": {
      "delete": {
        "tags": [
          "workItems"
        ],
        "summary": "DeleteWorkItem",
        "description": "",
        "operationId": "deleteWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "workItems"
        ],
        "summary": "GetWorkItem",
        "description": "Returns a single work item",
        "operationId": "getWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "workItems"
        ],
        "summary": "UpdateWorkItem",
        "description": "",
        "operationId": "updateWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments": {
      "get": {
        "tags": [
          "comments"
        ],
        "summary": "GetComments",
        "description": "Returns specified number of comments for a work item from the specified revision",
        "operationId": "getComments",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/comments/{revision}": {
      "get": {
        "tags": [
          "comments"
        ],
        "summary": "GetComment",
        "description": "Returns comment for a work item at the specified revision",
        "operationId": "getComment",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetRevisions",
        "description": "Returns the list of fully hydrated work item revisions, paged.",
        "operationId": "getRevisions",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/revisions/{revisionNumber}": {
      "get": {
        "tags": [
          "revisions"
        ],
        "summary": "GetRevision",
        "description": "Returns a fully hydrated work item for the requested revision",
        "operationId": "getRevision",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates": {
      "get": {
        "tags": [
          "updates"
        ],
        "summary": "GetUpdates",
        "description": "Returns a the deltas between work item revisions",
        "operationId": "getUpdates",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workItems/{id}/updates/{updateNumber}": {
      "get": {
        "tags": [
          "updates"
        ],
        "summary": "GetUpdate",
        "description": "Returns a single update for a work item",
        "operationId": "getUpdate",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemtypetemplate": {
      "post": {
        "tags": [
          "workItemTypeTemplate"
        ],
        "summary": "UpdateWorkItemTypeDefinition",
        "description": "Add/updates a work item type",
        "operationId": "updateWorkItemTypeDefinition",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/_apis/wit/workitemtypetemplate/{type}": {
      "get": {
        "tags": [
          "workItemTypeTemplate"
        ],
        "summary": "ExportWorkItemTypeDefinition",
        "description": "Export work item type",
        "operationId": "exportWorkItemTypeDefinition",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/classificationnodes": {
      "get": {
        "tags": [
          "classificationNodes"
        ],
        "summary": "GetRootNodes",
        "description": "",
        "operationId": "getRootNodes",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/classificationnodes/{structureGroup}/{*path}": {
      "post": {
        "tags": [
          "classificationNodes"
        ],
        "summary": "CreateOrUpdateClassificationNode",
        "description": "",
        "operationId": "createOrUpdateClassificationNode",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "classificationNodes"
        ],
        "summary": "DeleteClassificationNode",
        "description": "",
        "operationId": "deleteClassificationNode",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "classificationNodes"
        ],
        "summary": "GetClassificationNode",
        "description": "",
        "operationId": "getClassificationNode",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "classificationNodes"
        ],
        "summary": "UpdateClassificationNode",
        "description": "",
        "operationId": "updateClassificationNode",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields": {
      "get": {
        "tags": [
          "fields"
        ],
        "summary": "GetFields",
        "description": "Returns information for all fields.",
        "operationId": "getFields",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/fields/{fieldNameOrRefName}": {
      "get": {
        "tags": [
          "fields"
        ],
        "summary": "GetField",
        "description": "Gets information on a specific field.",
        "operationId": "getField",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/queries": {
      "get": {
        "tags": [
          "queries"
        ],
        "summary": "GetQueries",
        "description": "Retrieves all queries the user has access to in the current project",
        "operationId": "getQueries",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/queries/{query}": {
      "post": {
        "tags": [
          "queries"
        ],
        "summary": "CreateQuery",
        "description": "Creates a query, or moves a query.",
        "operationId": "createQuery",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "queries"
        ],
        "summary": "DeleteQuery",
        "description": "",
        "operationId": "deleteQuery",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "queries"
        ],
        "summary": "GetQuery",
        "description": "Retrieves a single query by project and either id or path",
        "operationId": "getQuery",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "queries"
        ],
        "summary": "UpdateQuery",
        "description": "",
        "operationId": "updateQuery",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin": {
      "get": {
        "tags": [
          "recyclebin"
        ],
        "summary": "GetDeletedWorkItems",
        "description": "",
        "operationId": "getDeletedWorkItems",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/recyclebin/{id}": {
      "delete": {
        "tags": [
          "recyclebin"
        ],
        "summary": "DestroyWorkItem",
        "description": "",
        "operationId": "destroyWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "recyclebin"
        ],
        "summary": "GetDeletedWorkItem",
        "description": "",
        "operationId": "getDeletedWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "recyclebin"
        ],
        "summary": "RestoreWorkItem",
        "description": "",
        "operationId": "restoreWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemlinks": {
      "get": {
        "tags": [
          "workItemLinks"
        ],
        "summary": "GetReportingLinks",
        "description": "Get a batch of work item links",
        "operationId": "getReportingLinks",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/reporting/workitemrevisions": {
      "get": {
        "tags": [
          "workItemRevisions"
        ],
        "summary": "ReadReportingRevisionsGet",
        "description": "Get a batch of work item revisions with the option of including deleted items",
        "operationId": "readReportingRevisionsGet",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "workItemRevisions"
        ],
        "summary": "ReadReportingRevisionsPost",
        "description": "Get a batch of work item revisions",
        "operationId": "readReportingRevisionsPost",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/wiql": {
      "post": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryByWiql",
        "description": "Gets the results of the query.",
        "operationId": "queryByWiql",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/wiql/{id}": {
      "get": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryById",
        "description": "Gets the results of the query by id.",
        "operationId": "queryById",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitems/${type}": {
      "post": {
        "tags": [
          "workItems"
        ],
        "summary": "CreateWorkItem",
        "description": "",
        "operationId": "createWorkItem",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "workItems"
        ],
        "summary": "GetWorkItemTemplate",
        "description": "Returns a single work item from a template",
        "operationId": "getWorkItemTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories": {
      "get": {
        "tags": [
          "workItemTypeCategories"
        ],
        "summary": "GetWorkItemTypeCategories",
        "description": "",
        "operationId": "getWorkItemTypeCategories",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypecategories/{category}": {
      "get": {
        "tags": [
          "workItemTypeCategories"
        ],
        "summary": "GetWorkItemTypeCategory",
        "description": "Returns a the deltas between work item revisions",
        "operationId": "getWorkItemTypeCategory",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes": {
      "get": {
        "tags": [
          "workItemTypes"
        ],
        "summary": "GetWorkItemTypes",
        "description": "",
        "operationId": "getWorkItemTypes",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}": {
      "get": {
        "tags": [
          "workItemTypes"
        ],
        "summary": "GetWorkItemType",
        "description": "Returns a the deltas between work item revisions",
        "operationId": "getWorkItemType",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/fields/{field}": {
      "get": {
        "tags": [
          "workItemTypesField"
        ],
        "summary": "GetDependentFields",
        "description": "Returns the dependent fields for the corresponding workitem type and fieldname",
        "operationId": "getDependentFields",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypes/{type}/states": {
      "get": {
        "tags": [
          "workItemTypeStates"
        ],
        "summary": "GetWorkItemTypeStates",
        "description": "Returns the state names and colors for a work item type",
        "operationId": "getWorkItemTypeStates",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypetemplate": {
      "post": {
        "tags": [
          "workItemTypeTemplate"
        ],
        "summary": "UpdateWorkItemTypeDefinition",
        "description": "Add/updates a work item type",
        "operationId": "updateWorkItemTypeDefinition",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/wit/workitemtypetemplate/{type}": {
      "get": {
        "tags": [
          "workItemTypeTemplate"
        ],
        "summary": "ExportWorkItemTypeDefinition",
        "description": "Export work item type",
        "operationId": "exportWorkItemTypeDefinition",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates": {
      "post": {
        "tags": [
          "templates"
        ],
        "summary": "CreateTemplate",
        "description": "Creates a template",
        "operationId": "createTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "templates"
        ],
        "summary": "GetTemplates",
        "description": "Gets template",
        "operationId": "getTemplates",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/templates/{templateId}": {
      "delete": {
        "tags": [
          "templates"
        ],
        "summary": "DeleteTemplate",
        "description": "Deletes the template with given id",
        "operationId": "deleteTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "templates"
        ],
        "summary": "GetTemplate",
        "description": "Gets the template with specified id",
        "operationId": "getTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "templates"
        ],
        "summary": "ReplaceTemplate",
        "description": "Replace template contents",
        "operationId": "replaceTemplate",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql": {
      "post": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryByWiql",
        "description": "Gets the results of the query.",
        "operationId": "queryByWiql",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/wit/wiql/{id}": {
      "get": {
        "tags": [
          "wiql"
        ],
        "summary": "QueryById",
        "description": "Gets the results of the query by id.",
        "operationId": "queryById",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks.",
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}