{
  "swagger": "2.0",
  "info": {
    "title": "TaskAgent",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "agents"
    },
    {
      "name": "azurermsubscriptions"
    },
    {
      "name": "deploymentgroupaccesstoken"
    },
    {
      "name": "deploymentgroups"
    },
    {
      "name": "deploymentgroupsmetrics"
    },
    {
      "name": "deploymentmachinejobrequests"
    },
    {
      "name": "deploymentmachinemessages"
    },
    {
      "name": "endpoint"
    },
    {
      "name": "executionhistory"
    },
    {
      "name": "hublicense"
    },
    {
      "name": "icon"
    },
    {
      "name": "inputvalidation"
    },
    {
      "name": "jobrequests"
    },
    {
      "name": "machinegroupaccesstoken"
    },
    {
      "name": "machinegroups"
    },
    {
      "name": "machines"
    },
    {
      "name": "maintenancedefinitions"
    },
    {
      "name": "maintenancejobs"
    },
    {
      "name": "messages"
    },
    {
      "name": "packages"
    },
    {
      "name": "poolroles"
    },
    {
      "name": "pools"
    },
    {
      "name": "queueroles"
    },
    {
      "name": "queues"
    },
    {
      "name": "revisions"
    },
    {
      "name": "securefiles"
    },
    {
      "name": "serviceendpointproxy"
    },
    {
      "name": "serviceendpoints"
    },
    {
      "name": "serviceendpointtypes"
    },
    {
      "name": "sessions"
    },
    {
      "name": "taskgroups"
    },
    {
      "name": "tasks"
    },
    {
      "name": "updates"
    },
    {
      "name": "usercapabilities"
    },
    {
      "name": "variablegroups"
    },
    {
      "name": "vstsaadoauth"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/distributedtask/endpoint": {
      "post": {
        "tags": [
          "Endpoint"
        ],
        "description": "Proxy for a GET request defined by an 'endpoint'. The request is authorized using a service connection. The response is filtered using an XPath/Json based selector.",
        "operationId": "Endpoint_Query"
      }
    },
    "/_apis/distributedtask/hublicense/{hubName}": {
      "get": {
        "tags": [
          "Hublicense"
        ],
        "description": "",
        "operationId": "Hublicense_Get"
      },
      "put": {
        "tags": [
          "Hublicense"
        ],
        "description": "",
        "operationId": "Hublicense_Update"
      }
    },
    "/_apis/distributedtask/inputvalidation": {
      "post": {
        "tags": [
          "Inputvalidation"
        ],
        "description": "",
        "operationId": "Inputvalidation_ValidateInputs"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "Packages_List"
      }
    },
    "/_apis/distributedtask/packages/{packageType}/{platform}/{version}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "Packages_Get"
      }
    },
    "/_apis/distributedtask/poolroles/{poolId}": {
      "get": {
        "tags": [
          "Poolroles"
        ],
        "description": "",
        "operationId": "Poolroles_List"
      }
    },
    "/_apis/distributedtask/pools": {
      "post": {
        "tags": [
          "Pools"
        ],
        "description": "",
        "operationId": "Pools_Add",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Pools"
        ],
        "description": "",
        "operationId": "Pools_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}": {
      "delete": {
        "tags": [
          "Pools"
        ],
        "description": "",
        "operationId": "Pools_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Pools"
        ],
        "description": "",
        "operationId": "Pools_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Pools"
        ],
        "description": "",
        "operationId": "Pools_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents": {
      "post": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_Add",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}": {
      "delete": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_ReplaceAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Agents"
        ],
        "description": "",
        "operationId": "Agents_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/updates": {
      "put": {
        "tags": [
          "Updates"
        ],
        "description": "",
        "operationId": "Updates_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/agents/{agentId}/usercapabilities": {
      "put": {
        "tags": [
          "Usercapabilities"
        ],
        "description": "",
        "operationId": "Usercapabilities_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests": {
      "get": {
        "tags": [
          "Jobrequests"
        ],
        "description": "",
        "operationId": "Jobrequests_GetAgentRequestsForAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Jobrequests"
        ],
        "description": "",
        "operationId": "Jobrequests_Queue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/jobrequests/{requestId}": {
      "delete": {
        "tags": [
          "Jobrequests"
        ],
        "description": "",
        "operationId": "Jobrequests_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Jobrequests"
        ],
        "description": "",
        "operationId": "Jobrequests_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Jobrequests"
        ],
        "description": "",
        "operationId": "Jobrequests_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions": {
      "post": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Maintenancedefinitions_Create",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Maintenancedefinitions_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancedefinitions/{definitionId}": {
      "delete": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Maintenancedefinitions_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Maintenancedefinitions_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Maintenancedefinitions"
        ],
        "description": "",
        "operationId": "Maintenancedefinitions_Update"
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs": {
      "get": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Maintenancejobs_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Maintenancejobs_Queue",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/maintenancejobs/{jobId}": {
      "delete": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Maintenancejobs_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Maintenancejobs_GetAgentPoolMaintenanceJob",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Maintenancejobs"
        ],
        "description": "",
        "operationId": "Maintenancejobs_Update",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages": {
      "get": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Messages_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Messages_RefreshAgent",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/messages/{messageId}": {
      "delete": {
        "tags": [
          "Messages"
        ],
        "description": "",
        "operationId": "Messages_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions": {
      "post": {
        "tags": [
          "Sessions"
        ],
        "description": "",
        "operationId": "Sessions_Create",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/pools/{poolId}/sessions/{sessionId}": {
      "delete": {
        "tags": [
          "Sessions"
        ],
        "description": "",
        "operationId": "Sessions_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/queueroles/{queueId}": {
      "get": {
        "tags": [
          "Queueroles"
        ],
        "description": "",
        "operationId": "Queueroles_List"
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/azurermsubscriptions": {
      "get": {
        "tags": [
          "Azurermsubscriptions"
        ],
        "description": "Returns list of azure subscriptions",
        "operationId": "Azurermsubscriptions_Get"
      }
    },
    "/_apis/distributedtask/serviceendpointproxy/vstsaadoauth": {
      "post": {
        "tags": [
          "Vstsaadoauth"
        ],
        "description": "",
        "operationId": "Vstsaadoauth_AcquireAccessToken"
      },
      "get": {
        "tags": [
          "Vstsaadoauth"
        ],
        "description": "",
        "operationId": "Vstsaadoauth_Get"
      }
    },
    "/_apis/distributedtask/serviceendpointtypes": {
      "get": {
        "tags": [
          "Serviceendpointtypes"
        ],
        "description": "",
        "operationId": "Serviceendpointtypes_List",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}": {
      "delete": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "Tasks_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "Tasks_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}": {
      "get": {
        "tags": [
          "Tasks"
        ],
        "description": "",
        "operationId": "Tasks_GetTaskContentZip",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/_apis/distributedtask/tasks/{taskId}/{versionString}/icon": {
      "get": {
        "tags": [
          "Icon"
        ],
        "description": "",
        "operationId": "Icon_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroupaccesstoken/{deploymentGroupId}": {
      "post": {
        "tags": [
          "Deploymentgroupaccesstoken"
        ],
        "description": "",
        "operationId": "Deploymentgroupaccesstoken_GenerateDeploymentGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups": {
      "post": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Deploymentgroups_Add"
      },
      "get": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Deploymentgroups_List"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}": {
      "delete": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Deploymentgroups_Delete"
      },
      "get": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Deploymentgroups_Get"
      },
      "patch": {
        "tags": [
          "Deploymentgroups"
        ],
        "description": "",
        "operationId": "Deploymentgroups_Update"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinejobrequests": {
      "get": {
        "tags": [
          "Deploymentmachinejobrequests"
        ],
        "description": "",
        "operationId": "Deploymentmachinejobrequests_GetAgentRequestsForDeploymentMachine"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/deploymentmachinemessages": {
      "post": {
        "tags": [
          "Deploymentmachinemessages"
        ],
        "description": "",
        "operationId": "Deploymentmachinemessages_RefreshDeploymentMachines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines": {
      "post": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_Add"
      },
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_GetDeploymentMachines"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_UpdateDeploymentMachines"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/{deploymentGroupId}/machines/{machineId}": {
      "delete": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_Delete"
      },
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_Get"
      },
      "put": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_ReplaceDeploymentMachine"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_UpdateDeploymentMachine"
      }
    },
    "/{project}/_apis/distributedtask/deploymentgroups/deploymentgroupsmetrics": {
      "get": {
        "tags": [
          "Deploymentgroupsmetrics"
        ],
        "description": "",
        "operationId": "Deploymentgroupsmetrics_List"
      }
    },
    "/{project}/_apis/distributedtask/machinegroupaccesstoken/{machineGroupId}": {
      "post": {
        "tags": [
          "Machinegroupaccesstoken"
        ],
        "description": "",
        "operationId": "Machinegroupaccesstoken_GenerateDeploymentMachineGroupAccessToken"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups": {
      "post": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Machinegroups_Add"
      },
      "get": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Machinegroups_List"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}": {
      "delete": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Machinegroups_Delete"
      },
      "get": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Machinegroups_Get"
      },
      "patch": {
        "tags": [
          "Machinegroups"
        ],
        "description": "",
        "operationId": "Machinegroups_Update"
      }
    },
    "/{project}/_apis/distributedtask/machinegroups/{machineGroupId}/machines": {
      "get": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_GetDeploymentMachineGroupMachines"
      },
      "patch": {
        "tags": [
          "Machines"
        ],
        "description": "",
        "operationId": "Machines_UpdateDeploymentMachineGroupMachines"
      }
    },
    "/{project}/_apis/distributedtask/queues": {
      "post": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Queues_Add",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Queues_Create",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Queues_List",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/queues/{queueId}": {
      "delete": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Queues_Delete",
        "security": [
          {
            "oauth2": [
              "vso.agentpools_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Queues"
        ],
        "description": "",
        "operationId": "Queues_Get",
        "security": [
          {
            "oauth2": [
              "vso.agentpools"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/securefiles": {
      "get": {
        "tags": [
          "Securefiles"
        ],
        "description": "Get secure files",
        "operationId": "Securefiles_GetSecureFiles"
      },
      "post": {
        "tags": [
          "Securefiles"
        ],
        "description": "Query secure files using a name pattern and a condition on file properties.",
        "operationId": "Securefiles_Query"
      },
      "patch": {
        "tags": [
          "Securefiles"
        ],
        "description": "Update properties and/or names of a set of secure files. Files are identified by their IDs. Properties provided override the existing one entirely, i.e. do not merge.",
        "operationId": "Securefiles_UpdateSecureFiles"
      }
    },
    "/{project}/_apis/distributedtask/securefiles/{secureFileId}": {
      "delete": {
        "tags": [
          "Securefiles"
        ],
        "description": "Delete a secure file",
        "operationId": "Securefiles_Delete"
      },
      "get": {
        "tags": [
          "Securefiles"
        ],
        "description": "Download a secure file by Id",
        "operationId": "Securefiles_DownloadSecureFile"
      },
      "patch": {
        "tags": [
          "Securefiles"
        ],
        "description": "Update the name or properties of an existing secure file",
        "operationId": "Securefiles_UpdateSecureFile"
      }
    },
    "/{project}/_apis/distributedtask/serviceendpointproxy": {
      "post": {
        "tags": [
          "Serviceendpointproxy"
        ],
        "description": "",
        "operationId": "Serviceendpointproxy_ExecuteServiceEndpointRequest",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_query"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints": {
      "post": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_Create",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_List",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_UpdateServiceEndpoints",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}": {
      "delete": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_Delete",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_Get",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Serviceendpoints"
        ],
        "description": "",
        "operationId": "Serviceendpoints_UpdateServiceEndpoint",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/{endpointId}/executionhistory": {
      "get": {
        "tags": [
          "Executionhistory"
        ],
        "description": "",
        "operationId": "Executionhistory_List",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/serviceendpoints/executionhistory": {
      "post": {
        "tags": [
          "Executionhistory"
        ],
        "description": "",
        "operationId": "Executionhistory_Add",
        "security": [
          {
            "oauth2": [
              "vso.serviceendpoint_manage"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/taskgroups": {
      "post": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Create a task group.",
        "operationId": "Taskgroups_Add",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_add"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Taskgroups"
        ],
        "description": "",
        "operationId": "Taskgroups_PublishTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Taskgroups"
        ],
        "description": "",
        "operationId": "Taskgroups_UndeleteTaskGroup"
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}": {
      "delete": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Delete a task group.",
        "operationId": "Taskgroups_Delete",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Taskgroups"
        ],
        "description": "Get task group.",
        "operationId": "Taskgroups_GetTaskGroup",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Taskgroups"
        ],
        "description": "",
        "operationId": "Taskgroups_PublishPreviewTaskGroup"
      }
    },
    "/{project}/_apis/distributedtask/taskgroups/{taskGroupId}/revisions": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "",
        "operationId": "Revisions_List",
        "security": [
          {
            "oauth2": [
              "vso.taskgroups"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/distributedtask/variablegroups": {
      "post": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Variablegroups_Add"
      },
      "get": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Variablegroups_GetVariableGroups"
      }
    },
    "/{project}/_apis/distributedtask/variablegroups/{groupId}": {
      "delete": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Variablegroups_Delete"
      },
      "get": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Variablegroups_Get"
      },
      "put": {
        "tags": [
          "Variablegroups"
        ],
        "description": "",
        "operationId": "Variablegroups_Update"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.agentpools": "Grants the ability to view tasks, pools, queues, agents, and currently running or recently completed jobs for agents",
        "vso.agentpools_manage": "Grants the ability to manage pools, queues, and agents",
        "vso.serviceendpoint_manage": "Grants the ability to read, query and manage service endpoints.",
        "vso.serviceendpoint": "Grants the ability to read service endpoints.",
        "vso.serviceendpoint_query": "Grants the ability to read and query service endpoints.",
        "vso.taskgroups": "Grants the ability to read task groups",
        "vso.taskgroups_manage": "Grants the ability to read, create and manage taskgroups.",
        "vso.taskgroups_add": "Grants the ability to read and create task groups"
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}