{
  "swagger": "2.0",
  "info": {
    "title": "Feed",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "5.0-preview"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Badge"
    },
    {
      "name": "Feed Changes"
    },
    {
      "name": "Feeds"
    },
    {
      "name": "Global Permissions"
    },
    {
      "name": "Package Changes"
    },
    {
      "name": "Packages"
    },
    {
      "name": "Permissions"
    },
    {
      "name": "Recycle Bin Packages"
    },
    {
      "name": "Recycle Bin Versions"
    },
    {
      "name": "Retention Policies"
    },
    {
      "name": "Versions"
    },
    {
      "name": "Views"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/packaging/feedchanges": {
      "get": {
        "tags": [
          "Feed Changes"
        ],
        "description": "Utility method to iterate through all changes to every package in every feed in an account.  This method allows a caller to discover package pushes, package deprecations, package deletions, and all of the other actions that are possible with packages in a feed.",
        "operationId": "Get Feed Changes",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feedchanges/{feedId}": {
      "get": {
        "tags": [
          "Feed Changes"
        ],
        "description": "Utility method to poll for settings changes to a specific feed.",
        "operationId": "Get Feed Change",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds": {
      "post": {
        "tags": [
          "Feeds"
        ],
        "description": "Creates a feed.  A feed is a container for various types of package protocols.",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Feeds"
        ],
        "description": "Get all of the feeds in an account.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}": {
      "delete": {
        "tags": [
          "Feeds"
        ],
        "description": "Remove a feed.",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Feeds"
        ],
        "description": "Get the settings for a specific feed.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Feeds"
        ],
        "description": "Use this to change any of the attributes of a feed.",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packagechanges": {
      "get": {
        "tags": [
          "Package Changes"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "Get details about all of the packages in the feed.  Use the various filters to include or exclude information from the result set.",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages/{packageId}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "Get details about a specific package.",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions/{packageVersionId}": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/permissions": {
      "get": {
        "tags": [
          "Permissions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Permissions"
        ],
        "description": "",
        "operationId": "Set Feed Permissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/RecycleBin/Packages": {
      "get": {
        "tags": [
          "Recycle Bin Packages"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/RecycleBin/Packages/{packageId}": {
      "get": {
        "tags": [
          "Recycle Bin Packages"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/RecycleBin/Packages/{packageId}/Versions": {
      "get": {
        "tags": [
          "Recycle Bin Versions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/RecycleBin/Packages/{packageId}/Versions/{packageVersionId}": {
      "get": {
        "tags": [
          "Recycle Bin Versions"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/retentionpolicies": {
      "delete": {
        "tags": [
          "Retention Policies"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Retention Policies"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Retention Policies"
        ],
        "description": "",
        "operationId": "Set Feed Retention Policies",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views": {
      "post": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views/{viewId}": {
      "delete": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/globalpermissions": {
      "get": {
        "tags": [
          "Global Permissions"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Global Permissions"
        ],
        "description": "",
        "operationId": "Set Global Permissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/public/packaging/Feeds/{feedId}/Packages/{packageId}/badge": {
      "get": {
        "tags": [
          "Badge"
        ],
        "description": "Utility method to generate a SVG badge for the latest version of a package.  The generated SVG is typically used as the image in an HTML link which takes users to the feed containing the package to accelerate discovery and consumption.",
        "operationId": "Get"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
    },
    "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.packaging_write": "Grants the ability to create and read feeds and packages.",
        "vso.packaging": "Grants the ability to read feeds and packages.",
        "vso.packaging_manage": "Grants the ability to create, read, update, and delete feeds and packages."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}