{
  "swagger": "2.0",
  "info": {
    "title": "Build",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Artifacts"
    },
    {
      "name": "Badge",
      "description": "Controller to handle all REST calls against build definition badges"
    },
    {
      "name": "Buildbadge",
      "description": "Controller to handle all REST calls against build definition badges"
    },
    {
      "name": "Builds"
    },
    {
      "name": "Controllers",
      "description": "Controller to handle all REST calls against XAML build controllers"
    },
    {
      "name": "Definitions"
    },
    {
      "name": "Folders",
      "description": "Controller to handle all REST calls against build definition folders"
    },
    {
      "name": "Metrics",
      "description": "Controller to handle all REST calls against build metrics"
    },
    {
      "name": "Options",
      "description": "Controller to handle all REST calls against build option definitions"
    },
    {
      "name": "Properties"
    },
    {
      "name": "Report",
      "description": "Controller to get build reports"
    },
    {
      "name": "Resource Usage"
    },
    {
      "name": "Revisions",
      "description": "Controller to handle all REST calls against build definition revisions"
    },
    {
      "name": "Settings",
      "description": "Controller to handle all REST calls against settings"
    },
    {
      "name": "Tags",
      "description": "Controller to handle all REST calls against definition tags"
    },
    {
      "name": "Templates",
      "description": "Controller to handle all REST calls against build definition templates"
    },
    {
      "name": "Timeline",
      "description": "Controller to handle all REST calls against build timelines"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/build/controllers": {
      "get": {
        "tags": [
          "Controllers"
        ],
        "description": "Gets controller, optionally filtered by name",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/_apis/build/controllers/{controllerId}": {
      "get": {
        "tags": [
          "Controllers"
        ],
        "description": "Gets a controller",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/_apis/build/resourceusage": {
      "get": {
        "tags": [
          "Resource Usage"
        ],
        "description": "",
        "operationId": "Get"
      }
    },
    "/_apis/build/settings": {
      "get": {
        "tags": [
          "Settings"
        ],
        "description": "Gets the build settings",
        "operationId": "Get"
      },
      "patch": {
        "tags": [
          "Settings"
        ],
        "description": "Updates the build settings",
        "operationId": "Update"
      }
    },
    "/_apis/public/build/definitions/{project}/{definitionId}/badge": {
      "get": {
        "tags": [
          "Badge"
        ],
        "description": "",
        "operationId": "Get"
      }
    },
    "/{project}/_apis/build/builds": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets builds",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Builds"
        ],
        "description": "Queues a build",
        "operationId": "Queue",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Builds"
        ],
        "description": "Update a batch of builds",
        "operationId": "Update Builds",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}": {
      "delete": {
        "tags": [
          "Builds"
        ],
        "description": "Deletes a build",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets a build",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Builds"
        ],
        "description": "Updates a build",
        "operationId": "Update Build",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/artifacts": {
      "post": {
        "tags": [
          "Artifacts"
        ],
        "description": "Associates an artifact with a build",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Artifacts"
        ],
        "description": "Gets all artifacts for a build",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/artifacts/{artifactName}": {
      "get": {
        "tags": [
          "Artifacts"
        ],
        "description": "Gets a specific artifact for a build",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/changes": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets the changes associated with a build",
        "operationId": "Get Build Changes",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/logs": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets logs for a build",
        "operationId": "Get Build Logs",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/logs/{logId}": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets a log",
        "operationId": "Get Build Log",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/properties": {
      "get": {
        "tags": [
          "Properties"
        ],
        "description": "Gets properties for a build.",
        "operationId": "Get Build Properties",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Properties"
        ],
        "description": "Updates properties for a build.",
        "operationId": "Update Build Properties",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/report": {
      "get": {
        "tags": [
          "Report"
        ],
        "description": "Gets report for a build",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/tags": {
      "post": {
        "tags": [
          "Tags"
        ],
        "description": "Adds tag to a build",
        "operationId": "Add Build Tags",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Tags"
        ],
        "description": "Gets the tags for a build",
        "operationId": "Get Build Tags",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/tags/{tag}": {
      "put": {
        "tags": [
          "Tags"
        ],
        "description": "Adds a tag to a build",
        "operationId": "Add Build Tag",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tags"
        ],
        "description": "Deletes a tag from a build",
        "operationId": "Delete Build Tag",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/timeline/{timelineId}": {
      "get": {
        "tags": [
          "Timeline"
        ],
        "description": "Gets details for a build",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/builds/{buildId}/workitems": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets the work item ids associated with a build",
        "operationId": "Get Build Work Items Refs",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Builds"
        ],
        "description": "Gets the work item ids associated with build commits",
        "operationId": "Get Build Work Items Refs From Commits",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/changes": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets the changes associated between given builds",
        "operationId": "Get Changes Between Builds"
      }
    },
    "/{project}/_apis/build/definitions": {
      "post": {
        "tags": [
          "Definitions"
        ],
        "description": "Creates a new definition",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Definitions"
        ],
        "description": "Gets definitions, optionally filtered by name",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/{definitionId}": {
      "delete": {
        "tags": [
          "Definitions"
        ],
        "description": "Deletes a definition and all associated builds",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Definitions"
        ],
        "description": "Gets a definition, optionally at a specific revision",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Definitions"
        ],
        "description": "Updates an existing definition",
        "operationId": "Update",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/{definitionId}/metrics": {
      "get": {
        "tags": [
          "Metrics"
        ],
        "description": "Gets metrics of a definition",
        "operationId": "Get Definition Metrics",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/{definitionId}/properties": {
      "get": {
        "tags": [
          "Properties"
        ],
        "description": "Gets properties for a definition.",
        "operationId": "Get Definition Properties",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Properties"
        ],
        "description": "Updates properties for a definition.",
        "operationId": "Update Definition Properties"
      }
    },
    "/{project}/_apis/build/definitions/{definitionId}/revisions": {
      "get": {
        "tags": [
          "Revisions"
        ],
        "description": "Gets revisions of a definition",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/{DefinitionId}/tags": {
      "post": {
        "tags": [
          "Tags"
        ],
        "description": "Adds multiple tags to a definition",
        "operationId": "Add Definition Tags",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Tags"
        ],
        "description": "Gets the tags for a definition",
        "operationId": "Get Definition Tags",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/{DefinitionId}/tags/{tag}": {
      "put": {
        "tags": [
          "Tags"
        ],
        "description": "Adds a tag to a definition",
        "operationId": "Add Definition Tag",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Tags"
        ],
        "description": "Deletes a tag from a definition",
        "operationId": "Delete Definition Tag",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/templates": {
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets definition templates",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/definitions/templates/{templateId}": {
      "delete": {
        "tags": [
          "Templates"
        ],
        "description": "Deletes a definition template",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Templates"
        ],
        "description": "Gets definition template filtered by id",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Templates"
        ],
        "description": "Saves a definition template",
        "operationId": "Save Template",
        "security": [
          {
            "oauth2": [
              "vso.build_execute"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/folders/{*path}": {
      "get": {
        "tags": [
          "Folders"
        ],
        "description": "Gets folders",
        "operationId": "List"
      }
    },
    "/{project}/_apis/build/folders/{path}": {
      "put": {
        "tags": [
          "Folders"
        ],
        "description": "Creates a new folder",
        "operationId": "Create"
      },
      "delete": {
        "tags": [
          "Folders"
        ],
        "description": "Deletes a definition folder for given folder name and path and all it's existing definitions and it's corresponding builds",
        "operationId": "Delete"
      },
      "post": {
        "tags": [
          "Folders"
        ],
        "description": "Updates an existing folder at given  existing path",
        "operationId": "Update"
      }
    },
    "/{project}/_apis/build/metrics/{metricAggregationType}": {
      "get": {
        "tags": [
          "Metrics"
        ],
        "description": "Gets metrics of a project",
        "operationId": "Get Project Metrics"
      }
    },
    "/{project}/_apis/build/options": {
      "get": {
        "tags": [
          "Options"
        ],
        "description": "Gets all build option definitions",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/repos/{repoType}/badge": {
      "get": {
        "tags": [
          "Buildbadge"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/tags": {
      "get": {
        "tags": [
          "Tags"
        ],
        "description": "Gets a list of tags in the project",
        "operationId": "Get Tags",
        "security": [
          {
            "oauth2": [
              "vso.build"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/build/workitems": {
      "get": {
        "tags": [
          "Builds"
        ],
        "description": "Gets all the work item ids inbetween fromBuildId to toBuildId",
        "operationId": "Get Work Items Between Builds"
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.build": "Grants the ability to access build artifacts, including build results, definitions, and requests, and the ability to receive notifications about build events via service hooks.",
        "vso.build_execute": "Grants the ability to access build artifacts, including build results, definitions, and requests, and the ability to queue a build, update build properties, and the ability to receive notifications about build events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}