{
  "swagger": "2.0",
  "info": {
    "title": "Npm",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "content"
    },
    {
      "name": "packagesbatch"
    },
    {
      "name": "readme"
    },
    {
      "name": "Versions"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/packaging/feeds/{feedId}/npm/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_GetScopedPackageInfo",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_UnpublishScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_UpdateScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/{packageName}/versions/{packageVersion}": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_GetPackageInfo",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_UnpublishPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_UpdatePackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}/content": {
      "get": {
        "tags": [
          "Content"
        ],
        "description": "",
        "operationId": "Content_GetContentScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/@{packageScope}/{unscopedPackageName}/versions/{packageVersion}/readme": {
      "get": {
        "tags": [
          "Readme"
        ],
        "description": "",
        "operationId": "Readme_GetReadmeScopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/{packageName}/versions/{packageVersion}/content": {
      "get": {
        "tags": [
          "Content"
        ],
        "description": "",
        "operationId": "Content_GetContentUnscopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packages/{packageName}/versions/{packageVersion}/readme": {
      "get": {
        "tags": [
          "Readme"
        ],
        "description": "",
        "operationId": "Readme_GetReadmeUnscopedPackage",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}/npm/packagesbatch": {
      "post": {
        "tags": [
          "Packagesbatch"
        ],
        "description": "Update several packages from a single feed in a single request. The updates to the packages do not happen atomically.",
        "operationId": "Packagesbatch_Update",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.packaging": "Grants the ability to read feeds and packages.",
        "vso.packaging_manage": "Grants the ability to create, read, update, and delete feeds and packages.",
        "vso.packaging_write": "Grants the ability to create and read feeds and packages."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}