{
  "swagger": "2.0",
  "info": {
    "title": "Dashboard",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "Dashboards",
      "description": "Controller for CRUD operations on dashboards"
    },
    {
      "name": "Widgets",
      "description": "Controller for CRUD operations on widgets"
    },
    {
      "name": "Widget Types",
      "description": "Controller for exposing Read-only WidgetTypes"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/dashboard/widgettypes": {
      "get": {
        "tags": [
          "Widget Types"
        ],
        "description": "Returns available widgets in alphabetical order.",
        "operationId": "Get Widget Types"
      }
    },
    "/_apis/dashboard/widgettypes/{contributionId}": {
      "get": {
        "tags": [
          "Widget Types"
        ],
        "description": "",
        "operationId": "Get Widget Metadata"
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards": {
      "post": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "List",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "Replace Dashboards"
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}": {
      "delete": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "Get",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Dashboards"
        ],
        "description": "",
        "operationId": "Replace Dashboard"
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}/widgets": {
      "post": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Create",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Get Widgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Replace Widgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Update Widgets",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/dashboard/dashboards/{dashboardId}/widgets/{widgetId}": {
      "delete": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Delete",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Get Widget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards",
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Replace Widget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Widgets"
        ],
        "description": "",
        "operationId": "Update Widget",
        "security": [
          {
            "oauth2": [
              "vso.dashboards_manage"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.dashboards": "Grants the ability to read team dashboard information",
        "vso.dashboards_manage": "Grants the ability to manage team dashboard information"
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}