{
  "swagger": "2.0",
  "info": {
    "title": "Feed",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "FeedChanges"
    },
    {
      "name": "Feeds"
    },
    {
      "name": "GlobalPermissions"
    },
    {
      "name": "PackageChanges"
    },
    {
      "name": "Packages"
    },
    {
      "name": "Permissions"
    },
    {
      "name": "RetentionPolicies"
    },
    {
      "name": "Versions"
    },
    {
      "name": "Views"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/_apis/packaging/feedchanges": {
      "get": {
        "tags": [
          "FeedChanges"
        ],
        "description": "",
        "operationId": "FeedChanges_GetFeedChanges",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feedchanges/{feedId}": {
      "get": {
        "tags": [
          "FeedChanges"
        ],
        "description": "",
        "operationId": "FeedChanges_GetFeedChange",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds": {
      "post": {
        "tags": [
          "Feeds"
        ],
        "description": "",
        "operationId": "Feeds_Create",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Feeds"
        ],
        "description": "",
        "operationId": "Feeds_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/feeds/{feedId}": {
      "delete": {
        "tags": [
          "Feeds"
        ],
        "description": "",
        "operationId": "Feeds_Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Feeds"
        ],
        "description": "",
        "operationId": "Feeds_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Feeds"
        ],
        "description": "",
        "operationId": "Feeds_Update",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packagechanges": {
      "get": {
        "tags": [
          "PackageChanges"
        ],
        "description": "",
        "operationId": "PackageChanges_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "Packages_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/packages/{packageId}": {
      "get": {
        "tags": [
          "Packages"
        ],
        "description": "",
        "operationId": "Packages_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/Packages/{packageId}/versions/{packageVersionId}": {
      "get": {
        "tags": [
          "Versions"
        ],
        "description": "",
        "operationId": "Versions_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/permissions": {
      "get": {
        "tags": [
          "Permissions"
        ],
        "description": "",
        "operationId": "Permissions_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Permissions"
        ],
        "description": "",
        "operationId": "Permissions_SetFeedPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/retentionpolicies": {
      "delete": {
        "tags": [
          "RetentionPolicies"
        ],
        "description": "",
        "operationId": "RetentionPolicies_Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "RetentionPolicies"
        ],
        "description": "",
        "operationId": "RetentionPolicies_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "RetentionPolicies"
        ],
        "description": "",
        "operationId": "RetentionPolicies_SetFeedRetentionPolicies",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views": {
      "post": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Views_Create",
        "security": [
          {
            "oauth2": [
              "vso.packaging_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Views_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/Feeds/{feedId}/views/{viewId}": {
      "delete": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Views_Delete",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Views_Get",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Views"
        ],
        "description": "",
        "operationId": "Views_Update",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    },
    "/_apis/packaging/globalpermissions": {
      "get": {
        "tags": [
          "GlobalPermissions"
        ],
        "description": "",
        "operationId": "GlobalPermissions_List",
        "security": [
          {
            "oauth2": [
              "vso.packaging"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "GlobalPermissions"
        ],
        "description": "",
        "operationId": "GlobalPermissions_SetGlobalPermissions",
        "security": [
          {
            "oauth2": [
              "vso.packaging_manage"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.packaging_write": "Grants the ability to create and read feeds and packages.",
        "vso.packaging": "Grants the ability to read feeds and packages.",
        "vso.packaging_manage": "Grants the ability to create, read, update, and delete feeds and packages."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}