{
  "swagger": "2.0",
  "info": {
    "title": "Work",
    "description": "",
    "termsOfService": "https://go.microsoft.com/fwlink/?LinkId=329770",
    "contact": {
      "name": "nugetvss",
      "email": "nugetvss@microsoft.com"
    },
    "license": {
      "name": "MICROSOFT SOFTWARE LICENSE TERMS",
      "url": "https://go.microsoft.com/fwlink/?LinkId=329770"
    },
    "version": "4.1"
  },
  "host": "fabrikam-fiber-inc.visualstudio.com",
  "basePath": "/",
  "tags": [
    {
      "name": "backlogconfiguration"
    },
    {
      "name": "boardcolumns"
    },
    {
      "name": "boardfiltersettings"
    },
    {
      "name": "boardparents"
    },
    {
      "name": "boardrows"
    },
    {
      "name": "boards"
    },
    {
      "name": "boardusersettings"
    },
    {
      "name": "capacities"
    },
    {
      "name": "cardrulesettings"
    },
    {
      "name": "cardsettings"
    },
    {
      "name": "charts"
    },
    {
      "name": "columns"
    },
    {
      "name": "deliverytimeline"
    },
    {
      "name": "iterations"
    },
    {
      "name": "plans"
    },
    {
      "name": "processconfiguration"
    },
    {
      "name": "rows"
    },
    {
      "name": "teamdaysoff"
    },
    {
      "name": "teamfieldvalues"
    },
    {
      "name": "teamsettings"
    }
  ],
  "schemes": [
    "https"
  ],
  "paths": {
    "/{project}/_apis/work/boardcolumns": {
      "get": {
        "tags": [
          "Boardcolumns"
        ],
        "description": "",
        "operationId": "Boardcolumns_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/boardrows": {
      "get": {
        "tags": [
          "Boardrows"
        ],
        "description": "",
        "operationId": "Boardrows_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/_apis/work/plans": {
      "post": {
        "tags": [
          "Plans"
        ],
        "description": "Add a new plan for the team",
        "operationId": "Plans_Create"
      },
      "get": {
        "tags": [
          "Plans"
        ],
        "description": "Get the information for all the plans configured for the given team",
        "operationId": "Plans_List"
      }
    },
    "/{project}/_apis/work/plans/{id}": {
      "delete": {
        "tags": [
          "Plans"
        ],
        "description": "Delete the specified plan",
        "operationId": "Plans_Delete"
      },
      "get": {
        "tags": [
          "Plans"
        ],
        "description": "Get the information for the specified plan",
        "operationId": "Plans_Get"
      },
      "put": {
        "tags": [
          "Plans"
        ],
        "description": "Update the information for the specified plan",
        "operationId": "Plans_Update"
      }
    },
    "/{project}/_apis/work/plans/{id}/deliverytimeline": {
      "get": {
        "tags": [
          "Deliverytimeline"
        ],
        "description": "Get Delivery View Data",
        "operationId": "Deliverytimeline_Get"
      }
    },
    "/{project}/_apis/work/processconfiguration": {
      "get": {
        "tags": [
          "Processconfiguration"
        ],
        "description": "",
        "operationId": "Processconfiguration_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/backlogconfiguration": {
      "get": {
        "tags": [
          "Backlogconfiguration"
        ],
        "description": "",
        "operationId": "Backlogconfiguration_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards": {
      "get": {
        "tags": [
          "Boards"
        ],
        "description": "Get boards",
        "operationId": "Boards_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/boardfiltersettings": {
      "get": {
        "tags": [
          "Boardfiltersettings"
        ],
        "deprecated": "true",
        "description": "",
        "operationId": "Boardfiltersettings_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Boardfiltersettings"
        ],
        "deprecated": "true",
        "description": "",
        "operationId": "Boardfiltersettings_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/boardusersettings": {
      "get": {
        "tags": [
          "Boardusersettings"
        ],
        "description": "",
        "operationId": "Boardusersettings_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Boardusersettings"
        ],
        "description": "Update board user settings for the board id",
        "operationId": "Boardusersettings_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardrulesettings": {
      "get": {
        "tags": [
          "Cardrulesettings"
        ],
        "description": "Get board card Rule settings for the board id or board by name",
        "operationId": "Cardrulesettings_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Cardrulesettings"
        ],
        "description": "Update board card Rule settings for the board id or board by name",
        "operationId": "Cardrulesettings_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/cardsettings": {
      "get": {
        "tags": [
          "Cardsettings"
        ],
        "description": "Get board card settings for the board id or board by name",
        "operationId": "Cardsettings_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Cardsettings"
        ],
        "description": "Update board card settings for the board id or board by name",
        "operationId": "Cardsettings_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts": {
      "get": {
        "tags": [
          "Charts"
        ],
        "description": "Get board charts",
        "operationId": "Charts_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/charts/{name}": {
      "get": {
        "tags": [
          "Charts"
        ],
        "description": "Get a board chart",
        "operationId": "Charts_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Charts"
        ],
        "description": "Update a board chart",
        "operationId": "Charts_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/columns": {
      "get": {
        "tags": [
          "Columns"
        ],
        "description": "",
        "operationId": "Columns_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Columns"
        ],
        "description": "",
        "operationId": "Columns_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{board}/rows": {
      "get": {
        "tags": [
          "Rows"
        ],
        "description": "",
        "operationId": "Rows_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Rows"
        ],
        "description": "",
        "operationId": "Rows_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/{id}": {
      "get": {
        "tags": [
          "Boards"
        ],
        "description": "Get board",
        "operationId": "Boards_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Boards"
        ],
        "description": "Update board options",
        "operationId": "Boards_SetBoardOptions",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/boards/boardparents": {
      "get": {
        "tags": [
          "Boardparents"
        ],
        "description": "Returns the list of parent field filter model for the given list of workitem ids",
        "operationId": "Boardparents_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings": {
      "get": {
        "tags": [
          "Teamsettings"
        ],
        "description": "",
        "operationId": "Teamsettings_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamsettings"
        ],
        "description": "",
        "operationId": "Teamsettings_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations": {
      "get": {
        "tags": [
          "Iterations"
        ],
        "description": "",
        "operationId": "Iterations_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "Iterations"
        ],
        "description": "",
        "operationId": "Iterations_PostTeamIteration",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{id}": {
      "delete": {
        "tags": [
          "Iterations"
        ],
        "description": "",
        "operationId": "Iterations_Delete",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Iterations"
        ],
        "description": "",
        "operationId": "Iterations_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities": {
      "get": {
        "tags": [
          "Capacities"
        ],
        "description": "",
        "operationId": "Capacities_List",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "Capacities"
        ],
        "description": "",
        "operationId": "Capacities_ReplaceCapacities",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/capacities/{teamMemberId}": {
      "get": {
        "tags": [
          "Capacities"
        ],
        "description": "",
        "operationId": "Capacities_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Capacities"
        ],
        "description": "",
        "operationId": "Capacities_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/iterations/{iterationId}/teamdaysoff": {
      "get": {
        "tags": [
          "Teamdaysoff"
        ],
        "description": "",
        "operationId": "Teamdaysoff_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamdaysoff"
        ],
        "description": "",
        "operationId": "Teamdaysoff_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    },
    "/{project}/{team}/_apis/work/teamsettings/teamfieldvalues": {
      "get": {
        "tags": [
          "Teamfieldvalues"
        ],
        "description": "",
        "operationId": "Teamfieldvalues_Get",
        "security": [
          {
            "oauth2": [
              "vso.work"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Teamfieldvalues"
        ],
        "description": "",
        "operationId": "Teamfieldvalues_Update",
        "security": [
          {
            "oauth2": [
              "vso.work_write"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "accessToken": {
      "type": "basic",
      "description": "Personal access token. Use any value for the user name and the token as the password."
     },
     "oauth2": {
      "type": "oauth2",
      "flow": "accessCode",
      "authorizationUrl": "https://app.vssps.visualstudio.com/oauth2/authorize&response_type=Assertion",
      "tokenUrl": "https://app.vssps.visualstudio.com/oauth2/token?client_assertion_type=urn:ietf:params:oauth:client-assertion-type:jwt-bearer&grant_type=urn:ietf:params:oauth:grant-type:jwt-bearer",
      "scopes": {
        "vso.work": "Grants the ability to read work items, queries, boards, area and iterations paths, and other work item tracking related metadata. Also grants the ability to execute queries and to receive notifications about work item events via service hooks.",
        "vso.work_write": "Grants the ability to read, create, and update work items and queries, update board metadata, read area and iterations paths other work item tracking related metadata, execute queries, and to receive notifications about work item events via service hooks."
      }
    }
  },
  "security": [
    {
      "accessToken": []
    }
  ]
}